### ISSUE TITLE
Multiple Connections are Open

### ISSUE THREAD

**Issue by ansubur** [StackExchange/StackExchange.Redis#1019]
As soon as I initiate a connection using:
            Dim ConnectTo1 As String = ServerIP & ":" & ServerPort
            redisPorter = ConnectionMultiplexer.Connect(ConnectTo1)

Redis response:
           [20028] 15 Dec 00:15:35 - Accepted 127.0.0.1:55623
           [20028] 15 Dec 00:15:36 - Accepted 127.0.0.1:55624
           [20028] 15 Dec 00:15:36 - Accepted 127.0.0.1:55625

I subscribe using [node_redis](https://github.com/NodeRedis/node_redis).
        RedSubclient = redis.createClient(6379, '127.0.0.1');
        RedSubclient.psubscribe(subChannelName);

When I publish using 
        RedPub.PublishAsync(ChannelName, Message, CommandFlags.FireAndForget)

I receive 4 repeated (duplicate) messages for each message that is published. How to resolve this.

**Comment by mgravell** [comment]
This seems ... very odd. In particular, even if multiple connections were
established (which seems odd - I would expect 2 only), the publish step
writes exactly once : it selects a socket and writes to it. I can see no
mechanism whereby a single publish got sent multiple times.

I would be interested to see what happens if you pass a StringWriter to the
log pareter of connect/connectasync, to see what it says, but: again,
something seems very odd here.

Are you sure you aren't calling connect multiple times?

**Comment by ansubur** [comment]
It was due to having multiple workers.

**Comment by ansubur** [comment]
I'm using this in socketcluster. the node_redis code is inside worker.js which is started on 4 threads. Thats why it is happening, with 1 worker it doesn't repeat.
