### ISSUE TITLE
StackExchange.Redis ConnectRetry does not work as expected

### ISSUE THREAD

**Issue by IConstructor** [StackExchange/StackExchange.Redis#1025]
StackExchange.Redis does not make the connection retries which I expect.

So, I have an integration test for the connection retry. I am trying to configure StackExchange.Redis connection retrying as this:
`var configurationOptions = ConfigurationOptions.Parse(_configurationProvider.RedisPublishConnectionString);
configurationOptions.ReconnectRetryPolicy = new LinearRetry(2000);
configurationOptions.ConnectRetry = 5;`
So as you can see the number of retries is 5 and the time between each retry is 2000. As the result I expect that in the worst case it will take more than 10000, however, my tests is failing. It takes less. Sometimes it takes 9 seconds, sometimes 4 seconds.
Also I've asked this question on stack overflow: https://stackoverflow.com/questions/53906842/stackexchange-redis-connectretry-does-not-work-as-expected

**Comment by NickCraver** [comment]
Which version of the library were you trying this on? It's also unclear if it's stopping _because it succeeds_ (expected), or fails early (not expected). This changed greatly in how it's handled in 2.x, and we can pass a `StringWriter` log into the connect function to observe exactly what's happening when.

I realize this issue is quite old, but if you're still having this somewhere I'd like to get it fixed up with a decent explanation.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
