### ISSUE TITLE
ConnectionString documentation is not clear about connecting to hostname with multiple A records

### ISSUE THREAD

**Issue by kodfodrasz** [StackExchange/StackExchange.Redis#1041]
Hi!

I have a setup with a redis cluster, where all cluster members are available under a single A record:

```
redis1 - A ip1
redis2 - A ip2
redis3 - A ip3
```
and
``` 
redis - A ip1,ip2,ip3
```

It is not clear to me from the [documentation](https://stackexchange.github.io/StackExchange.Redis/Configuration) if the following two are equivalent:

```
var conn = ConnectionMultiplexer.Connect("redis1,redis2,redis3");
```
and 

```
var conn = ConnectionMultiplexer.Connect("redis");
```

Some other clustered software support this feature, some not. Please clarify the docs about the topic, and if it is not supported why is it not (not done yet, or explicit decision).

Thank You!

**Comment by NickCraver** [comment]
Good question! They are not equivalent. For instance, a server in one data center may use DNS devolution to go to the more-local cluster though the A record has IPs across each subnet for say multiple data centers. The responses from an `A` query will be ordered by the resolver based on the locality of the requester in these scenarios which isn't quite split horizon (almost is though), it's just the order that's different so that the local data center is preferred.

By specifying only `"redis"` in your connection string, it'll choose the first IP (as determined by the OS). If however you _tell_ the client to do it: `"redis,resolveDns=true"`, *then* we'll resolve all the IP endpoints and it'll behave the same way.

Hope this helps!

**Comment by kodfodrasz** [comment]
Hi!

Thanks for the answer, this totally helps!

Do you think the docs should be extended with this example? For me this wasn't trivial from reading the linked documentation page, but maybe its just me.

**Comment by NickCraver** [comment]
@kodfodrasz Since this hasn't come up again, I'm going to close out to tidy up. Overall: I don't think we should add to the docs because _it's determined by the OS_ and it's best we don't duplicate that documentation (likely incorrectly) for users :)
