### ISSUE TITLE
Is there any "GetAllKeysByPrefix" like method ?

### ISSUE THREAD

**Issue by BlowaXD** [StackExchange/StackExchange.Redis#1048]
Hello,

I would like to know if there is an actual way to have something like "GetAllKeysByPrefix" ?

I'm using Foundatio framework and it looks like it's not possible (or I'm probably wrong) to do that with their actual architecture, so I'm willing to add it and request it for addition on their framework.
As they are using StackExchange.Redis client.

[Here is the issue talking about it](https://github.com/FoundatioFx/Foundatio/issues/128)

Thanks by advance,
Blowa.

**Comment by mgravell** [comment]
The Keys method accepts a glob pattern, so wildcards like "yourprefix*"
should work fine. The Keys method is on the server API, not the database
API, because it is a per-server operation:
https://stackexchange.github.io/StackExchange.Redis/KeysScan

Note however that it is a *terrible* idea to sue this API *routinely* in
production. It simply isn't something that redis is good at. Common
workarounds include things like sets of key names.

**Comment by BlowaXD** [comment]
Thanks for your answer, I already had the idea of sets with keynames, I think I will probably go for that solution which seems to be a good way to save both compute time and code writing.
