### ISSUE TITLE
How to get all keys and values with C# client?

### ISSUE THREAD

**Issue by mr-mohsen** [StackExchange/StackExchange.Redis#1049]
I have installed _StackExchange.Redis 2.0.519_  and  _StackExchange.Redis.Extensions.Core 4.0.5_  via Nuget Packet Management to get connect with a remote Redis server.

```
ConnectionMultiplexer redisUsers = ConnectionMultiplexer.Connect("192.168.30.251:6379");
IDatabase db_Users = redisUsers.GetDatabase();
Dictionary<string , long> AllUsers = new Dictionary<string, long>();

```
How do i read all the keys and values using this C# client?

**Comment by mgravell** [comment]
How are the values stored? Is it a "hash" (in the redis sense) that
contains all users? Or is each user a "string"? It matters. In particular,
crawling all keys (the "string" option) is inefficient in redis, but see
https://stackexchange.github.io/StackExchange.Redis/KeysScan

If it is a "hash", then just HashGetAll should do everything.

**Comment by NickCraver** [comment]
Judging by the upvote this seems addressed, so closing out to cleanup :)

**Comment by Ivan-2NE1** [comment]
How to get all keys and values with C# client?
This problem is fully solved?
How to check value types if it is string or hash or list or .... with C# client?

**Comment by mgravell** [comment]
> How to get all keys and values with C# client?

There is no **single** API in redis that is "get all keys and values"; to get all keys, `IServer` (`GetServer()`)  and `.Keys(...)`

Getting the values is per-key and depends on what you want to do with them; useful APIs are `KeyType` and `KeyDump`, beyond that you might want the per-type operations.

If you tell me *what you're trying to do* I can probably add more guidance

**Comment by gorlasreekanth** [comment]
hi @mgravell, in our scenario we have three operations,
1. Add/update value for a key (very frequent, per request)
2. Remove key (very frequent, once per few request)
3. Read all the keys (occasional)

and we have another dimension of partitions in our usecase that keys are contained in partitions. in this reg. is there a way to store keys in redis separately to each partition so that operations in two different partitions are not blocking each other.

thank you.

**Comment by mgravell** [comment]
The server core on redis is single threaded, so any long running operation will block other operations. Options, depending on your needs:

1. don't perform long-running operations; this is why `SCAN` should be used instead of `KEYS`
2. perform large read operations on a replica node
3. using "cluster" (server topology) and "hash tags" (key topology), intentionally shard the data between multiple servers
4. combine 3 with 2 and use a shard replica

On non-cluster, redis databases (i.e. `select`) can be used to logically partition keys, but note that this doesn't change server impact (it does make it easy to, for example, drop an entire cohort of associated keys, though)
