### ISSUE TITLE
Why the method GetServer causes the increasing threads?

### ISSUE THREAD

**Issue by Humour0625** [StackExchange/StackExchange.Redis#1069]
@I have a simple redis web application and found some code interesting, which cause the high CPU usage. So I did some tests. Here are the basic codes which are very simple.

public class RedisCacheConnector
    { 
        public static IDatabase GetDatabase()
        {
            return Connection.GetDatabase();
        }
        private static ConnectionMultiplexer Connection
        {
            get { return ConnectionMultiplexer.Connect(GetConfiguration()); }
        }

        public static IServer GetServer()
        {
            return Connection.GetServer("10.10.*.*", 6379);
        }
}

Program.cs  some test code.

   static void Main(string[] args)
        {
            while(true)
            {
                var td = new Thread(new ParameterizedThreadStart(test));
                td.Start();
                Thread.Sleep(5000);
            }
        }

        private static void test(object obj)
        {
            var redisServer = RedisCacheConnector.GetServer();
            Console.WriteLine("Key:" + Guid.NewGuid().ToString() + "Thread id: " + Thread.CurrentThread.ManagedThreadId);
        }
From the resource monitor, the threads from the console exe are increasing .
Could everyone tell me what happened in the backgroud of the API? Will it create a new Thread within the GetServer() Method? why the thread does not stop ? I have the reflector installed, but seems nothing happened from there. Is there some other method I need to call after I use the IServer? like stop, dispose.
Things go well after I cache the IServer object.

StackExchange.Redis.StrongName  1.2.6.0

**Comment by mgravell** [comment]
The problem you're having here is that every time you touch `Connection`, you are getting a **different** connection instance. In 1.2.6, this meant: threads; you *don't* get extra threads in 2.*, but that's moot : frankly, the "fix" here is to not create a new `ConnectionMultiplexer` all the time - they are *expensive*; you want to get one *once* and reuse it. If you're using "static" (and whether or not that is appropriate is another discussion), then I would suggest:

    private static ConnectionMultiplexer Connection {get; } = ConnectionMultiplexer.Connect(GetConfiguration());

which is the same *idea*, except that it is only created once

**Comment by Humour0625** [comment]
You mentioned I don't get extra threads in 2.*. What does this mean? I use the StackExchange.Redis.StrongName and it seems it's still in the version of 1.*. Do you mean I should use the StackExchange.Redis instead? How can I decide which dll I should add reference. Maybe my question is so simple, but If you can help answer it, it will much appreciated. Thanks @mgravell

**Comment by mgravell** [comment]
Threads - 2.0 has a different threading model. Although in this case the real problem is the constant creation of multiplexers, which is bad for *any* version.

Strong naming: in 2.*, the main SE.Redis package is strong named. As such, the .StrongName package is no longer useful, and so has not been updated.

**Comment by Humour0625** [comment]
OK, so the strongName package cannot be used any more, and I should use the StackExchange.Redis package, right? As it will require the .net 4.6.1 or above, but my project still uses the 4.5. Maybe I need to wait another chance to reference it. Do you think I can use the strongName package for a while or need to use the main package right now? If the strongName package is not enough stable,  i think I need to do it right now.

**Comment by mgravell** [comment]
In 1.* builds, the StrongName package is identical in every respect other
than the strong name.

If you require .NET Framework 4.5, then you are limited to 1.* - the 2.*
tooling requires net461 as the minimal version currently, IIRC - although
if you're looking to update, it would make more sense to jump straight to a
net47* or net48* level.

So: your only option for now is 1.2.6; whether you choose strong-named or
not is up to you. To reiterate: having 2 identical packages was clcausijg
problems, so since we were already making breaking changes in 2.0, it made
sense to solve the strong naming problem for once and for all.

**Comment by Humour0625** [comment]
Thanks @mgravell .
