### ISSUE TITLE
RedisValue.Unbox

### ISSUE THREAD

**Issue by Lukiya** [StackExchange/StackExchange.Redis#1079]
`object value = 1;
RedisValue.Unbox(value );`

throw "Unable to cast object of type 'System.Int32' to type 'StackExchange.Redis.RedisValue" error.

**Comment by mgravell** [comment]
The `RedisValue.Unbox` method is only currently intended to be used with values that were obtained via `RedisValue.Box`; `Box` would never return a boxed `Int32` (it would return a boxed `RedisValue`), so `Unbox` doesn't expect to handle it. The main purpose of `Box`/`Unbox` here is to avoid creating an *additional* object when the value inside the `RedisValue` is *already* an object - specifically, a `string` or `byte[]` (or a `null`, which... OK isn't actually an object, but doesn't need boxing).

That said, though... I *can* see some utility in some minor changes to this method - a boxed `RedisValue` is actually oversize for what we need; we *could* make it instead box the remaining values as `Int64` / `Double`, and if we did *that* it would perhaps be reasonable for `Unbox` to also operate against `Int32` / `Single`, as convenience features.

But: before I hack on that - can I clarify what your intended usage is, so that I can plan accordingly?

**Comment by mgravell** [comment]
(actually it seemed pretty obvious and straight-forward, so I just hacked it in)
