### ISSUE TITLE
How to implement "redis.cli --raw" option in StackExchange.Redis?

### ISSUE THREAD

**Issue by wangxu047** [StackExchange/StackExchange.Redis#1080]
How to implement "redis.cli --raw" option in StackExchange.Redis?

**Comment by mgravell** [comment]
Can we take a step back? What exactly is it that you're trying to do? And for what purpose?

Normally, SE.Redis always deframes results, giving them back as structured / parsed data; usually this means specific .NET types, but it can also be the more obtuse `RedisResult` (which can represent any RESP frame, including arbitrarily deep trees). The `Execute[Async]` and the `ScriptEvaluate[Async]` methods return `RedisResult`.

Can I assume that this isn't what you want? If so: what *do* you want? are you after something that returns the raw RESP byte-stream for a given reply? This isn't something we currently expose, but it wouldn't be impossible to add - I'm just curious about the intended usage to a: evaluate applicability, and b: determine the most reasonable API. Of particular note: one pragmatic option might actually be to have a mechanism for `RedisResult` to *write the equivalent RESP stream* - the advantage here being that it doesn't need huge API changes - just a new method(s) on the existing `RedisResult` type. And most of the code actually already exists (albeit in a different context).

**Comment by wangxu047** [comment]
> Can we take a step back? What exactly is it that you're trying to do? And for what purpose?
> 
> Normally, SE.Redis always deframes results, giving them back as structured / parsed data; usually this means specific .NET types, but it can also be the more obtuse `RedisResult` (which can represent any RESP frame, including arbitrarily deep trees). The `Execute[Async]` and the `ScriptEvaluate[Async]` methods return `RedisResult`.
> 
> Can I assume that this isn't what you want? If so: what _do_ you want? are you after something that returns the raw RESP byte-stream for a given reply? This isn't something we currently expose, but it wouldn't be impossible to add - I'm just curious about the intended usage to a: evaluate applicability, and b: determine the most reasonable API. Of particular note: one pragmatic option might actually be to have a mechanism for `RedisResult` to _write the equivalent RESP stream_ - the advantage here being that it doesn't need huge API changes - just a new method(s) on the existing `RedisResult` type. And most of the code actually already exists (albeit in a different context).

Thanks for your reply, Without "--raw" option, it will get messy code when receving chinese string message from subscribed channel.

**Comment by mgravell** [comment]
No... it won't. RESP is a binary-safe protocol, and subscriptions expose a `RedisValue`. The only reason that `redis-cli` needs a `--raw` option is because it is trying to display arbitrary binary data on a console that doesn't support full unicode, and without knowing what *encoding* (if any) was used to encode the data. The "if any" there is because there's no actual reason that a `publish` payload even needs to be text-based in the first place - it could be a protobuf message, for example, or some other non-text binary form.

Now; the interesting question is: what **actually** got sent in the `publish`? You mention a "chinese string message", but that doesn't actually mean anything to RESP : RESP always deals in *bytes*, not strings. So what *really* matters is : in the code that did the `publish`, what **encoding** did they use?

If you're using SE.Redis to do the publish, and you sent a .NET `string`, then this will be encoded as UTF8; likewise, if you use SE.Redis to *receive* a value that you then interpret as a .NET `string`, then it will be decoded as UTF8, and everything will work fine.

If you're using a different client/platform/framework to do the `publish`, and that client/platform/framework *also* uses UTF8 encoding, then once again, it'll all just work fine.

If you're using a different client/platform/framework to do the `publish`, and it uses a **different** encoding (something other than UTF8), then *at that point* you might need to do some work yourself. You can cast a `RedisValue` to a `byte[]` or `ReadOnlyMemory<byte>`, which you can use with any `Encoding`, so if the text is encoded with UTF7, UTF16, UTF32, or some obscure codepage: just *use the right one* and decode it.

**Comment by wangxu047** [comment]
Got it，Thanks。
