### ISSUE TITLE
await ConnectionMultiplexer ConnectAsync does not wait

### ISSUE THREAD

**Issue by imtrobin** [StackExchange/StackExchange.Redis#1099]
Hi, I just found that using 

await ConnectionMultiplexer.ConnectAsync (connectionString) 

does not really wait for connect to succeed before returning. I have to use non async version to do that. Is that by design?

**Comment by mgravell** [comment]
It should do... what symptom are you seeing here? What makes you think it
isn't connected?

**Comment by imtrobin** [comment]
My assert to check if Redis is connected is triggered after the ConnectAsync calls. If I replace the Connect without Async, then it does not trigger

`public bool  IsRedisConnected  { get { return null != redisConnection_ && redisConnection_.IsConnected;  } }
`

**Comment by mgravell** [comment]
There is a toggle in the connection options for exactly this, and the
default should be "throws", from memory. Are you sure the connection
options don't specify something like "abort on failed connect=false"?
(Sorry - on mobile, I can't lookup the exact string)

**Comment by mgravell** [comment]
Note: the connect methods also take an optional text writer. It may be
illuminating to pass in a StringWriter or similar, and look at what it says
after the connect attempt.

**Comment by imtrobin** [comment]
This is my setup, I will put in the text writer and check

```
var config                  = ConfigurationOptions.Parse (connectionString);
config.AbortOnConnectFail   = true;
config.KeepAlive            = 10;
config.SyncTimeout          = 1000;
config.ReconnectRetryPolicy = new ExponentialRetry (5000); // defaults maxDeltaBackoff to 10000 ms

//redisConnection_ = await ConnectionMultiplexer.ConnectAsync (config);
redisConnection_ = ConnectionMultiplexer.Connect (connectionString);

redisConnection_.ErrorMessage += ((object sender, RedisErrorEventArgs args)=> 
{
    ReportRedisError ($"Redis Error:{args.Message}");
});

redisConnection_.InternalError += ((object sender, InternalErrorEventArgs args) => 
{
    ReportRedisError ($"Redis Internal Error:{args.Exception.Message}");
});

redisDB_ = redisConnection_.GetDatabase ();

// assert fails later in calls
```

**Comment by imtrobin** [comment]
Ok ,I found the problem. I was not using await when I was getting back the instance at higher code. Sorry for the false alarm.

**Comment by Rajeev-kumar22** [comment]
Tried everything but ConnectAsync is not working even tested with exact code available in GutHub for ASP.Net best practices, below is the code and URL. -   

https://github.com/Azure-Samples/azure-cache-redis-samples/blob/main/quickstart/aspnet/ContosoTeamStats/RedisConnection.cs 

Interlocked.Exchange(ref _connection, null);
                ConnectionMultiplexer newConnection = await ConnectionMultiplexer.ConnectAsync(_connectionString);
                Interlocked.Exchange(ref _connection, newConnection);

                Interlocked.Exchange(ref _lastReconnectTicks, utcNow.UtcTicks);
                IDatabase newDatabase = _connection.GetDatabase();
                Interlocked.Exchange(ref _database, newDatabase);

**Comment by Rajeev-kumar22** [comment]
HI marc gravell

I am stuck with library StackExchange.Redis" version="2.1.58 library Update to latest one-2.6.45 at the time of our release.  Now we are facing an application crash issue due to the below exception. Now I am seeing this library has been deprecated with 2.6.48. Could You please suggest with what version, we should continue in our application and how to resolve the issue below.



Thread 11592
ExitCode E0434352
ExitCodeString CLR EXCEPTION
DefaultHostName p6infrappsrvuiprdsea01.azurewebsites.net
Managed Exception = StackExchange.Redis.RedisTimeoutException:Timeout performing UNLINK (2000ms), next: UNLINK ff30g301hczve223anmcs3km_LoginDetails, inst: 401, qu: 17, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 565, serverEndpoint: P4InfrProdRedisC01.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD00155DF31AF0(SE.Redis-v2.6.45.45955), IOCP: (Busy=1,Free=999,Min=500,Max=1000), WORKER: (Busy=208,Free=32559,Min=500,Max=32767), v: 2.6.45.45955 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
CallStack - Managed Exception
========================================================
     StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[[System.Boolean, mscorlib]](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1<Boolean>, StackExchange.Redis.ServerEndPoint, Boolean)
     StackExchange.Redis.RedisDatabase.KeyDelete(StackExchange.Redis.RedisKey, StackExchange.Redis.CommandFlags)
     ISF.AzureRedisCache.AzureRedisCacheOperations.RemoveValueByKey(System.String)
     ISF_WEB.Util.RedisKeyspaceNotifications+<>c__DisplayClass0_0+<<RedisKeysNotifications>b__0>d.MoveNext()
     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     System.Threading.ThreadPoolWorkQueue.Dispatch()
CallStack - Crashing Thread
========================================================
     HelperMethodFrame
     System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     HelperMethodFrame
     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     System.Threading.ThreadPoolWorkQueue.Dispatch()
     DebuggerU2MCatchHandlerFrame
     ContextTransitionFrame
     DebuggerU2MCatchHandlerFrame

 Native Call Stack
========================================================
KERNELBASE!RaiseException
clr!RaiseTheExceptionInternalOnly
clr!IL_Rethrow
clr!ExceptionTracker::CallHandler
clr!ExceptionTracker::CallCatchHandler
clr!ProcessCLRException
ntdll!RtlpExecuteHandlerForUnwind
ntdll!RtlUnwindEx
clr!ClrUnwindEx
clr!ProcessCLRException
ntdll!RtlpExecuteHandlerForException
ntdll!RtlDispatchException
ntdll!KiUserExceptionDispatch
KERNELBASE!RaiseException
clr!RaiseTheExceptionInternalOnly
clr!IL_Throw
clr!CallDescrWorkerInternal
clr!CallDescrWorkerWithHandler
clr!MethodDescCallSite::CallTargetWorker
clr!QueueUserWorkItemManagedCallback
clr!ManagedThreadBase_DispatchInner
clr!ManagedThreadBase_DispatchMiddle
clr!ManagedThreadBase_DispatchOuter
clr!ManagedThreadBase_DispatchInCorrectAD
clr!Thread::DoADCallBack
clr!ManagedThreadBase_DispatchInner
clr!ManagedThreadBase_DispatchMiddle
clr!ManagedThreadBase_DispatchOuter
clr!ManagedThreadBase_FullTransitionWithAD
clr!ManagedPerAppDomainTPCount::DispatchWorkItem
clr!ThreadpoolMgr::ExecuteWorkRequest
clr!ThreadpoolMgr::WorkerThreadStart
clr!Thread::intermediateThreadProc
<img width="794" alt="Application Error" src="https://user-images.githubusercontent.com/38314687/177568487-a7febb26-21d6-4e23-bba7-8fc7246887a0.PNG">

kernel32!BaseThreadInitThunk
ntdll!RtlUserThreadStart

**Comment by mgravell** [comment]
Hi, I believe you also emailed me directly; I'd already responded to that
one when I saw this.
