### ISSUE TITLE
Unsubscribe not removing subscriptions made with ChannelMessageQueue Subscribe

### ISSUE THREAD

**Issue by BrennanConroy** [StackExchange/StackExchange.Redis#1101]
`ISubscriber.UnsubscribeAsync(channelName)` does not unsubscribe subscriptions made with the new channel queue `ISubscriber.SubscribeAsync(channelName)`.

```
var channel = await _bus.SubscribeAsync("name");
channel.OnMessage(channelMessage =>Task.CompletedTask);
await _bus.UnsubscribeAsync("name"); // does not unsubscribe
```

**Comment by mgravell** [comment]
Will look first thing tomorrow morning. Sorry for delay, was working on a stability fix.

**Comment by mgravell** [comment]
You're right, something isn't working quite right there; however! In this case, you don't need it - the following works as a workaround (and is the intended usage):

``` c#
await channel.UnsubscribeAsync();
```

I'll make sure the other path gets fixed, though

**Comment by mgravell** [comment]
k; to explain what was happening here: we have two types of subscriptions - "things we trust not to steal our thread" (i.e. our own code, which includes the `ChannelMessageQueue` implementation), and "things we don't trust at all" (i.e. anything that used the older API). The most significant difference between them is that if we don't trust it not to steal the thread, we need to dispatch the callback to a worker. If we trust the code, we can just invoke it inline.

So: because the "old" API (taking a delegate directly) is the "untrusted" path, we push that into the "untrusted" bucket; and indirectly, `UnsubscribeAsync(channel, null)` was *also* saying "this is the legacy API, you can't trust me!", so it was only *clearing* the untrusted bucket. When what it probably *should* do is: clear *both* buckets.

So: fixed next deploy; since a workaround exists (above), I'm not pushing it as an "urgent"

**Comment by mgravell** [comment]
if you want a preview: [r592 on myget](https://www.myget.org/feed/stackoverflow/package/nuget/StackExchange.Redis)

**Comment by mgravell** [comment]
and nuget: https://www.nuget.org/packages/StackExchange.Redis/2.0.593
