### ISSUE TITLE
300ms for 1000 StringGet 

### ISSUE THREAD

**Issue by minhhungit** [StackExchange/StackExchange.Redis#1119]
I'm not sure if this is an issue, but I see that StringGet is taking **300** ms to process 1000 StringGet()

My test code here:
```csharp
class Program
{
    static ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost");
    static IDatabase db = redis.GetDatabase();

    static void Main(string[] args)
    {
        string value = "abcdefg";
        db.StringSet("mykey", value);

        Stopwatch stopwatch = Stopwatch.StartNew();
        for (int i = 0; i < 1_000; i++)
        {
            var x = db.StringGet("mykey", flags: CommandFlags.None);
        }
        stopwatch.Stop();
        Console.WriteLine(stopwatch.Elapsed.TotalMilliseconds);

        Console.ReadKey();
    }
}
```

I installed Redis on windows 3.0.504 at [here ](https://github.com/MicrosoftArchive/redis/releases)

Btw, I also did a test with ServiceStack.Redis (both v5 and v3 - just for compare) and they took 90-100 ms for 1000 StringGet

so my question is: 
I don't know if 300 ms is a big number, is it normal behavior ? 
If it's really slow, what did I do wrong?

P/S: This is image with redis-benchmark.exe

![image](https://user-images.githubusercontent.com/2279508/55945584-49c3ab80-5c75-11e9-8b7d-18159f5dd146.png)

Thank you!

**Comment by minhhungit** [comment]
FYI
I tested with 100_000 StringGet, StackExchange.Redis took **30 seconds**, 
while ServiceStack v3 took only **3 seconds**

I have to say that I am a big fan of StackExchange libraries but this make me confuse 

[DemoRedis.zip](https://github.com/StackExchange/StackExchange.Redis/files/3067919/DemoRedis.zip)

**Comment by mgravell** [comment]
What library version are you testing with, so I can take a look?

**Comment by mgravell** [comment]
Also: the redis benchmark test is based on 50 concurrent clients. For that
to be meaningful, you'd have to set up 50 threads sharing the multiplexer.

**Comment by minhhungit** [comment]
Hello @mgravell 

>What library version are you testing with, so I can take a look?

I used the latest version of StackExchange.Redis 2.0.600

I also attached project which I used to test https://github.com/StackExchange/StackExchange.Redis/files/3067919/DemoRedis.zip

**Comment by dme-development** [comment]
@minhhungit: Did you continue your investigation? What was the conclusion?

@mgravell: Did you have a look at the demo test project? Without comparing with the Redis benchmark, the performance difference between the two client libraries looks really big.

**Comment by minhhungit** [comment]
@dme-development: no I did not, that's everything I know

**Comment by NickCraver** [comment]
Just tidying up old issues here. We're basically just not comparing apples here. For example, redis-cli is 50 concurrent clients. On this laptop I've only got 8 cores, but let's compare the core of the test:
```c#
for (int i = 0; i < 1_000; i++)
{
    var x = db.StringGet("mykey", flags: CommandFlags.None);
}
```
This runs in **286-297ms**, let's call it the 300ms filed here. We agree that's the performance!

Now, let's make it parallel. This will depend on your machine's core count. In my case it's 8 logical cores:
```c#
Parallel.For(0, 1_000, new ParallelOptions() { MaxDegreeOfParallelism = 50 }, i =>
{
	var x = db.StringGet("mykey", flags: CommandFlags.None);
});
```
This drops us down to **25-28ms**. A huge win. Let's further this and optimize for the fact we're dealing with a pipeline and make it all async:
```c#
Task<RedisValue> lastTask = default;
for (int i = 0; i < 1_000; i++)
{
	lastTask = db.StringGetAsync("mykey", flags: CommandFlags.None);
}
await lastTask;
```
This drops us down to **1.8-3.2ms**. 

So...it's about using the tech to achieve what you want here. Let me compare the above scenarios:
1. Simple `for` loop: here we have **1 thread** waiting synchronously for each result before sending the next. That's losing tons of performance waiting on round trips.
2. `Parallel.For` loop: here we have **n threads** waiting synchronously for each result before sending the next. That's got the same issues as option 1, we just have more of those workers in parallel.
3. Async `for` loop: This takes full advantage of the pipeline. Instead of sending 1 request for data and waiting for the reply before asking for the next piece of data, we ask for all of them *as soon as possible*. This means all of the requests are on their way to Redis possibly before the first reply comes back. We're not just waiting, we're *doing*, and the pipe is flowing. The requests come back in order. The above example only waits on the _last_ reply to illustrate: it's a pipeline, that's all we need to do. You should be asking "great...but what if I actually want the results?" Good question! We just track the `Task`s like this:
```c#
List<Task<RedisValue>> tasks = new List<Task<RedisValue>>(1_000);
for (int i = 0; i < 1_000; i++)
{
	tasks.Add(db.StringGetAsync("mykey", flags: CommandFlags.None));
}
await Task.WhenAll(tasks);
```
...and in that we have all of our results for usage. It adds very little overhead with only 1,000 in play, maybe ~1ms.

Overall, we want to throw the work on the thread pool and let it do that work _as soon as it is able_ to maximize throughput. It's all about how you use it knowing a little bit about how it works behind the scenes.

I hope the above is useful!

**Comment by minhhungit** [comment]
@NickCraver thank you, it's really useful.
Agree with you, I recognized that in real work we won't send request to redis synchronously, one by one. Even if we have to get it synchronously then 1 request just take only 0.3ms. That is NOT bad !!!
