### ISSUE TITLE
Keyspace subscribe doesn't work with keys with * in the name

### ISSUE THREAD

**Issue by damongr** [StackExchange/StackExchange.Redis#112]
The following code in RedisSubscriber.cs method SubscribeToServer
```C#
var cmd = channel.Contains((byte)'*') ? RedisCommand.PSUBSCRIBE:RedisCommand.SUBSCRIBE;
```

The problem arrives if you happen to have a key with a * in the name. You then try to subscribe to keyspace events on channel:
`"__keyspace@0__:Example*Key"`
This doesn't work with PSUBSCRIBE against keyspace events for some reason.
It would be good if ISubscriber.Subscribe allowed you to pick which type of subscription and not do it for you based on the channel name. This also doesn't work because it doesn't take into account other PSUBSCRIBE pattern characters like ? or [ ] etc. Allow the developer to pick which kind of PUB/SUB they want to do.
Suggestion, put it in the RedisChannel struct, like IsPattern or something.

**Comment by NickCraver** [comment]
When you're subscribing to keys using special characters, use a `\` to escape them. So instead of `*` in the key, you'll need `\*` (`\\*` in most cases for the `\` escape itself). I don't think a new pattern variable is needed because it's controllable by the user already via escaping, which matches the command line options.

Does that make sense and cover your use cases?
