### ISSUE TITLE
System.Buffers, Version=4.0.3.0 error with "Azure Functions"

### ISSUE THREAD

**Issue by ashuthinks** [StackExchange/StackExchange.Redis#1121]
I have used `System.Buffers, Version=4.0.3.0 ` in one class library.

ClassLibrary1.csproj 

Created one Azure function and refer this  class library dll inside Azure Function.

When run the Azure function getting below exception , any clue why it is not working. 

![git-err](https://user-images.githubusercontent.com/3287696/56017732-d3c74f00-5d1d-11e9-8e06-35d02b08cf5e.png)

**Comment by mgravell** [comment]
The problem is a missing assembly binding redirect. Unfortunately I don't
know a lot about azure functions - or: I know enough to know that in the v1
of azure functions, it was virtually impossible to *add* assembly binding
redirects. But "how do I add a binding redirect in azure functions" is
where I'd start.

**Comment by NickCraver** [comment]
I've since written up why this happens in https://nickcraver.com/blog/2020/02/11/binding-redirects/, but the causes and fixes are not specific to this library. We have added builds for `net462` and `net472` to make this _less_ likely to happen, but fundamentally it is an issue with .NET assembly loading and there's nothing further we can do about it. I hope the above post helps - that's the limit of what we're able to help with overall.
