### ISSUE TITLE
Why can't I await KeyMoveAsync from an ITransaction object?

### ISSUE THREAD

**Issue by VitorCioletti** [StackExchange/StackExchange.Redis#1125]
I need to create a transaction so I used `db.CreateTransaction()` to get an `ITransaction`. However, the code gets stuck when I await `KeyMoveAsync(RedisKey, int)`, the following code only works without awaiting it.

- Why there is no sync `KeyMove(RedisKey, int)` method?
- Why does this code gets stuck?

```cs
var transaction = db.CreateTransaction();
            
// Does not execute this line
await transaction.KeyMoveAsync(myKey, indexDatabase);
            
if (await transaction.ExecuteAsync())
     // my code
```

Thanks in advance :)

**Comment by mgravell** [comment]
Firstly, note that if you're only performing one operation then it is *already* atomic and you don't need a transaction at all. Transactions only really make sense when you are doing one of:

- performing multiple operations as an atomic unit, and/or
- using the "conditions" API to check that something is unchanged

If you *do* want to use transactions, then: nothing is sent to the server until you call `ExecuteAsync`, since it doesn't know in advance what commands you want to be considered atomic. So: invert the order:

``` c#
var movePending = transaction.KeyMoveAsync(myKey, indexDatabase);
if (await transaction.ExecuteAsync())
{
    var moveResult = await movePending;
    // todo: test what this was, if needed
}
```

**Comment by VitorCioletti** [comment]
@mgravell Thanks for the quick reply.

> Note that if you're only performing one operation then it is already atomic and you don't need a transaction at all

There are only one operation to keep this example clean and simple to people understand. I am really doing lots of operations in my transaction.

> If you do want to use transactions, then: nothing is sent to the server until you call ExecuteAsync, since it doesn't know in advance what commands you want to be considered atomic

But does the object `ITransaction` really need to have `KeyMoveAsync` as an async method? I believe it could be a lot simpler if there were a method `KeyMove` to perform operations in a transaction in order to avoid the problem i have just faced. In this situation, `await KeyMoveAsync(myKey, dbIndex)` just goes to the void, causing me some time to understand and solve.

**Comment by mgravell** [comment]
it can't possibly be synchronous - again, nothing is sent until the `Execute[Async]`, so a synchronous operation cannot complete.

**Comment by mgravell** [comment]
I agree that it isn't ideal that we can't intercept the `await` attempt and raise a "hey, you need to call execute before you can await" exception. Oddly enough, if we were using `ValueTask[<T>]` instead of `Task[<T>]`, there is actually a way I could do that, but: AFAIK, it just isn't possible with `Task[<T>]`.

**Comment by VitorCioletti** [comment]
> it can't possibly be synchronous - again, nothing is sent until the Execute[Async], so a synchronous operation cannot complete.

Got it.

>  I agree that it isn't ideal that we can't intercept the await attempt and raise a "hey, you need to call execute before you can await" exception.

Now I got your point.

Thanks for helping me.

:)
