### ISSUE TITLE
Could not uninstall from windows 10

### ISSUE THREAD

**Issue by dewelloper** [StackExchange/StackExchange.Redis#1134]
I have installed StackExchange.Redis.StrongName for trying instead of the StackExchange.Redis to my Asp.Net core 2.2 project on windows 10.
But it gave me confilict with the StackExchange.Redis like your assembly exist both!
I have not uninstalled the strongnamed project from my computer. Even they removed all projects but refference always seem to that. Please show me how can i uninstall? like a virus :) ?

https://stackoverflow.com/questions/55829849/how-to-change-a-nuget-packet-assembly-version/55862747#55862747

**Comment by mgravell** [comment]
are you targeting `Microsoft.AspNetCore.All`? it has a transitive dependency via `Microsoft.Extensions.Caching.Redis` to `StackExchange.Redis.StrongName`.

So: don't target `.All` - that is just a convenience package that takes **everything**.

**Comment by dewelloper** [comment]
Hi mgravell!
I have installed Microsoft.AspNetCore.All the day before but i have removed from the project fully yesterday in spite of uninstalling the Microsoft.AspNetCore.All and StackExchange.Redis and StackExchange.Redis.StrongName from nuget manager even from temporary folder error has continued. 
I understand that uninstalling package with nuget just working right with -force argument. With this manner i have uninstalled StackExchange.Redis but couldnt find and uninstall the StackExchange.Redis.StrongName. I think its interesting .net core 2.2 i because while deleting from project file i noticed it has providing removing from the project. After that i think to upgrade project .net core framework from 2.2 to 3.0 maybe it will not sees StackExchange.Redis.StrongName and realy it work out!
Thanks and for your information

**Comment by NickCraver** [comment]
I know this is late, but what I suggest for anyone hitting this is using `dotnet depends` (project: https://github.com/mholo65/depends) which will let you know where transitive dependencies are coming from. It's a console program that's very handy for this.

**Comment by dewelloper** [comment]
Yes I close this

**Comment by ShivaniY4W** [comment]
I try t uninstall the StackExchange.Redis.StrongName package but it could not . tell me how can I uninstall this package

**Comment by mgravell** [comment]
@ShivaniY4W we can't answer that directly because we can't see your project. However:

- if you are referencing it yourself, there will be a PackageReference in your project file that includes "StackExchange.Redis.StrongName" : remove that line!
- if you are getting it transitively, then *some package you are using* is adding the package reference; there is no way of removing the transitive dependency without removing the thing that is adding it; I can't tell you what package might have a transitive dependency, because I can't see your project and I don't know what packages you're using
