### ISSUE TITLE
why page size ignored,returns all elements (version 2.0.601)

### ISSUE THREAD

**Issue by mfjiang** [StackExchange/StackExchange.Redis#1146]
server.Keys(1,"*abc",100,CommandFlags.None);
here returns all elements, why page size ignored / not working?
my package version 2.0.601

Server Features in 3.2.12
BitwiseOperations: True
ClientName: True
ExecAbort: True
ExpireOverwrite: True
Geo: True
HashVaradicDelete: True
HyperLogLogCountSlaveSafe: True
IncrementFloat: True
InfoSections: True
ListInsert: True
MillisecondExpiry: True
MultipleRandom: True
Persist: True
PushIfNotExists: True
Scan: True
Scripting: True
ScriptingDatabaseSafe: True
SetConditional: True
SetPopMultiple: True
SetVaradicAddRemove: True
SortedSetPop: False
Streams: False
StringLength: True
StringSetRange: True
SwapDB: False
Time: True
Unlink: False

**Comment by mgravell** [comment]
The page size isn't being *ignored*; it just isn't doing what you *think*. When you use `Keys(...)` (which maps to `SCAN` usually), it still iterates the entire keyspace (if you read it to the end) - what changes is the *number of round trips*.

i.e. imagine that there are 2000 keys; if you use a page size of 100, you'll get all 2000 keys but behind the scenes it'll use approximately 20 round trips; if you use a page size of 500, you'll get all 2000 keys but behind the scenes it'll use approximately 4 round trips.

If you want to get only the first 100, then use `.Take(100)`; the iterator being used here is lazy in the appropriate ways, and will stop correctly when used with things like `.Take(...)`. Since the page size is only guidance, not a strict rule, I'd round up a little to minimize extra round trips... for example, if I wanted the first 100, I'd probably use:

``` c#
var firstHundred = server.Keys(1,"*abc",120,CommandFlags.None).Take(100).ToList();
```

**Comment by mgravell** [comment]
Note also: when you use a filtered search (`"*abc*"`), behind the scenes redis still needs to walk the entire keyspace, so the notes on page size become more complex... if you have lots of keys and most of them don't match the pattern, then it is possible that most pages are actually empty; each round-trip to redis is basically "some amount of work at crawling the keyspace, i.e. try approximately 500 keys to see if they match"; it is **not** "get the next 500 keys that match". This is done (at the server, not the client) so that each call has predictable time.

To rephrase that: since you're doing a **filtered** search, it is impossible for me to say how many round-trips it will take in your case, but: choose a page size that works for you - higher means fewer round-trips, but each trip monopolizes the server for longer.

**Comment by mfjiang** [comment]
thank you, i get it.
