### ISSUE TITLE
Setting abortConnect to false on Azure

### ISSUE THREAD

**Issue by mataness** [StackExchange/StackExchange.Redis#1169]
Based on Azure Redis docs, it is recommended to set abortConnect to false when running on Azure (https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-faq ).
When set to false, ConnectionMultiplexer should retry to connect on the background when failed to connect on the first attempt.

I have done some testing by myself, and intentionally tried to create a ConnectionMultiplexer by providing it a DNS endpoint to a Redis cache that doesn't exist.
I've also provided a TextWriter to see the logs from the ConnectionMultiplexer.

I didn't see any attempts to reconnect on the background, only the first 3 attempts as connectRetry defaults to 3.

Shouldn't it better to set abortConnect to true, and implement a custom retry logic ?

**Comment by NickCraver** [comment]
I think I understand the confusion here, to demonstrate what's happening I wrote up a quick LINQPad example:
```c#
async Task Main(string[] args)
{
	var sw = new StringWriter();
	ConnectionMultiplexer muxer = ConnectionMultiplexer.Connect("fakehost,abortConnect=false",log: sw);
	// Important: this log is _as of right now_, we don't log past the initial connection to it
	sw.Dump("Connection Log");
	
	// Demonstrate it keeps trying
	for (var i = 0; i < 100; i++)
	{
		// This increments every 2 seconds
		muxer.GetCounters().Interactive.SocketCount.Dump("Socket Attempt Count");
		await Task.Delay(1000);
	}
}
```
I think the disconnect is the log you're passing in is _only_ for the initial connection (with 3 reties). But if you continue to watch the counters on any connection, you'll see it keeps retrying. In the above example the count will increase on average every 2 loops (since it's a 2 second retry by default). It's doing what you want, I think the logging is just misleading here since that's _as of the return_. Does that make sense?
