### ISSUE TITLE
Multiple databases are not supported on this server; cannot switch to database

### ISSUE THREAD

**Issue by ichnb** [StackExchange/StackExchange.Redis#1188]
uses multiple databases and it tries to read or write to a database other than 0, the following exception is thrown，i used aliyun redis 4.0 cluster

Unhandled Exception: StackExchange.Redis.RedisConnectionException: ProtocolFailure on GET ---> StackExchange.Redis.RedisCommandException: Multiple databases are not supported on this server; cannot switch to database: 6

**Comment by mgravell** [comment]
Indeed, regular redis cluster doesn't support the concept of databases. The error message is correct, unless you're saying that "aliyun redis 4.0 cluster" has different rules. I've never heard of that, so I'd need to investigate.

**Comment by mgravell** [comment]
by "aliyun", is it possible that you mean "aiven"? I can't find "aliyun"

**Comment by WeihanLi** [comment]
@mgravell "aliyun" is a cloud service provider like azure or aws

**Comment by mgravell** [comment]
OK; you'll understand that I have limited ability to explore their service. Is this *actually* running in redis-cluster mode, yet supports multiple databases? Are you **absolutely sure about that?** - because that isn't something that regular redis does, which is why the client is stopping you. Have you confirmed this works via `redis-cli` or similar? i.e.

``` redis
select 6
get "foo"
```

?

Because what I would expect to see is (from my local desktop):

``` redis
127.0.0.1:7000> select 6
(error) ERR SELECT is not allowed in cluster mode
```

**Comment by ichnb** [comment]
This is not a component issue, like you said,"SELECT is not allowed in cluster mode", Thanks for help !
