### ISSUE TITLE
Discrepancy in GetEndpoints(false) output for Cluster/NonCluster endpoints

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#1208]
Hi

There seems to be a discrepancy in the way `GetEndpoints(false)` works for Cluster and NonCluster Redis endpoints. `GetEndpoints(true)` works as expected. 

Specifically I tested it on the Azure Redis Cache.

For NonCluster endpoints `GetEndpoints(false)` returns only one endpoint which is the public DNS endpoint in the form 'mycache.redis.cache.windows.net'. It won't show direct IP addresses for the primary and secondary replicas.

For Cluster endpoints it would return 2xN+1 endpoints where N is the amount of shards. First endpoints would be the public DNS endpoint. The rest of 2xN endpoints would be direct IP addresses for primary and secondary replicas of N shards.

Is it because StackExchange.Redis has no knowledge about Azure Redis internals when it connects to NonCluster endpoint for when in Cluster mode Azure Redis exposes all internals as a part of Cluster API?

Thanks,
Pavel

**Comment by NickCraver** [comment]
> Is it because StackExchange.Redis has no knowledge about Azure Redis internals when it connects to NonCluster endpoint for when in Cluster mode Azure Redis exposes all internals as a part of Cluster API?

Yep, pretty much this. Some more info:

Have you tried using `resolveDns=true`? Normally we just connect to the DNS endpoint _and let the OS/socket handle it_. Unless you'd prefer we manually resolve all endpoints, in which case we try to connect to those IPs specifically (that's what `resolveDns=true` in the connection string instructs).

For a cluster, we _must_ resolve and handle all endpoints - it's just the nature of the beast. We have to deal with all nodes. In other cases, we can't assume you'd want to connect to every A record, as there are many reasons we shouldn't (e.g. dual A records for multi-region failover).

Doe the above help? The behavior you're seeing is intentional, just trying to explain the "why" :)

**Comment by paveliak** [comment]
Thank you. I will try `resolveDns=true`. Meanwhile closing since it's an expected behavior and besides `GetEndpoints(true)` could be used to address the difference (pretty much this is what I did in our code).
