### ISSUE TITLE
netstandard required with .net framework 4.6.2

### ISSUE THREAD

**Issue by sumit4bansal** [StackExchange/StackExchange.Redis#1229]
I am trying to use StackExchange.Redis in my project which is in .net framework 4.6.2. When I am running the application, I am getting following error

Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

is netstandard needed to run  StackExchange.Redis or I am missing something?

**Comment by lAnubisl** [comment]
I have faced similar issue. In my case the problem is that netstandard is referenced along with all it's dlls which generates conflicts with existing .net framework references.
Looks like starting from StackExchange.Redis v2 netstandard is referenced in .net framework project because of this dependencies chain:
StackExchange.Redis -> Pipelines.Sockets.Unoficcial -> System.Buffers -> NetStandard 2.0
Looks like System.Buffers does not have ANY .net framework build

**Comment by mgravell** [comment]
System.Buffers has a net45 build. There's no obvious reason for a gap here, unless transitive dependencies have failed again. And from memory, yes: System.Buffers is one of those that is a bit... "delicate" on this

**Comment by lAnubisl** [comment]
@mgravell Not sure about "again" but here is the bug https://github.com/dotnet/corefx/issues/37639 their NuGet package contain only 

- netstandard1.1
- netstandard2.0
- netcoreapp2.0

**Comment by NickCraver** [comment]
The issue there is referencing what's _being pulled in_. The package does have a `net45` build, you can see it on NuGet: https://www.nuget.org/packages/System.Buffers/

The issue seems to be some binding/loading fun though...there are soo many combinations of issues here to debug sanely and that's why we still bundle both 4.6.1 and 4.7.2 builds to minimize the problems with loaders - really that's the _only_ reason we still build more than `netstandard2.0`. If you're having loader issues still, unfortunately that's framework territory.

What's being experienced here is not a common thing we see - it's something I'd be looking at the `dotnet` repos for (`dotnet/runtime` now, I think).
