### ISSUE TITLE
Pipeline with StringGetAsync with multiple keys slower than StringGet

### ISSUE THREAD

**Issue by ShwetaDeep** [StackExchange/StackExchange.Redis#1231]
I am trying to test calling redis with multiple keys in MGET call and notice that pipelining requests results in higher latency than multiple blocking calls in parallel. 
Why should that be the case since as I understand reading from the documentation, pipeline should result in lower latency than blocking call? 

Here's sample code snippet using pipeline vs. parallel blocking calls. Parallel blocking calls is order of magnitude faster than pipeline which is confusing to me.

	var cache = muxer.GetDatabase();	
       // pipeline		
        for(int i = 0; i < batch.Count(); i++)
        {
            tasks.Add(cache.StringGetAsync(batch[i]));
        };

        foreach (var t in tasks)
        {
            cache.Wait(t);
        }		

	// same number of blocking calls in a parallel for loop
        var results = cache.StringGet(batch);	

Will greatly appreciate insight into this behavior.

Thanks,
Shweta

**Comment by NickCraver** [comment]
In this case you're adding the overhead of a task collection (that's resizing as you go based on exponential growth) and a manual `.Wait()` blocking call on the end of them. Overall, you're going to be adding work that's burning CPU to accomplish. Since it's a pipeline, you can just await the last call (batch) and you'll know all will be ready at that point. Does that make sense?
