### ISSUE TITLE
 unknown command 'FT.CREATE'

### ISSUE THREAD

**Issue by Tameenk** [StackExchange/StackExchange.Redis#1284]
i got error  unknown command 'FT.CREATE' when trying to create index

this is my code

Client client = new Client("testIndex", database);
            Schema sc = new Schema()
                .AddTextField("Id", 1.0)
                .AddTextField("Name", 5.0)
                .AddTextField("Country", 1.0)
                .AddTextField("City", 1.0);
            client.CreateIndex(sc, Client.IndexOptions.Default);

           
            for (int i = 0; i < 300; i++)
            {
                Dictionary<String, RedisValue> fields = new Dictionary<String, RedisValue>();
                fields.Add("Id", i+1);
                fields.Add("Name", "Name " + i+1);
                fields.Add("Country", "Country " + i +1);
                fields.Add("City", "City " + i+1);
                client.AddDocument("d1", fields);
            }

**Comment by gkorland** [comment]
It seems like your Redis doesn't have the RediSearch module loaded. See redisearch.io

**Comment by Tameenk** [comment]
I'm using .net core 2.2 and i have installed StackExchange.Redis & NRediSearch is there any other package ?

**Comment by gkorland** [comment]
I'm talking about the Redis Server you're connecting to, it seems like the server doesn't have RediSearch module loaded.

The quickest way to run Redis server with the ReidSearch module loaded is just run the docker container this way you can verify if that was the issue.
```
docker run -p 6379:6379 redislabs/redisearch:latest
```

**Comment by Tameenk** [comment]
@gkorland thanks it works now with docker image , so my question now how can i add this module on windows ?

**Comment by gkorland** [comment]
do you run the redis server on windows?

**Comment by Tameenk** [comment]
yes i did

**Comment by gkorland** [comment]
https://redislabs.com/blog/redis-on-windows-10/

**Comment by Tameenk** [comment]
I already have installed redis server on windows 10 but i just need to add redis search module

**Comment by mgravell** [comment]
There are 2 ways to load a module; you can call the `MODULE LOAD` command against the server, or you add the module to the server's config file. Bother are mentioned here: https://redis.io/commands/module-load

I'm going to close this down, simply because it isn't really a library concern (other than to point you in the right direction)

**Comment by gyana12** [comment]
hi All, i was trying to install RedisSearch module but don't how to do that, Using below command
redis-cli --cluster call 127.0.0.1:30001 MODULE LOAD redisearch.so OPT1 OPT2

someone told me what would be value for OPT1 and OPT2

**Comment by roppa** [comment]
In docker compose I'm using `redislabs/redisearch:latest`. Yet when I run `FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT value NUMERIC` I get `ERR unknown command FT.CREATE`

**Comment by mgravell** [comment]
The command is still [`FT.CREATE`](https://oss.redislabs.com/redisearch/Commands.html#ftcreate), so: it it isn't working, it sounds like a problem with the docker setup. Is that your local setup, or one of ours?

**Comment by roppa** [comment]
This is very strange. I was using docker-compose:

```
version: '3.2'
services:
  redis:
    image: 'redislabs/redisearch:latest'
    command: redis-server
    ports:
      - '6379:6379'
```

running command `module list` I got an empty list. Then using docker for the same image, it works. 🤔

**Comment by samifouad** [comment]
Because this is still an issue with RediSearch 2.0 w/ docker, and this page comes up in Google:

if you look at the default docker files for RediSearch, it launches search module as a Docker CMD arg

In my testing, it seems like adding your own config file will for some reason make Docker ignore the CMD arg to launch the search module

The quick fix for this is two options:

1) add extra 'loadmodule' command to docker run
`docker run -d --rm -p 6379:6379 -v /var/redis/data:/data -v /var/redis/redis.conf:/usr/local/etc/redis/redis.conf --name redis redislabs/redisearch:latest redis-server /usr/local/etc/redis/redis.conf  --loadmodule /usr/lib/redis/modules/redisearch.so`

2) add 'loadmodule' in your custom redis.config:
`# load search module
loadmodule /usr/lib/redis/modules/redisearch.so`

Running `module list` command inside redis-cli will now show you search is loaded with either of these methods

I honestly think this is more of a Docker issue than a Redis issue, so not much can be done to solve it by Redis team
