### ISSUE TITLE
Redis Timeout- Timeout performing EVAL, inst: 1, mgr: Inactive, err: never, queue: 31, qu: 0, qs: 31, qc: 0, wr: 0, wq: 0, in: 0, ar: 0

### ISSUE THREAD

**Issue by pankajkumishra** [StackExchange/StackExchange.Redis#1286]
Timeout performing EVAL, inst: 1, mgr: Inactive, err: never, queue: 31, qu: 0, qs: 31, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: XYZ, serverEndpoint: Unspecified/ABC.redis.cache.windows.net:6380, keyHashSlot: 4338, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=2,Free=32765,Min=4,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

What could be the reason for this timeout?

**Comment by pankajkumishra** [comment]
Can some body help me with resolution of this problem?

**Comment by deepakkanswal** [comment]
Did you get any solution? I'm Having the same problem.

**Comment by pankajkumishra** [comment]
I did not get any solution yet. I am planning to increase the retry count and see if this resolves.

**Comment by mgravell** [comment]
Hi @pankajkumishra  - sorry for delay, but unfortunately this isn't our day job, so we can't always leap on things. What is your script doing here? is there any chance it genuinely is just a long running script? context will probably help

**Comment by pankajkumishra** [comment]
The application maintains the session in Azure Redis. We see this error once/twice in a month but couldn't figure out what is causing it.

**Comment by mgravell** [comment]
This gets a little harder to diagnose because of TLS. If it wasn't for TLS I'd say that I was content this was a network or server stall. With TLS in the mix: harder to be sure - could be stalled in the TLS layer.

However! Ultimately, sometimes sockets just die, especially in cloud/hosted scenarios. You will never find out why. This is true of redis, TDS (SQL Server), HTTP[S], FTP, etc. If this is happening rarely, frankly I probably wouldn't get too excited.

How much pain is this causing?

**Comment by NickCraver** [comment]
It appears you're using the old version of the client as well (more recent updates would include the version number) - is this happening in the latest 2.x release?
