### ISSUE TITLE
WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by Tameenk** [StackExchange/StackExchange.Redis#1288]
I got this error WRONGTYPE Operation against a key holding the wrong kind of value 
this is my example of my code

                Dictionary<string, string> value;
                value = service.GetResources("translations", lang);
                string serializeValue = JsonConvert.SerializeObject(value);
                database.SetAdd("translations", serializeValue);

               // i got error here in the below code
                var valueFromCache =  database.StringGet("translations");

**Comment by mgravell** [comment]
This seems correct and expected. You've added something to a set (a specific redis type), and are accessing it as a string (another specific, but different, redis type), but it is probably one of:

- use `StringSet` instead of `SetAdd`, if you intended to use a string
- use any of the `Set*` methods instead of `StringGet` if you intended to use a set

Can you clarify what you expected here? That will tell me how to advise you here.

**Comment by Tameenk** [comment]
Thanks StringSet , StringAppend & StringGet works for me
