### ISSUE TITLE
SyncTimeout exception meaning: inst is high, qs have also value, serverEndpoint starts with Unspecified

### ISSUE THREAD

**Issue by humayun-ahmed** [StackExchange/StackExchange.Redis#1292]
Hello guy, can you please help to find out where is the problem, I am getting exception most of the time like following:
Every of the case inst and qs is high, and serverEndpoint starts with Unspecified
1. Why serverEndpoint starts with Unspecified?
2.  inst and qs is high represents client side problem or aws redis side problem?

GetCacheObject: Key: {a328db2f-0a66-41e0-ab1a-408d94258264}UserFeatureSetsData_3b6c3d01-8938-466f-aea5-23b0a9070088, LastGetDuration: 00:00:01.5568732:
Timeout performing GET (1500ms), next: GET {a328db2f-0a66-41e0-ab1a-408d94258264}DivisionData_97037, inst: 205, qu: 0, qs: 10, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/******-developmentprod.ga7gjk.euw1.cache.amazonaws.com:6379, mgr: 10 of 10 available, clientName: NLC1DEOL145, PerfCounterHelperkeyHashSlot: 4212, IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=36,Free=32731,Min=8,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts):

**Comment by NickCraver** [comment]
> 1. Why serverEndpoint starts with Unspecified?

This is just how `DnsEndpoint` prints in .NET, for example:
```c#
new DnsEndPoint("example.com", 6379).ToString()
```
Yields: `Unspecified/example.com:6379`

The "unspecified" means "any" network type and the OS chooses what wins, contrasted with say explicitly asking for IPv4:
```c#
new DnsEndPoint("example.com", 6379, AddressFamily.InterNetwork).ToString()
```
In which case you get: `InterNetwork/example.com:6379`

> 2\. inst and qs is high represents client side problem or aws redis side problem?

`inst` means the amount of requests sent since the last heartbeat - that means they're send and haven't been completed. `qs` means the amount we sent to Redis, awaiting a rely.

We want to look at the other values though: you have 36 busy threads, which may be a little hot for a small application, but we also have `in:0` which means nothing has come back from Redis to process.

Overall, you're using a 1.5 second timeout in a cloud environment. Unfortunately, in the cloud you don't control the network - it is shared, can have hiccups, and you'll never know the reason of most issues. It looks like a network stall here and if you want to tolerate those (and not timeout), I'd recommend something a lot higher on your timeout, like 5000ms.
