### ISSUE TITLE
Q: any particular reason for using polling select in socket manager?

### ISSUE THREAD

**Issue by ppanyukov** [StackExchange/StackExchange.Redis#130]
Looking at the socket manager, there are two versions:

- polling, using select;
- other (assume completion ports?)

That other is used only with SSL option. For everything else select is used.

The questions are:

- any particular reason for select in non-SSL connections?
- wouldn't it be better to use completion ports for everything?
- should we change the default?
- perhaps make it configurable?

This came across when my profiler indicated 20ms (out of 100ms) was spent in select. There is a probability it's lying somewhat but maybe not.

Happy to explore this further if there are no immediate reasons why we can't use completion ports.

**Comment by NickCraver** [comment]
We use #1 due to the TPL stealing threads and general threadpool starvation leading to timeouts due to completions not running, SE.Redis uses a dedicated reader thread instead. We see a lot of issues on the starvation side at Stack Overflow scale, so it's mostly due to handling cases for which the TPL just isn't ideal. If only we could control threadpool growth patterns...
