### ISSUE TITLE
SortedSetRangeByValue question

### ISSUE THREAD

**Issue by WeihanLi** [StackExchange/StackExchange.Redis#1312]
I'm trying to get values via SortedSetRangeByValue, but not behave as expected, what is the `orderBy` logic?

``` csharp
var redis = ConnectionMultiplexer.Connect("127.0.0.1");
var db = redis.GetDatabase();

var zSetKey = "testZSet";

db.SortedSetAdd(zSetKey, Enumerable.Range(1, 1000).Select(i => new SortedSetEntry(i, 0)).ToArray());

var values = db.SortedSetRangeByValue(zSetKey, min: 90, max: int.MaxValue, take: 5L, order: Order.Ascending, exclude: Exclude.Start);
 
```

the values I got always an empty array

![image](https://user-images.githubusercontent.com/7604648/71432331-dfc03900-2713-11ea-9997-2c81b8e1cc77.png)

**Comment by konstantinsuslov** [comment]
Hi, @WeihanLi the key is lexicographical order, redis returns no values to your request because there is no values between 90 and int.MaxValue. I think it would be more clear if I make and example. Due to arithmetic order there is no values in range [100; 11], but in lexicographical order there are 12 values (values are taken from your example)
<img width="321" alt="Screenshot 2020-01-29 at 20 01 08" src="https://user-images.githubusercontent.com/12987653/73379007-8929ba00-42d2-11ea-8b29-acdd58b78d53.png">
