### ISSUE TITLE
Cannot get correct number of subscribers while using Redis clustering

### ISSUE THREAD

**Issue by yuaw** [StackExchange/StackExchange.Redis#1328]
SE.Redis version 2.0.601

I am using SE.Redis with Azure Redis cache and wanted to use Pub/Sub. I enabled Redis clustering and set the shard to 1. Publisher can get the correct number of subscribers.

However, I increased the shard to 3 from 1 and then the number of subscribers varied.

Publisher code:

            var host = "yuawprem.redis.cache.windows.net:6380";
            var input = "";
            var channelName = "yuaw";
            using (var conn = lazyConnection.Value)
            {
                var server = conn.GetServer(host);
                Console.WriteLine($"Database:{server}");
                while (true)
                {
                    Console.WriteLine($"Please, specify message to be send to `{channelName}`");
                    input = Console.ReadLine();
                    if (string.IsNullOrWhiteSpace(input))
                        break;
                    var subscriber = conn.GetSubscriber();
                    var numberOfSubscribers = subscriber.Publish(channelName, input);
                    Console.WriteLine("Message '{0}' was sent to '{1}'. And this channel has '{2}' subscribers", input, channelName, numberOfSubscribers);
                }
            }

Subscriber code:

            var host = "yuawprem.redis.cache.windows.net:6380";
            var channelName = "yuaw";
            using (var connection = lazyConnection.Value)
            {
                var server = connection.GetServer(host);
                Console.WriteLine($"Database:{server}");
                var subscriber = connection.GetSubscriber();
                // subscribe a channel
                //await subscriber.SubscribeAsync(channelName, (channel, message) =>
                //{
                //    Console.WriteLine($"{channel} - {message}");
                //});

                subscriber.Subscribe(channelName).OnMessage(channelMessage =>
                {
                    Console.WriteLine(channelName + " - " + (string) channelMessage.Message);
                });

                Console.WriteLine("Press any key!");
                Console.ReadKey();
            }

Screenshot:
![image](https://user-images.githubusercontent.com/7676957/72874458-08e0e300-3d2d-11ea-910c-bc114d77638d.png)

As you see, I have 3 subscribers but the publisher could not retrieve the correct number of subscribers.

Ask:
How to get the correct number of subscribers while using Redis clustering?

**Comment by NickCraver** [comment]
There's no way to do this in Redis cluster (without overlapping messages) because the API in Redis itself is _per server_, the variance you see is how many subscribers happen to be subscribed to the same shard as you are. It's possible Redis could add an API for this but as it stands I'm not aware of any that exist, sorry! It's part of the nature of reducing dependencies and increasing resiliency in cluster itself, some of the data/state isn't readily available.

**Comment by NickCraver** [comment]
@slorello89 do you know of a proper way to support this? I'm not aware of any current way _today_, maybe we'd have to explicitly query each cluster node or something? (and assume we're connected to them all, which may not be accurate)

**Comment by slorello89** [comment]
@NickCraver - I believe your intuition is correct, you would need to call `PUBSUB NUMSUB` on each node in the cluster, this is because the PUBSUB commands provide you the pub/sub context for the current shard and not for the whole cluster. 

That said there is a new Shard-based pubsub API in Redis 7 that would make the API @yuaw work as they expect it would. You would use `SPUBLISH` and `SSUBSCRIBE` rather than `PUBLISH`/`SUBSCRIBE`. This would force your publishing/subscribing to a single shard per channel based off the hash slot of the channel. See redis/redis#8621. The client would naturally have to direct the request to the correct shard so there may be a bit more complexity to supporting those commands on SE.R's end, as I'm not sure how it selects the shard its meant to go to for Pub/Sub right now, my wild guess is that you have some sort of least-loaded or round-robin algorithm to decide which server to talk to.

**Comment by NickCraver** [comment]
I'm going to close this out to tidy up for now - if sharded pub/sub comes along we'll add support but in the current state looks like we're properly mirroring server behavior and this will need to change in both.
