### ISSUE TITLE
SocketClosed Exception on Azure Cache for Redis

### ISSUE THREAD

**Issue by ismkdc** [StackExchange/StackExchange.Redis#1329]
Hello everyone,
I have asp.net core 3.1 app on azure k8s service and i am using stackexhange.redis 2.0.601 and i am seeing too many redis error on log.
like:
"SocketClosed on blablabla.redis.cache.windows.net:6380/Interactive, Flushing/MarkProcessed, last: GET, origin: ReadFromPipe, outstanding: 2, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.0.601.3402"

"It was not possible to connect to the redis server(s). To create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout"

Can you help me?

**Comment by n1l** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/871
Is it helpfull?

**Comment by NickCraver** [comment]
This looks like a legitimate networking issue, where the socket was severed and the command was lost due to that (we're alerting you to that fact so you can optionally take some action...not pretending everything is okay).

Are you using the `abortConnect=false` in your connection string as recommended? Azure specifies this in their help because there may be a transient issue in startup or a race in your app starting up vs. the Redis server being available.

**Comment by ismkdc** [comment]
We solved problem like that:
` private static string _connectionStr;
        private static readonly Lazy<ConnectionMultiplexer> _lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            return ConnectionMultiplexer.Connect(_connectionStr);
        });

        public static ConnectionMultiplexer GetConnection(string connectionStr)
        {
            if (_connectionStr == null)
                _connectionStr = connectionStr;

            return _lazyConnection.Value;
        }`

**Comment by SirMrDexter** [comment]
Hi @ismkdc ,

Wondering what prompted you to make that change and if had any issues after that code change. We just upgrade one of our application to .net core 3.1 as well and every since we deployed it to production, we are seeing similar errors in our environment. we are using stackexhange.redis 2.0.593 in our solution.

We do have `abortConnect=false` in our connection string.

Here's a sample of the error we got.
```
Timeout awaiting response (outbound=5KiB, inbound=0KiB, 5719ms elapsed, timeout is 5000ms), inst: 0, qu: 0, qs: 7, aw: False, rs: DequeueResult, ws: Idle, in: 0, serverEndpoint: Unspecified/SOMESERVER.redis.cache.windows.net:6380, mgr: 9 of 10 available, clientName: RD00155D699CFA, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=11,Free=8180,Min=2,Max=8191), v: 2.0.593.37019 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 
```
