### ISSUE TITLE
PhysicalConnection.OnBridgeHeartbeat Potential Performance Issue?

### ISSUE THREAD

**Issue by AlanMacdonald** [StackExchange/StackExchange.Redis#1330]
Hello,

we recently upgraded from 1.1.608 to 2.0.601 which has been a disaster in production.  Some of the issues were our related code (but most of this was unchanged between releases) but it seems like 2.0.601 is much more prone to throwing timeout exceptions.  One of the dump analyses we looked pointed to ~900 threads being blocked trying to acquire the lock in PhysicalConnection.GetCounters.  There was a thread blocked getting a lock on OnBridgeHeartbeat as well for 2.5 minutes.

Which made me look into PhysicalConnection.OnBridgeHeartbeat since that was not in 1.1.608.  There is a lot of code running inside the lock code if some messages have been detected to have timed out. Which made me wonder, if there are many messages timing out and that then causes this code to take longer before releasing the lock on _writtenAwaitingResponse then is that likely to cause even more messages to timeout as they wait on the lock?  At a minimum it blocks other threads even if the chance of a timeout is unaffected.

Could this implementation quickly identify the timed out messages, dequeue them and put them in a collection so the lock can be released quicker before then post processing them to do all the work around generating the error messages etc?

I don't know this code base so these are just questions and I could be way off. Clearly things have to start getting timed out in the first place for this block of code to do significant work but does it compound it?

**Comment by NickCraver** [comment]
Good question! We can't easily change how this works because there's a pipeline in play. Just because we've timed out getting responses doesn't mean _we aren't getting the results_. For example, if the head of the message queue is a 100MB payload blocking others, Redis is likely sending them as requested and we need to process them. We need to process the message pipeline _in order_ or we don't know which replies went with which messages and we have to just kill everything (or offer random response data corruption). That's worse than waiting on the lock.

Ultimately, we need to process these in order. The fact we're in a lock with a huge message count to time out is a _symptom_ of a bottleneck issue (there to prevent further cascading resource failure - like any timeout), rather than directly the issue.

If there's a large item like this, we recommend using a secondary connection that doesn't block things behind it (assuming order isn't important). Or, crank timeouts if order is important. Marc has a proposal we're thinking about for connection pooling as well, see https://github.com/StackExchange/StackExchange.Redis/issues/886 for that!
