### ISSUE TITLE
"No connection is available to service this operation: INFO" on slave instances

### ISSUE THREAD

**Issue by EricWu91** [StackExchange/StackExchange.Redis#1343]
I have two Redis instances in the connection string, with one acting as the slave and other as the master.

`Redis = ConnectionMultiplexer.Connect("10.30.7.10:6379,10.30.7.11:6379, allowAdmin=true");`

I know that 10.30.70.11 is acting as slave because I ran INFO against it in redis-cli, and got the following:

![image](https://user-images.githubusercontent.com/9344516/73877622-c42e6f00-4837-11ea-87f6-cd6813b298d9.png)

However, calling it like this:

`Redis.GetServer(endpoint).Info("Replication").First().First(i => i.Key == "role").Value`

throws the exception

![image](https://user-images.githubusercontent.com/9344516/73877784-0f488200-4838-11ea-9edd-0815e5ce6109.png)

I'm using Linqpad for testing purposes, but the error is the same in a MVC5 (.Net Framework) application.

**Comment by mgravell** [comment]
Huh. Odd. Is the replica under any high load?

**Comment by EricWu91** [comment]
Nope. I'm just setting it up for evaluation purposes. 

`redis-cli -- stat` reports:

![image](https://user-images.githubusercontent.com/9344516/73904510-0f1da600-487b-11ea-8050-1f3d814f3d9e.png)

**Comment by EricWu91** [comment]
... Anyone?

**Comment by EricWu91** [comment]
Weirdly, I just tested the call again, and it worked. I'm not sure how; everything was stalled until yesterday.

... Weird. Anyways, I don't even think this issue should be kept.

**Comment by NickCraver** [comment]
What might have been happening here is a data set load from disk when the replica was restarting. If so, the way to diagnose this would `INFO` on the master to see where the replication is with the replica instance(s).

What I see in your config that stands out is that replica backlog size. It's only a megabyte...if you've got a lot of traffic, it won't be able to replica the data set and start the sync to the replica until that circular buffer is overrun. If that happens, it restarts the sync...and this happens in a loop. I'd bet this is _likely_ what was happening based on your first byte offset in the backlog. That number is what you do a modulus of against the buffer size to figure out where in the circular backlog buffer you are.

If your case, it's written 28,405,040 to a 1,048,576 byte buffer, which means you've exhausted that buffer 27 times since startup. Depending on your spiky your data mutation is (reads won't have anything to buffer), it may well be exhausting your buffer before the slave gets a chance to get synced and catch up. After that, the buffer acts as a "catch up without a full resync" mechanism.

I recommend the following tweaks to your config:
```
repl-backlog-size 20mb
```
(the default is the `1mb` you're on)
And if your disks are slow, eliminate them from the syncing process (it's marcked as experimental, but we've been using it without issues at Stack Overflow for many years):
```
repl-diskless-sync true
```
For more explanations on each, [check our the official `redis.conf` here](http://download.redis.io/redis-stable/redis.conf)

Hope that helps!
