### ISSUE TITLE
SubscribeAsync - why cannot await for the subscribed message?

### ISSUE THREAD

**Issue by CCabrita** [StackExchange/StackExchange.Redis#1353]
Hi,
I am using StackExchange.Redis v1 in a .Net 4.5  legacy project.
I am wondering why `Task SubscribeAsync(RedisChannel channel, Action<RedisChannel, RedisValue> handler, CommandFlags flags = CommandFlags.None)` does not support a Func rather then an Action, as I would love  to  be able to await for the subscribed message - basically would be nice to have:

```
public async Task Subscribe(string channel, Func<string, Task<string>> handler)
        {
            var connection = _stackExchangeRedisDatabase.GetConnection();
            var sub = connection.GetSubscriber();
            await sub.SubscribeAsync(channel, async (_, message) =>
           {
                await handler(message.ToString());
           });

        }

```

**Comment by mgravell** [comment]
As for the "why": because historically, it just dispatches the work to the thread pool. Arguably, a claim could be made that this is similar to the "it is OK for event-handlers to be `async void`" point. Meaning: you could just *invoke an `async void`*. Alternatively, if you're not going to do anything with the result of handler: just throw it away! (`_ = handler(message.ToString())`. Nobody is looking either way, after all.


You *may* also prefer the other overload that returns a `ChannelMessageQueue`, then; once you have that, you can do *whatever you want* in your own reader loop.

**Comment by CCabrita** [comment]
Thanks for the prompt reply.
It would be a good shout for using the `Subscribe()` that returns `ChannelMessageQueue`, although I think this is only available from v2 which is not compatible with .Net 4.5? There are constraints that prevent me from upgrading this framework at the moment, but will consider your suggestion if this changes.

**Comment by NickCraver** [comment]
Options given above, so closing out to cleanup :)
