### ISSUE TITLE
.Net Core lua sciprt to return a tuple

### ISSUE THREAD

**Issue by ghetze** [StackExchange/StackExchange.Redis#1368]
Hi,
I'm struggling to create a lua script in .net core wich will return a tuple<string,string>.
The idea is to get the key and the pttl of that key , for a list of keys.
I've managed to do this using the code bellow but i get an array of 2 arrays which is pretty ugly to work with afterwards.
Is there a way to modify the script to return an tuple or something similar ?
Thank you...
```
const string luaScriptReturnExpiry =
                @"local result = {}
                    for i,key in ipairs(KEYS) do 
                        local pttl = redis.call('pttl', key)
                        result[i] = {key,pttl}
                    end
                    return result";

                var keysWithExpiry = (RedisResult[])await _msisdnPlatformIdMessageIdDB.ScriptEvaluateAsync(luaScriptReturnExpiry, keys.ToArray());
```
'''

**Comment by mgravell** [comment]
Personally, I wouldn't bring back the keys *at all*; since order is preserved, why not just bring back a single array that is the pttls, matched by position to the original keys. You can always combine the inputs and outputs after they've returned from the server; this would be simpler *and* more efficient (less to encode/transfer/decode); example:

``` lua
for i,key in ipairs(KEYS) do 
    result[i] = redis.call('pttl', key)
end
```

---

If you really want to bring back both, then you need to be thoughtful of what RESP is capable of expressing; at the RESP2 level, what we're mainly dealing with here is arrays and blob-strings; your Lua code creates an array of length (number of keys), where each element is an array of length 2, with the key and the TTL. I *suspect* a better approach here would be to create a single array of length 2 * (number of keys), and interleave the values, i.e. key/pttl/key/pttl/key/pttl; in pseudo-code (i.e. I haven't tested it!):

``` lua
local index = 0;
for i,key in ipairs(KEYS) do 
    local pttl = redis.call('pttl', key)
    result[index++] = key
    result[index++] = pttl
end
```

(I'm not a Lua expert, so the `++` usage might need tweaking)

The *reason* for this is that interleaved values is the expectation for maps, and what you're creating is basically a map. We *should* probably expose a "decompose a map in the usual/expected way" API; it certainly exists internally, but it may not exist on the public API today.

**Comment by NickCraver** [comment]
Advice above - closing out to cleanup!
