### ISSUE TITLE
StackExchange.Redis.RedisServerException:“EXECABORT Transaction discarded because of previous errors.”

### ISSUE THREAD

**Issue by weisenzcharles** [StackExchange/StackExchange.Redis#1372]
```
if (_db.LockTake("LockKey", Token, TimeSpan.FromSeconds(5)))
            {
                try
                {
                    var tmp = _db.StringGet(key);
                    var data = 0;
                    int.TryParse(tmp, out data);
                    _db.StringSet(key, data + 1, TimeSpan.FromSeconds(5));
                    flag = true;
                }
                catch (Exception)
                {
                    //var a = ex.Message + "\r\n" + ex.StackTrace;
                    var b = string.Empty;
                }
                finally
                {
                    _db.LockRelease("LockKey", Token);
                }
            }
```

At code ' _db.LockRelease("LockKey", Token); '
StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2258
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisTransaction.Execute(CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisTransaction.cs:line 53
   at StackExchange.Redis.RedisDatabase.LockRelease(RedisKey key, RedisValue value, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1090
   at RedisLock.Program.StringLockToUpdate(String key) in E:\Codes\CharlesDemo\RedisLock\Program.cs:line 135
   at RedisLock.Program.<>c.<Main>b__3_1(Object index) in E:\Codes\CharlesDemo\RedisLock\Program.cs:line 56
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by weisenzcharles** [comment]
Redis Version:4.0.11

**Comment by mgravell** [comment]
is it possible to run a `redis-cli monitor` while doing this, so we can see what actually got issued? for example, after the initial handshake, I get:

``` txt
1583232178.306892 [0 127.0.0.1:63202] "SET" "LockKey" "Whatever" "EX" "5" "NX"
```

(which is the `LockTake`),

``` txt
1583232178.308353 [0 127.0.0.1:63202] "GET" "mykey"
1583232178.309335 [0 127.0.0.1:63202] "SETEX" "mykey" "5" "1"
```

(which is the work inside the lock), and

``` txt
1583232178.315955 [0 127.0.0.1:63202] "WATCH" "LockKey"
1583232178.315962 [0 127.0.0.1:63202] "GET" "LockKey"
1583232178.318457 [0 127.0.0.1:63202] "MULTI"
1583232178.318464 [0 127.0.0.1:63202] "UNLINK" "LockKey"
1583232178.318469 [0 127.0.0.1:63202] "EXEC"
```

(which is the value-checked unlock)

from the C# code:

``` c#
using StackExchange.Redis;
using System;

static class P
{
    static void Main()
    {
        const string Token = "Whatever";
        using var conn = ConnectionMultiplexer.Connect("127.0.0.1:6379");
        var db = conn.GetDatabase();
        RedisKey key = "mykey";
        bool flag = false;
        if (db.LockTake("LockKey", Token, TimeSpan.FromSeconds(5)))
        {
            try
            {
                var tmp = db.StringGet(key);
                var data = 0;
                int.TryParse(tmp, out data);
                db.StringSet(key, data + 1, TimeSpan.FromSeconds(5));
                flag = true;
            }
            catch (Exception)
            {
                //var a = ex.Message + "\r\n" + ex.StackTrace;
                var b = string.Empty;
            }
            finally
            {
                db.LockRelease("LockKey", Token);
            }
        }
        Console.WriteLine(flag);
    }
}
```

which all looks about right to me; I'm curious as to what is happening in your case!

**Comment by mgravell** [comment]
in particular, I notice that the only thing issued inside the `MULTI`/`EXEC` is the `UNLINK`, and `UNLINK` is a >=4.0.0 command; you mention that you're using 4.0.11, so this feels correct; one other thing you could try, though, is disabling `UNLINK`; if I change my connection string slightly:

``` c#
using var conn = ConnectionMultiplexer.Connect("127.0.0.1:6379,$UNLINK=");
```

I now get, for the value-checked unlock:

``` txt
1583232503.516815 [0 127.0.0.1:63227] "WATCH" "LockKey"
1583232503.516822 [0 127.0.0.1:63227] "GET" "LockKey"
1583232503.519470 [0 127.0.0.1:63227] "MULTI"
1583232503.519478 [0 127.0.0.1:63227] "DEL" "LockKey"
1583232503.519483 [0 127.0.0.1:63227] "EXEC"
```

which might fix things *if the problem is that your server inexplicably doesn't support `UNLOCK`*

**Comment by weisenzcharles** [comment]
OK, the reason is that `UNLINK` is not disabled.
thank you!

**Comment by mgravell** [comment]
@weisenzcharles hmmm; this is curious to me, because it suggests one of a few options:

1. your server is deliberately configured to disable or rename the `UNLINK` command
2. you're using a "redis-like" server (not actually redis) that isn't quite following the expected rules (this could include a redis protocol proxy between you and the real server)
3. the redis.io docs are incorrect, and it isn't actually a 4.0.0 feature, but a 4.something.higher feature

Can you spare a moment to help me figure out which of these applies? If it is "1", then that's fine - we have a solution. If it is "2", I'd love to know "what server?", because we might be able to auto-detect it to prevent other people hitting this problem; if it is actually "3", I can try and get the documentation fixed.

**Comment by mgravell** [comment]
(btw; if it is "1" and you know what the renamed command is, you can use `$UNLINK=REALLYUNLINK` for example to let the library understand what is happening)
