### ISSUE TITLE
RedisTimeoutException not related to IOCP or WORKER threads

### ISSUE THREAD

**Issue by alexleech** [StackExchange/StackExchange.Redis#1378]
I've encountered a bunch of `RedisTimeoutException` when using Azure redis cache service. Though it only happened for around 5 minutes when under 12 hours of stress test, it's still problematic. Searching the issues threads but most conclusions are related to adjust the minimum threads and seems like that's not my case. Here's a sample error message:

Error locking lock instance xxxx.redis.cache.windows.net:6380 (master), xxx.117.211.105:15002 (master), xxx.117.211.105:15000 (master), xxx.117.211.105:15003 (slave), xxx.117.211.105:15001 (slave): Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5700ms elapsed, timeout is 5000ms), command=SET, next: EVAL, inst: 0, qu: 0, qs: 38, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: xxx.117.211.105:15002, mgr: 10 of 10 available, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=3,Free=32764,Min=16,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by dceravigupta** [comment]
@alexleech if you are working with Redis, you should design your application such that it can handle connection blips. There are number of reasons due to which it can happen like failover, redis patching etc.

It also mentioned as one of the guideline on Azure Redis Best practices page.
![image](https://user-images.githubusercontent.com/32182026/76677040-a5ce3880-6586-11ea-97ff-b07801d6aae2.png)

https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-best-practices

Also, what is your cached objects size as that can be another reason for increase in RedisTimeouts? Redis is designed for small objects (<10KB) and if you are caching large objects, under stress it might result in increase in timeouts.

**Comment by NickCraver** [comment]
The advice above is correct - we've also made some reconnect improvements in 2.2.50 which should reconnect faster than before, reducing the window of impact. We're also working with Microsoft to get a pub/sub message from Azure's infrastructure when a failover is about to happen and completed to make it even more instant and a very narrow window. No timeline yet, but that's on the list after the next few improvements.
