### ISSUE TITLE
Timeout Exceptions in StackExchange.Redis v2.1.30

### ISSUE THREAD

**Issue by jananiva** [StackExchange/StackExchange.Redis#1469]
We recently switched to v2.1.30 from v1.* and we have started seeing a lot of timeout exceptions. We only use REDIS async APIs. We use the following overrides `ssl=True,abortConnect=false,asyncTimeout=2000`

When a machine is hit by timeout, it continues to throw timeout exceptions for 10-15 mins, traffic on that machine reduces (since Load balancer realizes that the health of the machine is not good) and after a point, the timeout exceptions stop.

There are 3 flavors of error message being thrown when this happens.
### Error message 1:
`Timeout awaiting response (outbound=0KiB, inbound=0KiB, 4016ms elapsed, timeout is 2000ms), command=GET, next: SELECT, inst: 0, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: foobar.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: fobarbar, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=39,Free=32728,Min=4,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

### Error message 2:

`The timeout was reached before the message could be written to the output buffer, and it was not sent, command=SETEX, timeout: 5000, outbound: 6KiB, inbound: 4KiB, next: UNWATCH, inst: 3, qu: 10, qs: 3, aw: True, bw: WritingMessage, rs: ReadAsync, ws: Flushed, in: 0, serverEndpoint: foobar.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 9 of 10 available, clientName: fobarbar, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=219,Free=32548,Min=4,Max=32767), v: 2.1.30.38891 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

### Error message 3: 

`One or more errors occurred.`

We reuse connections (have one connection multiplexer instance per REDIS connection string). What could we be doing incorrectly here and how to fix this?

**Comment by jananiva** [comment]
Few more details:

- The rate of calls to the REDIS instance and the size of data being read/written did not change significantly before/after the exception period.
- The latency of REDIS calls shot up all of a sudden exactly when the exception started and ended with the exception period. Please see screenshot attached (Y axis in ms, X axis interval is 1m). 


![image](https://user-images.githubusercontent.com/30429097/82620472-62e39f00-9b8d-11ea-951a-024fec7034ef.png)


- There were very few calls to REDIS during the exception period. Until then, there were steady number of GET, SET and DEL calls to REDIS. Check the timerange in both the screenshots.
![image](https://user-images.githubusercontent.com/30429097/82620401-3891e180-9b8d-11ea-841b-e66e20ac823f.png)

**Comment by anandan84** [comment]
I am facing same issue.

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=8KiB, inbound=0KiB, 1594ms elapsed, timeout is 1000ms), command=GET,

**Comment by richardimms** [comment]
I'm also facing a similar issue, we've noticed that another team are using an earlier version of the package (2.0.601) and aren't facing this issue. Will try and downgrade the version soon and see if it resolves our issue.

**Comment by jananiva** [comment]
@mgravell @NickCraver Can you please take a look at this? We are repeatedly hitting this in v2.1.3

**Comment by NickCraver** [comment]
A large difference for most people is we _actually_ enforce the timeouts in v2. The SLA for redis especially in cloud environments is...undefined. There's no guarantee.  In this thread I am seeing:
1. `Busy=219,Free=32548,Min=4,Max=32767`

This indicates a *very* busy server, running 219 threads. That's far more loaded than Stack Overflow, for example. How many cores does the machine have? Unless it's massive, things are going to start piling up and waiting...and timeout. Either the timeout needs to be higher, or the work further spaced out. It's too much work with too few resources. That latency graph is showing _completion_ times...and commands can only be completed when they have CPU resources to do so.

2. `1594ms elapsed, timeout is 1000ms`

To be frank, that's a very low timeout. Even in our environment for Stack Overflow, that's tightly controlled with 0.016ms of network latency we *still* have a 2,000ms timeout. There are latency spikes on an entire network for a variety of reasons, 1,000ms as a *maximum* threshold is generally too low even in a LAN, much less a cloud environment if that's your case.

3. New timeouts in 2.x.

Again, this is likely due to unenforced timeouts and latency spikes not seen vs. actual enforcement. Do you have any telemetry from the previous versions to show if command latency actually shifted, or is it only the timeout bar/enforcement that changed?

I believe this enforcement and unclear expectations of what to expect, especially in hosted redis caches is contributing a great deal to the timeout reports we're getting. Any data you can share there is helpful.

**Comment by NickCraver** [comment]
Without more info here - closing this out to cleanup.
