### ISSUE TITLE
IP address binding

### ISSUE THREAD

**Issue by jbayardo** [StackExchange/StackExchange.Redis#1472]
We need to bind to a specific IP address when creating a connection to our Redis instance. Not doing so means that Redis.StackExchange's behavior is dependant on something else (i.e. OS behavior); in our case, we seem to be picking which IP to connect from _mostly_ at random, which means that sometimes we won't be able to connect due to picking an interface without internet connectivity.

As far as I can tell, there is no option to bind to a specific address in the ConnectionMultiplexer's options.

**Comment by NickCraver** [comment]
Correct that we don't expose this today, but as an SRE: I'm also not sure how this happens. Are you using 2 internet-routable interfaces on the machine though one of them isn't? All major OSes should be making a correct, routable, choice here when selecting the socket (that's why we let the OS handle it...as most everyone does). Can you elaborate a bit on how this is occurring?

**Comment by jbayardo** [comment]
The scenario is as follows:
- We run on VMs that we don't fully control
- These VMs are also running Hyper-V inside (i.e. VMs within VMs), and are located inside a datacenter
- To clarify, we run in the middle VM layer (i.e. not the "inception")
- There are two network interfaces:
  - Internet facing
  - Hyper-V (VM network, no internet connectivity)
- For currently unknown reasons, the Hyper-V interface may preferred by the OS sometimes (but not always)

This leads to machines attempting to connect to Redis via the Hyper-V interface, which fails as expected. We are currently working on fixing this, but resolution is likely to take some time, so we hoped to forcefully bind the IP with internet connectivity.

**Comment by jaamison** [comment]
I'd like to see this as well. We have VM hosts that are doing some complex routing, and being able to pick the local interface an outbound connection originates from is how we segment high priority application traffic from management/logging traffic.

Sure, all the interfaces are internet-routable, but some run through different VLANs, over different media, etc. For example, I could have a plain 1gb ethernet interface alongside a 100gb infiniband link.

Other situations this might be helpful (or even necessary):

- VRF where source address determines routing behavior
- traffic shaping / bandwidth monitoring at the application level
- multiple application instances on the same machine that need to be identified separately

Any reason not to add a `LocalInterface` option to ConfigurationOptions and pass it through to the underlying Sockets?

**Comment by jaamison** [comment]
Should have mentioned - I'm happy to submit a PR if this would be of interest.

**Comment by NickCraver** [comment]
I'm revisiting options here and I know it's been a while - could y'all elaborate on if this is still a needed thing, or were you able to solve it in config? I still hesitate to add something like this, and I wouldn't as-is, but if this is still a problem today then in the options work I'd propose a much more general "OnBeforeConnect" or something that takes an `Action<Socket>`, so rather than adding a contract of options, you could more generally modify the socket between creation and connection.

Everything we add has a cost though (even in user confusion), so I wanted to check in if this is still a pain point. Apologies it takes a while to get to the rarer cases, this is still a spare time thing for the vast majority of the work.

**Comment by NickCraver** [comment]
This scenario should be enabled by #2031 

/cc @TimLovellSmith re: socket linger, same config path!
