### ISSUE TITLE
Question about PreventThreadTheft

### ISSUE THREAD

**Issue by sungam3r** [StackExchange/StackExchange.Redis#1473]
I read the [documentation](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/ThreadTheft.md) and in fact I understand what `PreventThreadTheft` does and why. I myself have repeatedly encountered such a problem. The only thing I don’t understand is this line of code - https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/ResultBox.cs#L146. My question may seem silly - shouldn't this condition be inverted to that
```c#
ConnectionMultiplexer.PreventThreadTheft ? TaskCreationOptions.RunContinuationsAsynchronously : TaskCreationOptions.None; 
```
?

**Comment by mgravell** [comment]
This is a very perceptive question, and I understand what you mean - but: this code needs to be read alongside the other code here. Specifically, we check this flag in another place - [here](https://github.com/StackExchange/StackExchange.Redis/blob/8c36d5b8c600aca0ff5e973f4690ed33f8a0cdab/src/StackExchange.Redis/ResultBox.cs#L115) - and perform the invoke differently depending on what this flag is. It won't have shown in a search because we check the *task*, not the feature flag.

Make sense?

**Comment by sungam3r** [comment]
I re-read the documentation again and now I understand. Thanks.
