### ISSUE TITLE
Could ScriptEvaluate support IReadOnlyList<T> instead of T[]?

### ISSUE THREAD

**Issue by AdamOutcalt** [StackExchange/StackExchange.Redis#1495]
ScriptEvaluate takes RedisKey[], but I haven't found any usage inside StackExchange.Redis that actually needs it to be an array. Could it take IReadOnlyList<RedisKey> instead?

I have a scenario where I want to run ScriptEvaluate on many keys. I use Linq to get batches of size N, to keep the duration of a command reasonable.

To invoke ScriptEvaluate with RedisKey[], I have to call List.ToArray, which is an extra allocation. I'm doing this many times, so it would be ideal to be able to skip this.

**Comment by mgravell** [comment]
I'm certainly open to it; I did some work a while back around "how would we write the API if we were writing it today" - it had a lot of changes, including thoughts in this area (and others).

I'm slightly in doubt over `IReadOnlyList<T>` vs `ReadOnlyMemory<T>`, but maybe the former is more familiar with most people.

Let me think.

**Comment by AdamOutcalt** [comment]
Thanks. Happy to provide motivational samples if it's useful.

I suggest IReadOnlyList<T> only because I know it's not a breaking change from T[]. I don't know much about ReadOnlyMemory<T>.

**Comment by mgravell** [comment]
*changing* the API from `T[]` to `IReadOnlyList<T>` is absolutely a breaking change, so we'd be adding this as an overload. One minor nuance is that it can still be *code* breaking to add as an overload, because someone could be using the `null` literal as an argument, and if we do that: the compiler won't be able to pick a preferred overload. So it is always slightly non-trivial. I'll have a think about it!

**Comment by NickCraver** [comment]
Given this hasn't been requested again, is an efficiency-only change, and it is breaking going to close this out as "won't change" given all the factors.
