### ISSUE TITLE
RedisConnectionException: 'No connection is available to service this operation' after upgrading to .net core 3.1.5

### ISSUE THREAD

**Issue by RiskXs** [StackExchange/StackExchange.Redis#1500]
Hi,

I'm using Redis in my project and everything worked fine but after I upgraded my environment to .net core 3.1.5 an RedisConnectionException is thrown with a message 'No connection is available to service this operation'

downgrading back to 3.1.3 solves the problem. What can it be?

**Comment by mgravell** [comment]
Interesting! I will have to investigate this as a priority, as obviously
this isn't good, but my first guess would be "TLS level" - any chance
you're running against a TLS redis instance, and not specifying the TLS
version explicitly?

**Comment by RiskXs** [comment]
Hi @mgravell thank you for your answer.
We are using SSL but I remind you that nothing changed configuration wise. The only thing that was changed is the .net runtime.

**Comment by RiskXs** [comment]
BTW @mgravell 
If you go to C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.5 and delete a file named ".version" it works fine.

**Comment by mgravell** [comment]
Yes, I realise you are using the same config, but *something* is obviously
different, and I know that TLS default versions have been changing a lot
recently, hence why I'm saying it is worth trying. My aim here is to solve
things as quickly as possible, so I'm saying: it is worth trying checking
what TLS version your redis server is using, and specifying that version
explicitly on the config string. If this fixes it, great: we can look into
options for making this not be a problem. If this doesn't fix it: we'll try
to repro and see what the underlying problem is.

**Comment by mgravell** [comment]
Sadly, deleting random files from the runtime folder isn't advice I'm going
to give out, even if it does resolve it :)

**Comment by RiskXs** [comment]
@mgravell 
It’s not exactly random but if it doesn’t ring a bell never mind.
I’ll try what you suggested on Sunday and will update. Thanks.

**Comment by mgravell** [comment]
Did you get any joy with this? And just for confirmation: this is SDK 3.1.301, yes?

**Comment by mgravell** [comment]
azure is working fine for me on the latest runtime and SDK:

![image](https://user-images.githubusercontent.com/17328/85023708-03b58200-b16d-11ea-8b92-f1cda3931c8f.png)

**Comment by thelgevold** [comment]
@mgravell I am seeing this issue as well. Interestingly enough the issue comes and goes in my case. I am running my redis cluster in K8 (azure). One primary with 2 secondary replication nodes.

I can go 30 minutes without seeing it, but then it happens at random and recovers on its own.

Code sample below:

Version 2.1.30 of StackExchange.Redis
.Net Core 3.1

Relevant code:

```

            var configurationOptions = new ConfigurationOptions
            {
                EndPoints = { host },
                Password = password,
                KeepAlive = 10,
                ConfigCheckSeconds = 0,
                CommandMap = CommandMap.Create(new HashSet<string>
                {
                    "CLUSTER"
                }, available: false)
            };
           
            connectionMultiplexer = ConnectionMultiplexer.Connect(configurationOptions);
           

            await connectionMultiplexer.GetDatabase().StringSetAsync("some-key", "some-value", lockTimeout, When.NotExists);
```

Error details:

StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: SET [some-key], mc: 1/1/0, mgr: 10 of 10 available, clientName: my-service, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767), v: 2.1.30.38891

**Comment by ejsmith** [comment]
I'm seeing this issue as well where it wasn't happening with older versions.

**Comment by thelgevold** [comment]
Update:
I have made two changes and it seems to have helped fix this issue on my end.

Changes:
1) Change connection to use a sentinel connection since my cluster is sentinel enabled
2) Upgrade StackExchange.Redis from v2.1.30 to v2.1.58

Still testing, but have not seen this error in 24 hours now. Before making these changes the error occurred very frequently.

**Comment by NickCraver** [comment]
This issue is probably ultimately related to the SDK fixes that we also gave feedback on to the .NET team, which has since been resolved in newer SDK installers. Will comment over on #1140 for other folks having issues :)
