### ISSUE TITLE
ZRANGEBYSCORE - double precision issue

### ISSUE THREAD

**Issue by dszryan** [StackExchange/StackExchange.Redis#1511]
not sure if this is my redis limitation or the c# API.

but i am losing resolution when calling the ZRANGEBYSCORE operation

value provided: scoreStart.ToString("N") = {string} "15,875,259,493,311,844,**352**.000"
value sent to redis (seen in monitor): "ZRANGEBYSCORE" "KEY" "1.5875259493311844E+19" "+inf" "LIMIT" "0" "100"

losing the last three digits in the resolution.

**Comment by mgravell** [comment]
The general accuracy of an IEEE754 double-precision value is understood to be [approximately 15-17 digits](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types); in this case it looks like you're effectively seeing 17 (which means you're doing well - this was not guaranteed), and hoping for 20. If the `"N"` format is managing to get back the exact value, then that's doing *extremely* well, but I worry that you're asking too much from `double`, and even if we "fixed" this by detecting some scenarios where `"N"` worked better than `"G17"`, it still wouldn't give you exactly what you want, because there would be a lot of cases where `double` *simply can't hold the value you're expecting it to hold*, because it can't be represented in floating point.

Rephrasing: double-precision numbers *are not precise* - in particular at the extreme ends, but even some numbers that look intuitively "easy" to represent (like 0.1 or 0.3) end up being approximated internally to something that *isn't quite that*.

**Comment by mgravell** [comment]
A number of the related APIs here assume double for the score. We can perhaps look at offering `long` instead (additional), but it is more than just this one API that would need to be considered. Before doing such, I should double-check what Redis allows internally. I'm *presuming* from the fact that you're asking the question that Redis differentiates here and works correctly with these values.

**Comment by dszryan** [comment]
the issue was PEBKAC

to explain, the code was using all 63bits of the double to represent a long value, which made it the numeric larger than the max long value ([9007199254740992](https://redis.io/commands/zadd))

as long as the numeric is kept below the said value, everything works fine.
