### ISSUE TITLE
Cluster slot change may lead to EXECABORT errors, app restart fixes issue

### ISSUE THREAD

**Issue by Plasma** [StackExchange/StackExchange.Redis#1520]
Hey,

Using SE.Redis v2.1.0.

We added a new shard to our redis cluster, and mostly things were uneventful, except for our backend worker machines receiving `EXECABORT Transaction discarded because of previous errors` for a certain code path.

This code path uses transactions, and was working fine with 2 shards prior. After adding the 3rd shard, these errors seemed to be constant for a code path.

A restart of our worker application immediately fixed the issue.

I'm thinking perhaps the transaction code did not detect/know to refresh the cluster slots map?

**Comment by nloyolag** [comment]
Hey Plasma

I'd like to bump this issue since I experienced the exact same problem recently. One theory that a colleague cooked up is that inside the transaction we are getting MOVED errors. Transactions will wrap this error as EXECABORT and the StackExchange.Redis client will therefore be unable to understand what to do. If it received the MOVED error plainly it would perhaps just point to the new shard, but I have not tested if this repros without transactions.

**Comment by NickCraver** [comment]
If this is still happening in the latest version, can you please post the full message on the errors you're seeing? This situation _should_ be handled appropriately in the latest version.

**Comment by hamish-omny** [comment]
I'll answer for Andrew. We are just about to upgrade to `2.2.88` and may need to add a shard next week so will try provide an update after that

**Comment by dusty9023** [comment]
@NickCraver, I wanted to add a little extra information as we're seeing this exact same problem on our side as well.

Notes: 
- We are using the latest version of the library - 2.5.43.
- We are using AWS' MemoryDB Service (Redis 6.2 Engine)

For our multiplexer we register the following for logging:
```
multiplexer.ErrorMessage += (sender, ev) => logger.Warn("ErrorMessage: " + ev.Message + " " + ev.EndPoint);
```

When resizing our shard, we start seeing the follow kinds of logs from the ErrorMessage event:
```
2022-03-31 21:41:59,262 [295] Level=WARN  ErrorMessage: EXECABORT Transaction discarded because of previous errors. Unspecified/<NODE>:6379
```


We then see a RedisServerException that is thrown from the `StackExchange.Redis.RedisTransaction.Execute`.
```
2022-03-31 21:41:59,263 [183]  ... Error: 
StackExchange.Redis.RedisServerException: EXECABORT Transaction discarded because of previous errors.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2836
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 53
   at StackExchange.Redis.RedisTransaction.Execute(CommandFlags flags) in /_/src/StackExchange.Redis/RedisTransaction.cs:line 50
...
(there is no inner exceptions)
```

**From what I can see, the first issue, is that the Transaction error for each of the operations are being swallowed, and not presented in the RedisServerException.**


Using the redis-cli and the `Monitor` command on one of the primary nodes, I waited for a transaction to fail on that specific node (watching our logs as mentioned above), and then attempted to repeat that same transaction manually on the node. 

This resulted in the following:
```
<NODE>:6379> multi
OK
<NODE>:6379(TX)> unlink {<KEY>}|doc
(error) MOVED 3659 <NEW_NODE>:6379
<NODE>:6379(TX)> unlink {<KEY>}size
(error) MOVED 3659 <NEW_NODE>:6379
<NODE>:6379(TX)> unlink {<KEY>}|hash
(error) MOVED 3659 <NEW_NODE>:6379
<NODE>:6379(TX)> unlink {<KEY>}|modified
(error) MOVED 3659 <NEW_NODE>:6379
<NODE>:6379(TX)> exec
(error) EXECABORT Transaction discarded because of previous errors.
```

As a note, we also had transactions using other commands, that failed for the same reason:
Example:
```
multi
hmset {KEY}|hash KEY HASH1 KEY1 HASH2
hmset {KEY}|size KEY 1 KEY2 2
exec
```

As a note, we have variety of other non transaction calls, including KeyDelete, KeyExists, ScriptEvaluate (LUA scripts), HashValues, HashGet, HashValues, etc that where all unaffected.

I haven't dug too deep into the code, but I'm assuming it's related to:
https://github.com/StackExchange/StackExchange.Redis/blob/4dccb0ab0c7abfbb64d1fbd8dd08a40668fe2285/src/StackExchange.Redis/ResultProcessor.cs#L206
AND
https://github.com/StackExchange/StackExchange.Redis/blob/4dccb0ab0c7abfbb64d1fbd8dd08a40668fe2285/src/StackExchange.Redis/RedisTransaction.cs#L441

If I understand this correct, the TransactionProcessor goes through the internal operations and calls ResultProcessor.ServerFail() on each operation. This then call  ResultProcessor.SetException():
```
var box = message?.ResultBox;
box?.SetException(ex);
```
Which I'm assuming is just constantly overriding the exception with the latest one.
https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/ResultBox.cs#L27

Then it calls:
base.SetResult(connection, message, result);

Which ends up at at the logic that potentially trigger the resend on the other endpoint:
https://github.com/StackExchange/StackExchange.Redis/blob/4dccb0ab0c7abfbb64d1fbd8dd08a40668fe2285/src/StackExchange.Redis/ResultProcessor.cs#L206

Which instead of being "(error) MOVED ...", it's "(error) EXECABORT Transaction discarded because of previous errors.".

Then finally, the exception is finally override once last time in this method with "(error) EXECABORT Transaction discarded because of previous errors." using ServerFail().
https://github.com/StackExchange/StackExchange.Redis/blob/4dccb0ab0c7abfbb64d1fbd8dd08a40668fe2285/src/StackExchange.Redis/ResultProcessor.cs#L263

Note:
- I have not verified this by running it locally.

**Comment by mgravell** [comment]
Very interesting. It looks like we're not correctly handling that flavor of error, i.e. where the error is eager rather than queued. Fortunately, I believe we can probably simulate and investigate this more using incorrect argument counts, which I believe acts similarly.
