### ISSUE TITLE
Does stack exchange 1.2.4 support aws elasticache redis ?

### ISSUE THREAD

**Issue by AakashArasu-Dev** [StackExchange/StackExchange.Redis#1543]
From my EC2 instance, I am able to do redis-cli -h xxxx -p 6379 and it works. But in the same ec2 instance i have my code deployed, with stack exchange redis 1.2.4 version, But the app cannot connect with the aws elasticache, my connection string looks like this - "xxxx:6379,abortConnect=false"

I am getting error :

No connection is available to service this operation, InternalFailure on xxxx:6379/interactive origin: EndReading, input-buffer: 826, outstanding: 1, last-read: 0s ago, last-write: 0s ago, unanswered-write: 1386721s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablishing, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago Value cannot be null.

Is this because of older version of stack exchange redis ?

**Comment by mgravell** [comment]
There is no specific limitation that I can think of that would prevent this
working in 1.2.4, but without being able to see it happen it is hard to
speculate, and I'm not keen to try and offer support on a very old version.

Things I would try first:

- use an IP instead of a host name
- check whether TLS is enabled, and if so: enable it in the configuration
string (although the fact that you can use redis-cli suggests not)
- (and check the TLS version)

**Comment by NickCraver** [comment]
Closing this out to tidy up!
