### ISSUE TITLE
System.ObjectDisposedException: 'The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.'

### ISSUE THREAD

**Issue by anilsahda** [StackExchange/StackExchange.Redis#1554]
Hi,
I'm using Redis in my project which is in .net framework 4.5 and getting 
exception : System.ObjectDisposedException: 'The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.'
while try to use StringSet to add data in cache.

Thanks

**Comment by NickCraver** [comment]
Can you provide the full stack trace please? And which version of the library you are using?

**Comment by rakker91** [comment]
Anilsahda,

We had a similar problem and found that it was because of autoscaling in k8s and calling close on the redis client prior to stopping a message pump from Kafka, which resulted in closing the connection on one thread while trying to use the connection on another.

You might want to see if you have something similar going on.

See https://github.com/StackExchange/StackExchange.Redis/issues/1579 for more details.
