### ISSUE TITLE
Does StackExchange.Redis work in WINE on Linux?

### ISSUE THREAD

**Issue by sdai2020** [StackExchange/StackExchange.Redis#1618]
I have a C# application which uses StackExchange.Redis to publish messages to and receives messages from Redis server. It works fine on Windows 10 environment. But it does not work on Linux VM (CentOS 7) with WINE 3.0.3. It failed with a program error and the output contained the following error message:
0084:fixme:shell:URL_ParseUrl failed to parse L"StackExchange.Redis"

And it also threw an unhandled exception - Could not load file or assembly 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' or one of its dependencies.
I upgraded WINE from 3.0.3 to 5.0.3 and the issue was not fixed. 

Does StackExchange.Redis work in WINE on Linux? How can I install StackExchange.Redis package in WINE?

**Comment by mgravell** [comment]
Quite honestly: I have no idea. Since .NET Core works just fine in Linux, most Linux users: just use that.

The library is just a standard .NET library. Any problems are likely to be WINE specific, and I make no attempt to present myself as a WINE expert (except in the🍷 sense).

If there are specific issues that can be addressed via code changes: I look forward to the PRs.

**Comment by bklooste** [comment]
"Could not load file or assembly 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' or one of its dependencies."

Would indicate it has more to do with  .NET support under WINE rather than stackexchange and the version installed/used/supported.   With the move to core there are a lot of binding issues like this  eg 4.6 Net.http shenanigans and .netstandard 2.1 does not even support .net anymore ( only Core and .NET 5 which is really Core 4)  .

Try install a recent ..net framework under WINE  if that is possible.

**Comment by mgravell** [comment]
> and .netstandard 2.1 does not even support .net anymore

> Minor nit: you mean ".NET Framework" here, which is the Windows-specific legacy platform, and it is more that .NET Framework does not - and will never - support .NET Standard 2.1, rather than the other way around

**Comment by sdai2020** [comment]
It works with Wine 5.0.3 now after all needed DLLs were copied into Linux VM. Thanks for all responses.
