### ISSUE TITLE
Question: where to find information on the driver compatibility with Redis?

### ISSUE THREAD

**Issue by maximvsidorenko** [StackExchange/StackExchange.Redis#1629]
We use StackExchange.Redis in our product, and we'd like to know where to find information on the driver compatibility with Redis.

For example, below are versions of StackExchange.Redis we are using in different versions of our product:

|StackExchange.Redis|Redis supported |
|---                             |---                      |
|1.0.488                      | ?                        |
|1.2.6                          | ?                        |
|2.0.519                      | ?                        |
|2.1.58                        | ?                        |

Could you please help with this?

**Comment by mgravell** [comment]
This is an impossible matrix to complete, because *in general* the answer is "all of them". The fundamental RESP protocol hasn't changed (if we ignore RESP3 for the moment), so *as long as* you aren't using new features, it'll just work.

If you're using ACL sign-in with redis 6, that will need a more recent version, as the auth mechanism changed. Other than that, you should be fine. For individual features and specific commands, you'd need to check the release notes.
