### ISSUE TITLE
Higer CPU usage for redis cluster than redis instance

### ISSUE THREAD

**Issue by limeng05** [StackExchange/StackExchange.Redis#1658]
We migrated our redis server to redis cluster, and using the SDK version is 2.2.4 from nuget. Seems currently the CPU usage is 30% more higher than before, is it normal?

**Comment by NickCraver** [comment]
Are we talking about CPU on the cluster or CPU on the client?

**Comment by limeng05** [comment]
> Are we talking about CPU on the cluster or CPU on the client?

CPU on the client

**Comment by Dao007forever** [comment]
We noticed the same for our client. The difference is we are on .Net framework and were using a mix of Sync and Async call. Switching all calls to Async reduce the contention (since it uses 1 backlog and 1 worker vs multiple requests trying to grab the lock.)

After that the CPU usage is still high ~20%, which I have not have time to dig into why.

**Comment by limeng05** [comment]
> We noticed the same for our client. The difference is we are on .Net framework and were using a mix of Sync and Async call. Switching all calls to Async reduce the contention (since it uses 1 backlog and 1 worker vs multiple requests trying to grab the lock.)
> 
> After that the CPU usage is still high ~20%, which I have not have time to dig into why.

Thanks for your information

**Comment by NickCraver** [comment]
@mgravell tagging because this may be the allocation issue on a miss we mentioned (wasn't sure where that is but happy to take a peek).

**Comment by NickCraver** [comment]
This was improved in #2110 (released in 2.6.45+), if you're still seeing issues after this please chime in but we believe this is corrected.
