### ISSUE TITLE
Getting an error 'The assembly for System.Runtime.CompilerServices.Unsafe could not be loaded' for v5.0.0

### ISSUE THREAD

**Issue by selvan-ramki** [StackExchange/StackExchange.Redis#1715]
In a .Net Framework 4.7.2 application, we are trying to migrate StackExchange Redis from 1.2.6 to 2.2.4. After upgradation we end with the below issue:

The assembly for System.Runtime.CompilerServices.Unsafe could not be loaded; this usually means a missing assembly binding redirect - try checking this, and adding any that are missing

The version of System.Runtime.CompilerServices.Unsafe is 5.0.0 and the assembly redirection uses the below:
![image](https://user-images.githubusercontent.com/5745819/112811832-16fd6280-909a-11eb-9cff-12db8a335efe.png)

Any help is appreciated...

**Comment by NickCraver** [comment]
The issue here is that you're using the NuGet package version (it appears), but a redirect works at the assembly level - so you'll want to see what version of assembly is in that package (I highly recommend https://github.com/NuGetPackageExplorer/NuGetPackageExplorer as a general tool here). More details in my post here: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by NickCraver** [comment]
Answered with info above, so closing this out :)

**Comment by ssg** [comment]
The info is very helpful, but the assembly version for 5.0.0.0 is 5.0.0.0 is though.
