### ISSUE TITLE
Config recommendation for performance

### ISSUE THREAD

**Issue by lalernehl** [StackExchange/StackExchange.Redis#1736]
Hi there,

Is there any config recommendation specially around Sockets? We have seen a performance degradation and perhaps this could be addressed with the proper configuration. Our main concern is CPU, it takes more than we expect.

How should we configure SocketUseThreadPool and SocketWorkerCount? Under what circumstances should we use the dedicated thread pool? How many workers is a good number and why? Any other setting we should be tweaking?

BTW, all these answers are missing from the documentation.

Thank you!

**Comment by NickCraver** [comment]
Do you have more information here? These aren't documented because almost no one should need to change them. What is it doing? What do you expect? Under what conditions does this occur? Loads vary in quite literally a million different ways, so saying what to do what isn't something we can document reasonably. What you're doing in a continuation 12 steps away matters.

The library is aimed at best performance as a default, if you're hitting some issue with the defaults, we need more information to suggest anything.
