### ISSUE TITLE
Create interface for ConnectionMultiplexer

### ISSUE THREAD

**Issue by nmehlei** [StackExchange/StackExchange.Redis#176]
This could help in creating unit tests for repositories or other data access layers because we could mock more easily.

**Comment by mgravell** [comment]
Not a terrible idea; there aren't *many* things on the multiplexer, and the database / server / etc are already interface-based, but yes, I can see the utility of this.

**Comment by PureKrome** [comment]
@mgravell would you accept a PR for this?

**Comment by RPM1984** [comment]
@mgravell i've already implemented a `IConnectionMultiplexer` class internally, so happy to PR this if you like.

**Comment by mgravell** [comment]
That would be good, yes please + thanks

On 2 July 2015 at 00:48, Ryan Miranda <notifications@github.com> wrote:

> @mgravell <https://github.com/mgravell> i've already implemented a
> IConnectionMultiplexer class internally, so happy to PR this if you like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/176#issuecomment-117854472>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
Completed via #231

**Comment by brutaldev** [comment]
Possible to return `IConnectionMultiplexer` in the `Connect* ` and `Create` methods? Cannot substitute these methods when third part libraries like [CacheManager use it internally](https://github.com/MichaCo/CacheManager/blob/3d6f8f40d77bf0b7a07d3966cb6545bff0127bd4/src/CacheManager.StackExchange.Redis/RedisConnectionManager.cs#L155). If these returned the interface then it's easy to substitute them with a mock object (since mocking `ConnectionMultiplexer` is not possible).
