### ISSUE TITLE
 Timeout performing GET (5000ms)

### ISSUE THREAD

**Issue by icejd** [StackExchange/StackExchange.Redis#1810]
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: GET cache_lp_sys_verifyfunsetting, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 192.168.0.123:5988, mc: 1/1/0, mgr: 10 of 10 available, clientName: GamePal_LP, IOCP: (Busy=0,Free=1000,Min=500,Max=1000), WORKER: (Busy=2,Free=32765,Min=500,Max=32767), v: 2.2.62.27853 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

**This timeout problem is so annoying that I added the following code to Application_Start() and it still occasionally occurs**

 System.Threading.ThreadPool.SetMinThreads(500, 500);

**Comment by SimonPapworth** [comment]
We suffers this - there is no fix and it is dam annoying. simply more than 5000 ms has passed since the request was made, and the SE client as timedout.

So if you are debugging and another thread or the current thread has made a redis request - then unless the request is serviced in 5 seconds Bang! - I can't debug in 4999ms intervals - I don't know about anybody else?

Or if you have front end IIS servers and the sever is busy then it often does not return back to the thread that made the Redis request in time and so Bang!

I hope this is fixed since we last checked in here 12 months ago - it is the most annoying time wasting issue we face (even worst that the sync async sync one).

It would be nice if on timeout a last attempt could be made, rather than the hard policy of bang!

We have a system that takes 60 seconds for the front end to warm up as it compiles the web pages, on swap over we get thousands of redis timeouts because the warmup keeps the CPU's busy and the SE client just jumps in and kills the request after 5 seconds.. To alleviate the problem in normal running  we run 50% extra Azure P1 web servers in the plan so that we don't get many items in the ISS worker processes, so we have less chance of threads not returning in 5000ms.  Async would solve some of these issues except for startup, which we are working on.

Of course a longer timeout would make the issue worst - because there are several redis server blips a day, and at least one failover per week, our users would be left hanging for the longer timeout, while whatever recovers. With hundreds of http requests per second generating thousands of Redis requests per second the longer timeout generates more support calls. And with hundreds of https requests stalling for longer it looks like a giant issue, the IIS servers reboot - did I mention we have a 60 second warm up?

Our fix is to go Async in .Net 5/6 - but that is a big task - and the SE client is only a small part of that reason.

**Comment by icejd** [comment]
All I can do now is use the other libraries

**Comment by alanjohn0915** [comment]
> All I can do now is use the other libraries

you have anything better to replace it?

**Comment by icejd** [comment]
> > All I can do now is use the other libraries
> 
> you have anything better to replace it?

https://github.com/2881099/FreeRedis/
This feels good
