### ISSUE TITLE
Publish not always received by Subscribers

### ISSUE THREAD

**Issue by Turnerj** [StackExchange/StackExchange.Redis#1827]
In [my caching library](https://github.com/TurnerSoftware/CacheTower) I use pub/sub to communicate cache evictions. This code works great locally on my Windows machine via Memurai (a Windows Redis-compatible server) but is flakey in CI.

I've created a MCVE for this following the core logic from my library here: https://github.com/Turnerj/RedisPubSubTest
The main test might look really strange but I'll explain it: https://github.com/Turnerj/RedisPubSubTest/blob/583528f58f80a6a4ee487de8d382f4cf4716d481/RedisPubSubTest/Program.cs#L29-L66

- The first "subscribe" is effectively what I do in my cache eviction extension - I do need to guarantee it is set so I don't use `FireAndForget` etc. The subscribe itself can't be `async` but the message received has to be (because in my library it calls something else that is `async`).
- The second "subscribe" replicates my actual test method in my library, it is there purely to see that a message is received to pass the test. The completion source is used to identify that the message was seen (more on that shortly).
- I call `PublishAsync` and this time it is `FireAndForget` - my library just needs the message sent, it doesn't need to wait to be sure. This code is on the hot path of my library.
- The completion source is used again and is compared to a 10-second task delay - whatever finishes first identifies whether it was successful.

The main thing here is I'm making the assumption that while I called `FireAndForget` on `PublishAsync` that it would still take less than 10 seconds to do it which seems reasonable to me.

Now that you hopefully understand the what and the why, I'm hoping you can help me figure out how to address it. I'm uncertain if its an issue with SE.Redis, an issue with Redis, an issue with CI or just an assumption I've made with how it all works together with my code.

Any help you can provide would be greatly appreciated!

**Comment by Turnerj** [comment]
Silly me didn't include some examples of the output via GitHub Actions when it succeeds/fails.

**Failed**
- Ubuntu: https://github.com/Turnerj/RedisPubSubTest/runs/3300657696?check_suite_focus=true
- Windows: https://github.com/Turnerj/RedisPubSubTest/runs/3300657740?check_suite_focus=true
- Mac: https://github.com/Turnerj/RedisPubSubTest/runs/3300657786?check_suite_focus=true

**Succeed**
- Windows: https://github.com/Turnerj/RedisPubSubTest/runs/3300999618?check_suite_focus=true#step:7:189
- Mac: https://github.com/Turnerj/RedisPubSubTest/runs/3300999656?check_suite_focus=true#step:7:189

**Comment by Turnerj** [comment]
I wonder if this relates to #1110 in at least it could be that its the subscriber-side of things not behaving rather than the publish side of things.

**Comment by Turnerj** [comment]
Hmmm, I removed the `FireAndForget` flag on the publish operation and it still happens just as fast - I think I'm making an assumption somewhere about the behaviour of the library or Redis but I really don't know what.

Failed run without `FireAndForget`: https://github.com/Turnerj/RedisPubSubTest/runs/3555873269
Code: https://github.com/Turnerj/RedisPubSubTest/blob/10c6085668017d68ca6b768d84789b2dd7de5524/RedisPubSubTest/Program.cs#L29-L65

**Comment by NickCraver** [comment]
I see this is in the context of a narrow time window - if you add a delay between the subscription and the publish, does it complete successfully every time? It is possible, depending on load, that a publish can beat a subscription to completion if run immediately after as is the case here (the library optimizes for overall massive load concurrency, rather than pub/sub order correctness). The reason for this approach is in almost all cases we've observed in the while, the pub/sub dependency for consumption is on _another_ server and not local (as in testing), so what is observed isn't different than time skew or speed of light issues between publishers and consumers. It's not to say it can't be made to be ordered, that's just the lock-light optimization path currently taken.

The way to test this would be a `await Task.Delay(2000);` before your publish, to establish it is a race that's happening. If we can do that, then it's easier to reason about some solutions...because it may _not_ be that, in which case: plot thickens!

**Comment by Turnerj** [comment]
You were spot on - the problem here was essentially a race condition between the publish and subscribe calls and your idea to simply put a delay before the publish works a charm in my example (tested it as low as 200ms and still good).

I agree with your reasoning too - this isn't exactly a normal case and it would be unlikely someone to hit this otherwise so the ordering typically doesn't matter.

I've been hitting this issue way longer than I've had this issue open so I'm extremely glad that this will make my tests be far more stable! I was pulling my hair out wondering how the logic wasn't working and whether I had a super subtle bug in my primary code base.

Thank you very much - you've made this developer's day!
