### ISSUE TITLE
Support ValueTask in IDatabaseAsync

### ISSUE THREAD

**Issue by korchak-aleksandr** [StackExchange/StackExchange.Redis#1855]
Hello @mgravell @NickCraver 

We have memory allocation issues in our highload microservice and the investigation via JetBrains DotTrace profiling shows that there is hign memory allocations in creation of `Task` instances. (in call stack there is `StackExchange.Redis`)
Almoust every call to our microservice create a request to `Redis` via `IDatabaseAsync`.

[ValueTask](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.valuetask-1?view=net-5.0) is a struct and it will help avoid memory allocations.

100% of our usages are:
1. Call redis (get/set etc) via await
2. Use the result

We would not touch on limitations of `ValueTask`.
You could fix this problem with no breaking changes for example with new `IDatabaseValueTaskAsync`

We are looking forward to your reply.
Thanks.

P.S.: There is related [issue](https://github.com/StackExchange/StackExchange.Redis/issues/1295), but it was closed due to inactivity

**Comment by mgravell** [comment]
ValueTask mainly avoids allocations *when the result is available synchronously*. When talking to redis: the result *will not be* available synchronously, so: this is nowhere near as clear cut as you seem to make out. There is a second usage of ValueTask using a more advanced API (IValueTaskSource), and this is *possible* to amortize allocations, but this usage is far from trivial. This kind of task usage is almost never a genuine allocation problem, as they are invariably collected pretty cheaply at gen-zero. I would be interested in any other findings you have, but: "let's use ValueTask" is not the instant win that you suggest.

**Comment by mgravell** [comment]
Also, to be clear: I'm a huge fan of ValueTask - see here: https://blog.marcgravell.com/2019/08/prefer-valuetask-to-task-always-and.html - and if we were creating the API from scratch, that would be an obvious thing to do; however, it is *not* automatically going to fix all the things here. I actually wonder if the task allocations in your case are *actually* mostly coming from your caller code; because even if you have`ValueTask` in your code, i.e.

``` c#
public async ValueTask DoTheThing()
{
    ... some code that uses await over SE.Redis
}
```

then : please be clear - you are allocating a`Task` each time; because (caveat: with a few exceptions) the `await` over SE.Redis is going to be an incomplete operation; the framework gives you back a `ValueTask` that is backed by a `Task` *that you can't see*. But it is there.

This then applies equally to every async part of your call chain; if you have 5 async methods A->B->C->D->E->(some underlying incomplete operation such as redis or ADO.NET) where A-E are all `ValueTask`, then *you still have 5 `Task`s in your code*a - plus whatever the incomplete operation itself used (1 in the case of SE-Redis)

Is this the possible real cause of your allocations? If so: note that `PooledAwait` might be of interest to you, as it targets exactly that situation - using an `IValueTaskSource` implementation instead. Note that .NET 5 also has some tricks available here, but they are also opt-in. I can dig out details if you like.

**Comment by Tornhoof** [comment]
In .NET 6 a lot of the capabilities around pooled (Value)Tasks changed (again) which makes pooling easier.
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#threading (below the Threadpool Part)

**Comment by mgravell** [comment]
Thanks @Tornhoof - that was what I was thinking of when I incorrectly cited .NET 5; to copy out the example:

``` c#
[AsyncMethodBuilder(typeof(PoolingAsyncValueTaskMethodBuilder))]
public static async ValueTask ExampleAsync() { }
```

I must find time to try tweaking PooledAwait to allow similar usage, just to see if there is still any advantage (very happy to just defer to the runtime folks, otherwise!) - couldn't do this before as the attribute could *only* be applied to types, not methods.

**Comment by korchak-aleksandr** [comment]
@mgravell Thank you very much for your answers. We will further investigate this problem.

**Comment by NickCraver** [comment]
Closing this out to cleanup - while `ValueTask` can make sense at the caching layer where the result is likely local, it doesn't at the client layer _where it's actually async_ - for anymore more curious, see Marc's comments above :)
