### ISSUE TITLE
Redis cluster looks like not distributing load in cluster way when using stackexchange.redis

### ISSUE THREAD

**Issue by KamranShahid** [StackExchange/StackExchange.Redis#1863]
I was testing my .net core 3.1 application which is using stackexchange.redis version 2.2.62.
First i haven't found any property from which i could flag it that this address i of cluster redis or not.
when testing with redis load looks like only to first node.
Theni use following code to first discover then again connect.

```
 private static readonly Lazy<ConnectionMultiplexer> Conn = new Lazy<ConnectionMultiplexer>(
            () =>
            {
                try
                {

                    if (ConfigOptions != null && ConfigOptions.Value != null)
                    {
                        var con = ConnectionMultiplexer.Connect(ConfigOptions.Value);
                        var connstring = string.Join(",", con.GetEndPoints(false).Select(ep => ep.ToString()));
                        if (connstring.Contains(","))
                        {
                            ConfigOptions.Value.EndPoints.RemoveAt(0);
                            List<string> endpoints = connstring.Split(',').ToList();
                            for (int i = 1; i < endpoints.Count; i++)
                            {
                                ConfigOptions.Value.EndPoints.Add(endpoints[i]);
                            }
                            con = ConnectionMultiplexer.Connect(ConfigOptions.Value);
                        }
                        //Logger.Info("Discovered Items:" + string.Join(",", con.GetEndPoints(false).Select(ep => ep.ToString())));
                        return con;
                    }
                    return null;

                }
                catch (Exception ex)
                {
                    Logger.Fatal(ex.Message, ex);
                    return null;
                }
            });
```
though this workaround would work but if i am adding or dropping some node within cluster then it seems to be not a good solution.
Please advice if there is any other good way

**Comment by mgravell** [comment]
When you say "first node" - do you mean in terms of shards, or replicas? If you mean shards: the designated shard-set is determined by the key chosen. Are your keys abnormally distributed? If you mean replicas: the optional command-flags parameter is important - by default, the primary is preferred.

**Comment by KamranShahid** [comment]
@mgravell which particular command flag you are referring

         None = 0,
        PreferMaster = 0,
        HighPriority = 1,
        FireAndForget = 2,
        DemandMaster = 4,
        PreferSlave = 8,
        PreferReplica = 8,
        DemandReplica = 12,
        DemandSlave = 12,
        NoRedirect = 64,
        NoScriptCache = 512

**Comment by KamranShahid** [comment]
@mgravell regarding key chosen there isn't any specific rule at the moment for key generation. we needed cluster recently as we seen too many timeout on very heavy load. i know the single threaded basic architecture of redis could be the bottleneck regarding that. So we went with redis cluster and able to remove timeout rleated thing when we have redis clusterwith three shardsand above logic to provide redis cluster endpoints information.
We are usign AWS Redis cluster

**Comment by mgravell** [comment]
k; let's try to reset and clarify; what **exactly** are you seeing, and how does this differ from what you *expect* to see?

There are two kinds of distribution; I think of it in terms of horizontal and vertical

Horizontal distribution (aka key sharding):
---

The way redis cluster works is: the cluster defines how the shards map to slots - the client library has absolutely no say in how things are distributed, so in terms of *shard* distribution: that's entirely out of our hands. If all your keys are going to one shard, then that's a key distribution problem - are you perhaps using "hash tags" in your keys? by which I mean: the keys `{foo}/bar` and `{foo}/blap` will both **always** go to the same shard, because when a `{something}` is present in a key, the slot is calculated *just* using the `something`.

Vertical distribution (aka replicas):
---

The other form of load distribution in redis is via replicas; if you *have* replicas enabled (which isn't a requirement), then it is possible to send some *read* operations to the replicas (*write* operations must be issued to the primary); however, because this may change semantics in terms of rapid "write then read" scenarios, we make this "opt in" in the library. Specifically, what I mean is that the default option when no suitable flag is specified via `CommandFlags` is `PreferPrimary` (it will use a replica only if no primary is available). If you want to distribute some of your read load to replicas, then you must specify `PreferReplica` or `DemandReplica` as part of the command flags on a command-by-command basis.

So: does the above explain what you are seeing? or are you seeing something else? If so: please be very specific, because I can't see your system from here :)

**Comment by KamranShahid** [comment]
Thanks @mgravell ,
My keys are simple string like MYXFuntionality_1235, MyZFunctionality e.t.c.
So looks like problem really lies at AWSsharding then to serve randomkeys to some db or may be we need to configure something there

**Comment by mgravell** [comment]
again, you haven't actually told me what you're seeing yet, so I can't really comment on that; perhaps start with : what symptom or behaviour makes you think there is a problem?

**Comment by NickCraver** [comment]
If we have more information, happy to re-open, but this appears to be a sharding/config problem (not client related) and a change would need to happen outside of the client area here.
