### ISSUE TITLE
Insert multiple keys with same date time expiration for all the keys

### ISSUE THREAD

**Issue by punitsinghi** [StackExchange/StackExchange.Redis#1869]
Hi,

I need to insert multiple keys with a expiry. Expiry is same for all the keys. As it is  a batch process  I see we can either use Creatbatch or CreateTransaction. We would like to maintain the order in the way keys inserted so looking at the definition, I think CreateTransaction will insert rows in order it receives. I can use StringSetAsync which supports expiration while HashSetAsync doesn't and it requires KeyExpiresAsync to set expiration value for a key.   Why HashSetAsync doesn't supports expiration? . I think If I use StringSetAsync than I have to use StringGetAsync in order to get value back from the key which is a slower operation than HashGetAsync.

**Comment by mgravell** [comment]
There's a lot to unpack here!

Right; let's start with what you want. Do you want to end up with three string values? Or one hash with three fields? Either is fine - we just need to know which. For expiration: note that absolute time is fine, not just relative time, so: if you're worried about picosecond drift between three keys: just use absolute time.

The reason hash-set doesn't support expiration is that redis does not support per-field expiration on hashes, which would be the logical assumption of what you're doing when setting individual fields on a hash.

String-get is not inherently faster or slower than hash-get. Can you clarify what you're referring to here?

Both the batch and transaction API preserve order; the main differences are that transactions support pre-conditions (which you don't need) and are execute on the server as a contiguous chunk (which you certainly can leverage here).

If this was me, I would do one of:

- create tran
- string set with absolute expiration, x3
- execute tran

Or

- create tran
- hash set multiple (with 3)
- key expire (absolute or relative, doesn't matter)
- execute tran

Note you could also use Lua (script evaluate) instead of the transaction API, with the note that the clock is essentially suspended within Lua.

**Comment by punitsinghi** [comment]
Thanks for such a detailed explanation. This helps.  

We need to store values and keys like below -

Key - [G:H2O][SG:LoanNumbers][Key:HL97031825691]
Value -  97031825691
Key - [G:H2O][SG:LoanNumbers][Key:HL97031825692]
Value -  97031825692

All of the keys have same expiration date. 

**String-get is not inherently faster or slower than hash-get. Can you clarify what you're referring to here?**
-- I am referring that when I use String Set operation to se the value of a key and later If I need to retrieve value, I need to use StringGet to get the data back from the key which I read somewhere that is a slower operation compare to If I have used HashSet to insert value and use HashGet to retrieve the value.

my understanding was that Transaction will roll back if any of the entries fails like a .NET transaction.

We don't have current scenario where we want to store Json object as a value into Redis but we may in future.  Will it matter if we use HashSet or StringSet in this case as well. 

Yeah I saw one Lua based on your response to another question on this forum and certainly can have a look. 

This is how I am trying to set If I use StringSetAsync-

         transaction.StringSetAsync(new RedisKey(key), 
                        new RedisValue(JsonConvert.SerializeObject(value)), expiration)

And using HashSetAsync

              transaction.HashSetAsync(key, new[] { new HashEntry(value.GetType().AssemblyQualifiedName, 
                                  JsonConvert.SerializeObject(value)) }).ConfigureAwait(false);
             transaction.KeyExpireAsync(key, exipration).ConfigureAwait(false);
       
I see that Keys is not a recommended operation specially in PROD envionment but II see pattern search is supported only through Keys. e.g If one has to fetch keys based on search criteria  like "[G:H2O][SG:LoanNumbers]" which would fetch both the keys, than I only see Keys is the way to go.

**Comment by mgravell** [comment]
> which I read somewhere that is a slower operation compare to If I have
used HashSet to insert value and use HashGet to retrieve the value.

I'm going to add a big dose of [citation-needed] here. There may be
contexts where it is relevant, in particular when talking about SCAN/KEYS,
but: not in general, no.

> my understanding was that Transaction will roll back if any of the
entries fails like a .NET transaction.

That's not quite how redis works, no.

**Comment by NickCraver** [comment]
Closing this out to cleanup!
