### ISSUE TITLE
Support redis server version

### ISSUE THREAD

**Issue by magicxiaoye** [StackExchange/StackExchange.Redis#1870]
Support redis version e.g. redis6.2.5 redis6.1.3, is there a document to identify StackExchange.Redis version adapts to redis version

**Comment by mgravell** [comment]
Yes, SE.Redis attempts to discover and utilize server-version specific features; however, *usually* this is minimal - i.e. it might prefer to use `SCAN` instead of `KEYS`, or a few other things; *usually*, a feature is going to simply work or not work depending on the connected server. Did you have a specific scenario in mind?

**Comment by NickCraver** [comment]
Answered above, so closing out to cleanup :)
