### ISSUE TITLE
StringSet does not accept expiration

### ISSUE THREAD

**Issue by smiket** [StackExchange/StackExchange.Redis#189]
IDatabase:StringSet has 2 overloads.  
One of the overloads takes an array of key/value.
This method also takes a When (condition) but does not take an expiration.  
Perhaps by design, but was curious if its just missing (I could use it if it was available).

**Comment by MichaCo** [comment]
It's most likely because Redis' [MSET](http://redis.io/commands/mset) doesn't support setting the expiration.

I guess you have to call EXPIRE on every key separated

**Comment by mgravell** [comment]
I'll check later, but I'm pretty sure this has optional parameters for the
expiry...

**Comment by mgravell** [comment]
If your question is about the dictionary overload: then indeed - we're
limited to what MSET and MSETNX expose, and these operations don't allow
timeouts to be specified. You could call StringSet multiple times, or you
could use KeyExpire.

**Comment by smiket** [comment]
Thanks for the quick response - yes, was in relation to the dictionary overload.  I will close the issue.  Really nice library, well written.

**Comment by iPilot** [comment]
Nothing changed on the redis side till now? I have a strange feelings using:
`Task.WhenAll(data.Select(d => StringSetAsync(d.Key, d,Value, expiration)));`
rather than
`StringSetAsync(data.Select(d => KeyValuePair.Create(d.Key, d.Value)).ToArray(), expiration);`
where there is one expiration time for all keys
