### ISSUE TITLE
Unsafe PulseAll() patterns in code

### ISSUE THREAD

**Issue by TimLovellSmith** [StackExchange/StackExchange.Redis#191]
This code in ResultBox exhibits a deadlock antipattern -

                lock (this)
                { // tell the waiting thread that we're done
                    Monitor.PulseAll(this);
                }

The reason: it has no guarantee that all threads who it expects to call Wait() on the result will not actually only call Wait() until AFTER the PulseAll() happens.

QueueDrainSyncLock also looks probably wrong.

            internal void Pulse()
            {
                lock (this)
                {
                    Monitor.PulseAll(this);
                }
            }

**Comment by mgravell** [comment]
Even if a wait happened after the pulse, that would not by itself create a
deadlock. I will review the corresponding wait code, but to the best of my
knowledge (prior to reviewing it), the code is sound. Do you have a
specific reason to suspect a wait-related issue here?

**Comment by mgravell** [comment]
On the topic of ResultBox, I will refer you to `ConnectionMultiplexer.ExecuteSyncImpl<T>`; what this does is:

- get a `ResultBox`
- lock it (the `ResultBox` is not externally available, and suffices as the sync-lock)
- push the message to the bridge
- perform a `Wait` with timeout (which releases the `Monitor` temporarily)
- if the `Wait` completed with success: obtain the result and recycle the box
- otherwise, throw a `TimeoutException` (do not recycle the box)

This **cannot** lead to an incorrect `PulseAll` timing, since the `Monitor` has the lock *before* it goes to the bridge, and thus the `PulseAll` can't get insode the `lock(this)` until the `Monitor.Wait` is invoked

On the topic  of  `QueueDrainSyncLock`: again, note  that the way this is used (see `ReadImpl`) means that the only thread that ever waits (the dedicated socket  thread) owns the lock at all times other than when  it is `Wait()`ing - unless of course it leaves the `lock(obj)`, at which point `obj` is out of scope and it *doesn't care*  if it misses a pulse: it no longer has an interest.

I do not believe the code you have cited does anything incorrect. Can you clarify your concerns?

**Comment by TimLovellSmith** [comment]
Your explanation makes sense.
I was missing that that the pulse/wait handoff is specific to a single message, which creates a stronger ordering constraint between events, and hadn't really looked at the way QueueDrainSyncLock is used.

**Comment by mgravell** [comment]
I appreciate the thoughts; threading is certainly hard to get right, and
virtually **any** technique / method will cause chaos if used
inappropriately - but I did try to put due thought into how the
synchronisation and messaging should work here :)
