### ISSUE TITLE
No connection is active/available to service this operation

### ISSUE THREAD

**Issue by natthavat28** [StackExchange/StackExchange.Redis#1925]
This happen when there are connection over 100+ but not 100% occur

`StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET conn_77_sZFLogqttv_A2rL6_7TpJA, mc: 1/1/0, mgr: 10 of 10 available, clientName: xxxxxxxxxxx, IOCP: (Busy=0,Free=1000,Min=20,Max=1000), WORKER: (Busy=208,Free=32559,Min=20,Max=32767), v: 2.2.88.56325`

**Comment by NickCraver** [comment]
In your case the connection died, likely due to starvation on the CPU being unable to keep up or the connection actually dropping. The 208 busy workers tells us this is a _very_ busy machine or there's some sync-over-async style locking happening in there. My best advice would be to get a snapshot when this happens to see what all those threads are busy doing.

In the 2.5x release we're working on in #1912, we should buffer and retry a bit when connections drop (for whatever reason), but I can't say that it'd solve your case with so much taxing the CPU when this happens - eg. if it can't keep up, then it can't keep up.

**Comment by NickCraver** [comment]
Closing this out to cleanup - main advice is above: CPU load/threading is the issue and while some changes we making may help _slightly_, it would only buffer the problem out a bit more on a starved CPU, the root overload cause there (or provisioning more resources) is needed to really address it).
