### ISSUE TITLE
ERR invalid expire time in psetex

### ISSUE THREAD

**Issue by Shad107** [StackExchange/StackExchange.Redis#2045]
from time to time have error StackExchange.Redis.RedisServerException width ERR invalid expire time in psetex.
I use a version 2.5.43 on netStandard 2.0 on redis server 6.2.6, after restart IIS service no error....

**Comment by NickCraver** [comment]
What was the error? Please always post the error message when filing an issue anywhere - the devs created them to help you debug :)

**Comment by Shad107** [comment]
Hello error message is 'ERR invalid expire time in psetex', log trace:

 à StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   à StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)

**Comment by NickCraver** [comment]
This is like pulling teeth, please post the entire error message, not part of the trace.

It looks like you're calling the method with an invalid expiry argument, but actual details would help.

**Comment by Shad107** [comment]
I have not other message, I not example of data at this time

**Comment by NickCraver** [comment]
The best advice I have is look for the caller that's calling this set, it appears to be sending an invalid expiration value to the server, but I don't know the range offhand. My guess is it's passing 0.

**Comment by Shad107** [comment]
I added a log for more details, I'll get back to you as soon as I have news

**Comment by slorello89** [comment]
@Shad107, that error is a RedisServer error, you are either passing in a negative value or a value that's slightly overflown a 64-bit signed integer to the `PSETEX` command. My money's on Negative because I don't think Timespans can be constructed from integers large enough to overflow.

**Comment by NickCraver** [comment]
@Shad107 any luck here?

**Comment by NickCraver** [comment]
@gdoron I'm not sure what that is but...doesn't appear to be our library?

**Comment by gdoron** [comment]
We are using [Foundatio](https://github.com/FoundatioFx/Foundatio#caching) (an amazing library BTW if you are not familiar, I highly recommend checking it) on top of redis stack exchange.

**Comment by mgravell** [comment]
It is still very hard for us to comment without knowing what's actually going through our library. What value did you supply as `expirationTime`? in particular, is there any chance it is zero, negative, or very very large? that error comes from the server [here](https://github.com/redis/redis/blob/155acef51ac7826ed294a4b61d891f1c7a9a40ac/src/networking.c#L653), I *think* from [this location](https://github.com/redis/redis/blob/155acef51ac7826ed294a4b61d891f1c7a9a40ac/src/t_string.c#L174-L178) (although there are others).

If you're passing a reasonable non-zero, non-negative value, then it becomes more interesting, but since I'm pretty sure we've exercised this path ourselves a lot of times, I would be suspicious that the cause is in the bit we *don't* know, i.e. Foundatio; in which case: "ask them"?

**Comment by gdoron** [comment]
I'm dumb. Indeed something in our CI configuration changed that sent expiration time of 0.
Sorry for bothering you Marc :( , and you surely helped me find the root cause here <3
