### ISSUE TITLE
Error : No connection is active/available to service this operation: HSET

### ISSUE THREAD

**Issue by sachin27sharma** [StackExchange/StackExchange.Redis#2073]
Hi,
Am using StackExchange.Redis version 2.5.61.
Am constantly getting below error when my C# API is try to add to cache.

"error":{"message":"**No connection is active/available to service this operation: HSET** 145959a8-ff6f-417c-a14b-08da194ec4ab, mc: 1/1/0, mgr: 10 of 10 available, clientName: SampleHost (SE.Redis-v2.5.61.22961), IOCP: (Busy=1,Free=999,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767), POOL: (Threads=13,QueuedItems=0,CompletedItems=237), v: 2.5.61.22961","type":"StackExchange.Redis.RedisConnectionException","stack_trace":"Exception 01 ===================================\r\nType: StackExchange.Redis.RedisConnectionException\r\nSource: StackExchange.Redis.ConnectionMultiplexer, StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46\r\nMessage: No connection is active/available to service this operation: HSET 

My ConfigurationOptions are - 
"RedisCacheConfig": {
    "ConnectionEndPoints": [ "TestServer:6379" ],
    "ConfigurationOptions": {
      "AllowAdmin": true,
      "Ssl": false,
      "ConnectTimeout": 5000,
      "ConnectRetry": 3,
      "ChannelPrefix": "channelTest",
      "KeepAlive": 180,
      "Database": 0,
      "AbortOnConnectFail": false
    }
  }

I've a 3 redis server (1 master-2 slaves) and 3 sentinel services running on same 3 servers.
Its not a firewall or port issue are am able to connect to Redis Load Balancer without any issues from my API server.

Can you clarify which setting if missing could be the reason for above issue?

Thanks
Sachin

**Comment by sachin27sharma** [comment]
Will appreciate if this can be responded soon, as its effecting lot of connected systems.

**Comment by NickCraver** [comment]
Quick answer is it doesn't look like you're connecting, I'd either pass a logger in, or change `"AbortOnConnectFail": false` to true so it blows up and shows you what error you're hitting.

**Comment by slorello89** [comment]
Sounds like a config / connection issue - is `TestServer:6368` the endpoint you're expecting to connect to? That seems to be what your config is set to.

Also since you're using sentinel, I'd expect you to be connecting to one of the sentinel's (which are usually hosted on 26379 unless otherwise specified, you'd probably also need to specify the `ServiceName` in the config, which is the sentinel's service name.

**Comment by sachin27sharma** [comment]
So this was happening as I was using Redis port 6379 along with using Load Balancer hostname for connection endpoint.
Now, am trying to use sentinel (I've a 3 sentinel setup with quorum of 2) port 26379 with Load Balancer hostname - This doesn't work too due to below error.  **It looks like Load Balancer is not identified as valid sentinel server.**
**Message: Sentinel: The ConnectionMultiplexer is not a Sentinel connection. Detected as: Standalone**

The connection is working if I list down all 3 sentinel servers along with port 26379 in connection endpoint, and specify ServiceName property.

**Is there anyway I can use Load Balancer name for this setup?**

Thanks
Sachin

**Comment by NickCraver** [comment]
@sachin27sharma I'm confused here, a picture would help - if you have load balancers _to the sentinels_ but then they're returning which nodes to connect to directly? What is the load balancer? This seems like a network connection issue if it works without the load balancer, without knowing what load balancer it is or what's in play, I'm hesitant to suggest anything. If we're connecting to a standalone via the load balancer the only way I can see that happening is if it's load balancing to the child nodes, rather than the sentinels but...yeah, picture please!

**Comment by sachin27sharma** [comment]
Hi,

So i've the below setup. There 3 nodes (servers) itself are load balanced behind a Load Balancer. When setting up connection end points, we will like to use the Load balancer hostname, rather than using 3 nodes with sentinels ports.

"ConnectionEndPoints": [
      "MasterHost:26379",
       "Slave1Host:26379"
       "Slave2Host:26379"
    ]

![image](https://user-images.githubusercontent.com/16281381/162741010-dce05174-52af-4919-8452-8db4b1738491.png)

It looks like a network issue to open port for 26379 which might be stopping me right now.
Thanks
