### ISSUE TITLE
 Can LockTake() be used to synchronize batch operations between 2 or more processes?

### ISSUE THREAD

**Issue by leslietoo** [StackExchange/StackExchange.Redis#210]
Actually this is a continuous question of issue 144:
https://github.com/StackExchange/StackExchange.Redis/issues/144

I wanna use LockTake to synchronize batch operations on the same key between 2 or more processes(one connection for each certainly), NOTICE that I mean MULTI-PROCESSes, not MULTI-THREADs in one process. Can LockTake do that expectably?

**Comment by mgravell** [comment]
Yes; yes it can. The entire point of Lock* is to provide atomic centralised
locking. Basically, if the named key isn't available, it will return false.
Otherwise it will take the lock and return true. What it *doesn't*
currently include is "loop with pause until you can get the lock", but that
isn't hard to implement.

**Comment by NickCraver** [comment]
Answered above - closing out.
