### ISSUE TITLE
Redis Cache 2.5.61 gets Exception:  Could not load file or assembly 'System.IO.Pipelines, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by junlia** [StackExchange/StackExchange.Redis#2125]
Hello, 

I have just updated Redis cache NuGet package from 2.0.519 to 2.5.61, hoping to address out of memory issues the azure function App is experiencing and RedisConnectionException: No connection is available to service this operation.  But run into this run-time exception:

`System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Pipelines, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.\r\nFile name: 'System.IO.Pipelines, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'\r\n   at StackExchange.Redis.ConnectionMultiplexer.ConnectAsync(ConfigurationOptions configuration, TextWriter log)\r\n   at ABCD.Caching.RedisCacheProvider.GetConnectionAsync() `...

And  the exception still exists after I added `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` to <PropertyGroup> in both the redis caching & azure function  .csproj files. 

Our application utilizes azure function 32 bit v3.

I checked that System.IO.Pipelines.dll does exists on the webroot directory, just that it is this version:
![image](https://user-images.githubusercontent.com/10760817/165874328-37b37d56-a9a3-47b9-a8dc-8e57e41d0778.png)

and there is no 'System.IO.Pipelines, Version=5.0.0.1 Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' available even for in NuGet:
![image](https://user-images.githubusercontent.com/10760817/165874503-5ade1c14-2649-4ff9-bffb-76e7173f3c5d.png)

Any pointer how to we can upgrade Redis cache NuGet package without this runtime issue  would be appreciated.

Thanks much for the help in advance!

**Comment by NickCraver** [comment]
This is often a pretty confusing thing! The package version isn't the same as the assembly version. The easiest way without downloads to check a package's version is:
1. Go to the NuGet page (e.g. System.IO.Pipelines  - go to version 5.0.1): https://www.nuget.org/packages/System.IO.Pipelines/5.0.1
2. Click on [Open in NuGet Package Explorer](https://nuget.info/packages/System.IO.Pipelines/5.0.1) in the right sidebar.
3. Go to the lib you're on - I'm assuming lib/net461/ (though they should all align):

<img width="548" alt="image" src="https://user-images.githubusercontent.com/454813/170840582-bbe5335f-64e4-421a-8ef4-a1ed2b6a1fe7.png">

So the 5.0.1 NuGet package is the 5.0.0.1 strong named assembly. That's the version you want, or if using newer you'll need a binding redirect to a newer version that helps anyone looking for a lower version. Note: .NET Core does away with this because these strong named versions _just don't matter_ :)

I wrote a bit more on it here in case it helps: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by NickCraver** [comment]
Closing out to tidy up.
