### ISSUE TITLE
Setjson and dbsize

### ISSUE THREAD

**Issue by Ekotenggara** [StackExchange/StackExchange.Redis#2156]
Hi all,

I am used to run this script in python: 
db1 = Client(host='127.0.0.1', port='6379', decode_responses=True)
db1.dbsize
db1.jsonset(keyname, Path.rootPath(), jsonLine)

What is the equivalent of these two lines (for dbsize to get the database size and jsonset to add the rejson key) in C#?
I have set this in C#, but I am lost about what the next steps would be.
            var mux = ConnectionMultiplexer.Connect("127.0.0.1:6379, syncTimeout = 100000");
            var db = mux.GetDatabase();

Thank you for your help

**Comment by mgravell** [comment]
dbsize is DatabaseSize[Async](), but it is on IServer, not IDatabase, for
the reasons discussed here:
https://stackexchange.github.io/StackExchange.Redis/KeysScan

For jsonset: can you tell me exactly what that does, in redis terms?
meaningmeaning: what commands is that issuing? If that is referring to
RedisJSON l's JSON.SET, then you have a few options:

1. use database.Execture[Async]("JSON.SET", ...) which issues raw commands
(since JSON.SET isn't a native server command)
2. use a pre-built wrapper lib that exposes those features in a managed
way; not at a PC, but I can see if one exists later

**Comment by Ekotenggara** [comment]
Thanks you for your reply @mgravell 
The database size runs perfectly fine.

I apologized for not explaining setjson, it came from 'from rejson import Client, Path' module in python.
database.ExecuteAsync("JSON.SET", ...) will work fine I guess.
If it is in redis cli, I need to run :

json.set "R:1-20307369-20307369-A4-None-0-2" $ "{\"a\":\"49972\",\"b\":\"5272007\",\"c\":\"5272009\",\"d\":null,\"e\":null,\"f\":\"20307369\",\"g\":\"5\",\"h\":\"2022-04-24 02:33:04\",\"i\":\"A4\",\"j\":null,\"k\":\"1\",\"l\":\"0\",\"m\":\"1\",\"n\":194.76938722663797,\"o\":\"1\",\"p\":\"2022\"}"

How do I run it in IDatabase.ExecuteAsync("JSON.SET", ...) ?
Thank you again

**Comment by Ekotenggara** [comment]
Thank you @mgravell , it works perfectly, I missed the RedisKey type, I have been trying to insert it as a string. 
I may play with NReJSON later on, but your solution has worked perfectly for my case. Thank you again

**Comment by mgravell** [comment]
RedisKey only really matters if you're using "cluster", as it is part of
the routing / sharding logic (i.e. "which server?")
