### ISSUE TITLE
Support ReadOnlyMemory<RedisValue> in IDatabaseAsync.HashGetAsync() ?

### ISSUE THREAD

**Issue by antomys** [StackExchange/StackExchange.Redis#2174]
I am wondering why is there no overload of method `Task<RedisValue[]> HashGetAsync(RedisKey key, RedisValue[] hashFields, CommandFlags flags = CommandFlags.None);` that consumes `ReadOnlyMemory<RedisValue>` as parameter? `Task<RedisValue[]> HashGetAsync(RedisKey key, ReadOnlyMemory<RedisValue> hashFields, CommandFlags flags = CommandFlags.None);`

As an example, client can retrieve from somewhere redis call `RedisValue[]` and convert it into `ReadOnlyMemory<byte>[]` , manipulate with data and reverse convert to `ReadOnlyMemory<RedisValue>[]` in particularly no cost instead of creating a bunch of strings.

**Comment by mgravell** [comment]
Basically, API explosion. If we added ROM support to every API that takes arrays, that would represent a significant API increase. The benefit is a little unclear, especially when we would still be allocating on the way out. We'd also presumably want to do something lease based on the way out, and that is awkward, since ROM doesn't have that semantic (although I keep asking for it, via custom managers)

Note: the switch between byte/RedisValue/string is much more nuanced than you suggest. We can already construct RedisValue from ROM-byte, IIRC.

Perhaps the real thing to do here is take a step back. Forget about the API, and tell me explicitly: what actual problem are you trying to solve. Until we know that, we can't assess whether this would achieve it appropriately.

**Comment by antomys** [comment]
Thanks for your answer, @mgravell. 

For now i did not know that there is conversion from `ReadOnlyMemory<byte` To `RedisValue`. I thought it only worked in one way. Basically, it satisfies my case, when with retrieved `RedisValue[]` i had to do some manipulations and convert it back to the `RedisValue[]`. Simply saying, you are totally right that it is not needed increase of Api that would be unclear. 

Thanks again, closing thread
