### ISSUE TITLE
lua table return empty string

### ISSUE THREAD

**Issue by yyang1207** [StackExchange/StackExchange.Redis#2184]
lua
```
local cursor=0;
local tbl={};
repeat
	local result=redis.call("SCAN",cursor,"MATCH","sku*","COUNT",1000);
	if(result~=nil and #result>0)
	then
		cursor=tonumber(result[1]);
		local keyarray=result[2];
		local keynum=#keyarray;
		for i=1,keynum,1 do
			local ky=keyarray[i];
			local val=redis.call("GET",ky);
			tbl[ky]=val;
		end
	end
until(cursor<=0)
local str=cjson.encode(tbl);
return str;
```
in redis-cli execute
`EVALSHA c86f29fcb4f38da9fa586428c9f506f6fe7f2e2b 0`
it returns 
`"{\"sku5\":\"5\",\"sku2\":\"20\",\"sku3\":\"12\",\"sku1\":\"1\",\"sku10\":\"13\",\"sku4\":\"4\"}"`

in c# client **StackExchange.Redis**  use  **ScriptEvaluateAsync**   execute
it returns **empty string**

what  heppened?

**Comment by NickCraver** [comment]
Do you have code to show here? You're basically asking us to guess about both your code and the setup scenario here - a repro would be very helpful.

**Comment by yyang1207** [comment]
i want to use  the **SCAN**  command to match some keys，then add these key/value pairs to a **table**. 
i execute the lua script in redis-cli，it returns the right result。
when i execute the scriptsha in c# code，it returns empty string(nothing).

c# 
```
var db = _redis.GetDatabase(5);
var result = db.ScriptEvaluate(entity.SHA);
```

redis-cli
`EVALSHA c86f29fcb4f38da9fa586428c9f506f6fe7f2e2b 0`

**Comment by mgravell** [comment]
We don't have any impact on the processing - we just pass arts in, and parse results out. If something odd is happening, I could take guesses, but they'd all be about your setup - things we can't detect without a full repro. My initial thoughts:

- the data isn't what you think it is
- maybe incorrect database number?
- maybe incorrect sha hash?
- wrong server/port?

Perhaps one way to investigate would be to use MONITOR while executing, to see what exactly got sent in both the cli version and the library version. But for us to help, a full repro (i.e. something that adds some minimal expected data, then runs against it) would help.

If we (as outsiders to your intent) try to invent things for the minimal repro, it is likely we're going to make incorrect assumptions that invalidates the entire question.

---

On a related note: I'm not sure if the wisdom of using SCAN in a script. Because of the server threading model, your entire instance is jammed while that script runs to completion, which could now be unpredictability expensive. SCAN/KEYS should really only be used for occasional administrative purposes, and SCAN doesn't avoid the costs of KEYS if you're inside a script (because: no other connections can make use of the server between calls). I'd strongly recommend changing your data model to support what you need here, not using SCAN. The first thing that leaps to mind would be a secondary index using a "hash", so your script can be replaced with a single HGETALL or similar.

**Comment by mgravell** [comment]
Meaning instead of strings "sku5"="5", "sku2"="20", etc - you'd have a single hash called "skus" (or similar), with contents "5"="5", "2"="20", etc

**Comment by yyang1207** [comment]
> Meaning instead of strings "sku5"="5", "sku2"="20", "sku3"="12" etc - you'd have a single hash called "skus" (or similar), with contents "5"="5", "2"="20", "3"="12" etc

yes 
first，set some keys 
```
set sku5 5
set sku2 20
set sku3 12
set user1 33
```

second, write a lua script 
use **scan** command to match "sku*" ，get some keys like "sku5"  "sku2" "sku3"
use `get` command to get value，then add key/value to a **table**
use cjson.encode(table)  to serialize as a string
return the string

use the same lua script sha，redis-cli returns right result   c# code returns error result

**Comment by yyang1207** [comment]
> and SCAN doesn't avoid the costs of KEYS if you're inside a script



> We don't have any impact on the processing - we just pass arts in, and parse results out. If something odd is happening, I could take guesses, but they'd all be about your setup - things we can't detect without a full repro. My initial thoughts:
> 
> * the data isn't what you think it is
> * maybe incorrect database number?
> * maybe incorrect sha hash?
> * wrong server/port?
> 
> Perhaps one way to investigate would be to use MONITOR while executing, to see what exactly got sent in both the cli version and the library version. But for us to help, a full repro (i.e. something that adds some minimal expected data, then runs against it) would help.
> 
> If we (as outsiders to your intent) try to invent things for the minimal repro, it is likely we're going to make incorrect assumptions that invalidates the entire question.
> 
> On a related note: I'm not sure if the wisdom of using SCAN in a script. Because of the server threading model, your entire instance is jammed while that script runs to completion, which could now be unpredictability expensive. SCAN/KEYS should really only be used for occasional administrative purposes, and SCAN doesn't avoid the costs of KEYS if you're inside a script (because: no other connections can make use of the server between calls). I'd strongly recommend changing your data model to support what you need here, not using SCAN. The first thing that leaps to mind would be a secondary index using a "hash", so your script can be replaced with a single HGETALL or similar.

> We don't have any impact on the processing - we just pass arts in, and parse results out. If something odd is happening, I could take guesses, but they'd all be about your setup - things we can't detect without a full repro. My initial thoughts:
> 
> * the data isn't what you think it is
> * maybe incorrect database number?
> * maybe incorrect sha hash?
> * wrong server/port?
> 
> Perhaps one way to investigate would be to use MONITOR while executing, to see what exactly got sent in both the cli version and the library version. But for us to help, a full repro (i.e. something that adds some minimal expected data, then runs against it) would help.
> 
> If we (as outsiders to your intent) try to invent things for the minimal repro, it is likely we're going to make incorrect assumptions that invalidates the entire question.
> 
> On a related note: I'm not sure if the wisdom of using SCAN in a script. Because of the server threading model, your entire instance is jammed while that script runs to completion, which could now be unpredictability expensive. SCAN/KEYS should really only be used for occasional administrative purposes, and SCAN doesn't avoid the costs of KEYS if you're inside a script (because: no other connections can make use of the server between calls). I'd strongly recommend changing your data model to support what you need here, not using SCAN. The first thing that leaps to mind would be a secondary index using a "hash", so your script can be replaced with a single HGETALL or similar.

thanks, 
database number is incorrect.

**Comment by mgravell** [comment]
Glad we helped, tangentially. But please consider what I said about the impact of looping SCAN in a script. Quite honestly, I would put a hard veto against this code running on any system I have involvement in - it is much riskier than it looks.
