### ISSUE TITLE
How do I read the content of ArrayRedisResult?

### ISSUE THREAD

**Issue by NimaAra** [StackExchange/StackExchange.Redis#2195]
I am trying to obtain the result of _SLOWLOG GET_ by running:

```c#
RedisResult result = db.Execute("SLOWLOG", "GET", "100");
```
I can see the command returning 100 elements: 
![image](https://user-images.githubusercontent.com/16215744/180425669-1d85b3d7-5d6e-4b48-9c34-e0d7126674e4.png)

But I cannot figure out how to read the elements themseves. I have tried:

```c#
RedisResult result = db.Execute("SLOWLOG", "GET", "100");
result.ToDictionary();
```

which throws: `InvalidCastException`.

**Comment by mgravell** [comment]
Slowlog is already exposed on IServer - see https://stackexchange.github.io/StackExchange.Redis/KeysScan

In the more general sense: I suspect ToDictionary is failing because the shape is incorrect. There are APIs for parsing the data as an array. I'm not at a PC, but I expect ToArray or AsArray or a cast operator exist.

**Comment by NimaAra** [comment]
Thanks for the _IServer_ pointer.
I can't see those methods on the type and casting also fails. This is the best I can do and it's such YUK!

![image](https://user-images.githubusercontent.com/16215744/180432170-41337c2d-8705-41af-ad67-d38382d061d6.png)

**Comment by mgravell** [comment]
Indeed. The flexible API demanded by unknown commands is by necessity more
awkward to work with. It doesn't help here that the API itself often has a
weird shape. That's why we usually offer stronger APIs for most operations.
