### ISSUE TITLE
keys count is 0

### ISSUE THREAD

**Issue by redisuser22** [StackExchange/StackExchange.Redis#2198]
Good Morning 
Apologies if this was answered already,

I am pushing to azure redis using the below in a for loop (The process runs for every 2-3 mins and inserts around 5k recs)

   cacheDB.StringSet("{PHN}:" + sc.GPS_PHONE_NUMBER.Trim(), scJson, null, When.Always, CommandFlags.DemandMaster);
   
Then immediately after end of for loop , I am trying to retrieve the count 
   
      IEnumerable<RedisKey> keys = server.Keys(0, "{PHN}:*", 5000, CommandFlags.DemandMaster);
      azureCount = keys.Count();

Sometimes the above line returns 0 even though I see the recs on azure redis (using redis desktop manager)
and I knew that the process just pushed the 5k recs without issues . After 30 mins I see the correct count. 
I experimented with different CommandFlags ...

I  am using 
.net 4.8, c#
<package id="StackExchange.Redis" version="2.6.48" targetFramework="net48" />
azure redis version 4.0.14

Could you please help/ point in a correct direction.

**Comment by mgravell** [comment]
In terms.of the server behaviour... ultimately that's up to the server, and I'm not sure we can do anything about that. This seems unusual, though, and I'd like to try to repro locally. Is this on cluster? Or standalone?

However! As an important note: SCAN/KEYS are not intended to be used routinely like this. Spending lots of time digging into this feels like showing you exactly how to point the shotgun at your own feet. I'd be interested in understanding what you're *actual trying to achieve*, because there's probably a much better approach using a list, set, hash, sorted set, or similar (depending on your exact needs; I'm guessing "hash" is the closest, but: context matters)

**Comment by redisuser22** [comment]
Thanks for the reply.

In redis , we have 2 shards in the cluster.

I fetch data from another api, max 5k recs.
Each record from api is converted to json string(200KB each) and pushed to redis. 
I am trying to validate the no. of recs from api vs no. of keys in redis, to check if both the counts are same or not after I push the data. If the counts dont match then find delete them.

if(azureCount >0)
{
  if(azureCount <> apiCount) 
  { 
       FindAndDeleteKeysNotInApi(listAPI,listRedis);
  }
}
else
{
   Log.Error('azureCount  is  0');
}

Thank you.

**Comment by slorello89** [comment]
@redisuser22 - are you sure you are checking the right shard? I think of `IServer`  as an abstraction over a particular Redis server (@mgravell correct me if I'm wrong here), whereas IDatabase (which is what the cacheDb is presumably using?) is an abstraction over your redis deployment, your key names `"{PHN}:" + sc.GPS_PHONE_NUMBER.Trim()`  are using a [hash-tag](https://redis.io/docs/reference/cluster-spec/#hash-tags) in other words the slot is being determined by the hash of `PHN`.

the `KEYS` command runs on a particular server, and will only respond with the keys from that server, so if you're asking for keys on a particular server that match a pattern that cannot live on that server (because they are invalid for the servers slots), you'd probably get either an empty result set (which is what you are getting) or a MOVED error (I'd guess this wouldn't happen because you aren't invoking a specific key). In other words, if you ran this against the `IDatabase` rather than the `IServer` you'd probably get a more correct response.

As Marc mentioned, the use of the `KEYS` command is considered a major anti-pattern, Scan's a bit better - but still has a total time complexity of O(N), where N is the size of your entire keyspace, so it's probably not ideal for what you're looking for here, you'd probably want to use a set, or sorted set from what I gather here.

**Comment by redisuser22** [comment]
@slorello89 I am not sure, if there is a method to get the pattern based keys using IDatabase.

**Comment by slorello89** [comment]
@redisuser22 - no, there wouldn't be because Scan/Keys are both server-specific commands so RedisDatabase cannot make guarantees about which keys are on which. As @mgravell mentioned, these commands aren't great, and their use (particularly keys) is a major code-smells. I'm not entirely sure why you'd need to run the keys check to ensure it didn't fail? You'd know if it failed presumably because there would be an error. You can just add each keyname to a SET (`SADD set:{PHN} key`), and then run an SCARD against it?

```cs
for (var gpsNumber in numbers)
{
   cacheDB.StringSet("{PHN}:" + sc.GPS_PHONE_NUMBER.Trim(), scJson, null, When.Always, CommandFlags.DemandMaster); 
   cacheDB.SetAdd("set:{PHN}", keyName); // getKeyname from the way you generated the keys above
}

var length = db.SetLength("set:{PHN}");
```

I'd be remiss if I didn't point out that you should be able to do the bulk insertion in an async pattern to significantly trim down on the execution time (it'll automagically pipeline everything for you), but that's a different topic.

**Comment by redisuser22** [comment]
@slorello89  Thank you.
I will remove the call to keys . Thanks for your help.
