### ISSUE TITLE
What does bw: SpinningDown mean. 

### ISSUE THREAD

**Issue by danielpalacian** [StackExchange/StackExchange.Redis#2205]
Hello. 
We have very randomly timeout exceptions when we are using the library from a .net framework application. 
Most recently the error is something like this. 

RedisTimeoutException: Timeout performing EVAL (5000ms), next: EVAL, inst: 4, qu: 0, qs: 97, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 131072, in-pipe: 0, out-pipe: 0, serverEndpoint: ...., mc: 1/1/0, mgr: 9 of 10 available, clientName:  .... , IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=98,Free=32669,Min=1000,Max=32767), v: 2.6.45.45955 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Can someone pls explain what does bw: SpinningDown mean? 
Or can you see any other possible culprits for this error. 

Thx in advance, 
Daniel

**Comment by slorello89** [comment]
`qs: 97` Means you have 97 commands issued to redis awaiting a response and `in: 131072` means there is 128kb on the inbound socket waiting to be read off of it.

A couple of guesses:

1. The commands you are issuing against redis are long and blocking the server, you can check this by checking your slowlog with [`SLOWLOG GET`](https://redis.io/commands/slowlog-get/)
2. The payloads you are pulling back are very large, you are flooding the inbound sockets, and you are running into bandwidth constraints. I've seen this in instances where people have been using the SessionStateManager and have many sessions which are many MBs - they present exactly like this, because there's some upper limit on what that inbound socket can hold - considering 131072 bytes is exactly 128 kb, I suspect that this is the limit.

**Comment by NickCraver** [comment]
Agree with Steve's notes above - to add the other question: SpinningDown means "the backlog is idle, has finished writing, and is only lingering waiting to see if anything else to process comes in". After a backlog process, we don't immediately spin down the thread because starting one is expensive - we let it longer a bit (with near zero cost) to monitor any more additions. If it gets some, rinse and repeat, if not the thread will go away.

**Comment by NickCraver** [comment]
Closing out to tidy up!
