### ISSUE TITLE
What does bw: SpinningDown mean?

### ISSUE THREAD

**Issue by abrahma** [StackExchange/StackExchange.Redis#2210]
Hi,

We are getting timeout exception while using from .net core framework application and Azure Redis.

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 15848ms elapsed, timeout is 15000ms), command=GET, next: GET 4051050825906537794, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: ****, mc: 1/1/0, mgr: 10 of 10 available, clientName: ***(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=200,Max=32767), POOL: (Threads=4,QueuedItems=0,CompletedItems=3876664), v: 2.6.48.48654 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

What does bw:SpinningDown mean? 
Can you please help us in identifying the issue here.

Thanks,
Ankita

**Comment by NickCraver** [comment]
SpinningDown is a state which means the backlog processed at least 1 command at some point in the last minute, but is idle now and the thread will go away if nothing comes in (starting and stopping threads is relatively expensive, so we hang around and wait to see if anything comes in for a bit).

Overall your error looks like a server stall - suggest running SLOWLOG on the server side to see if there are any pauses since nothing appears to be backed up on the client end (nothing pending and nothing in queue).

**Comment by abrahma** [comment]
Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5452ms elapsed, timeout is 5000ms), command=GET, next: GET com.samsung.android.contacts, inst: 0, qu: 0, qs: 0, aw: False, bw: SpinningDown, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: ****, mc: 1/1/0, mgr: 10 of 10 available, clientName: **(SE.Redis-v2.6.48.48654), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=200,Max=32767), POOL: (Threads=6,QueuedItems=2,CompletedItems=4994697), v: 2.6.48.48654


We got a similar exception again but here threads=6 and queuedItems=2. 
What does this queuedItems signify when qu and qs are 0?
