### ISSUE TITLE
Redis timeout investigation

### ISSUE THREAD

**Issue by Allmantool** [StackExchange/StackExchange.Redis#2289]
Prerequisites

- StackExchange.Redis v 2.2.4 Nuget
- Net core (3.1 - 6.0) web app
- Sync flow
- Redis server deployed on VM (thus, cloud communication)
- inst & qs can be up to 400 (don't know if it's a problem)
- ConnectionMultiplexer is a lazy singleton.
- IDatabase also resolved as a singleton at constructor level (can it be a problem ? )

Average error: (for more details pls. take a look at the attached file)

![image](https://user-images.githubusercontent.com/16443259/198853200-a03ee7e5-912e-4039-becc-60d9c249f92a.png)

Question:

- Read lots of similar articles about RedisTimeoutException, but still can't figure out in what direction should to go to resolve the issue
- My main suggestion, at that moment that there some problem with connection starvation, but not sure. And ever more don't know how to correctly fix it

Pls. provide some suggestion what can be fixed there ?

[redis-timeout.csv](https://github.com/StackExchange/StackExchange.Redis/files/9894601/redis-timeout.csv)

**Comment by NickCraver** [comment]
What machine is this on? All of these exceptions have very high active thread counts which likely means you're hitting thread pool limits, usually due to synchronous (rather than `async`) calls. You can: up the thread pool min count (band-aid, to be clear), raise the timeout to absorb large events, or go proper async in the flow so that threads aren't held onto while you're waiting for data to come back. The async option is by far the best, though I realize it's not trivial in a large application.

If you memory dump when this happens, you can see where all the threads are and what they're waiting on, this can give you a good idea of where to do the most impactful changes first.
