### ISSUE TITLE
Expiration Time 

### ISSUE THREAD

**Issue by akshatchhangani** [StackExchange/StackExchange.Redis#2298]
Hi Team and @mgravell ,
I am replacing DistributedCache in my code and using StackExchange Library. I want to know how to set SlidingExpirationTime, AbsoluteExpirationTime and AbsoluteExpirationTimeRelativeToNow.

**Comment by NickCraver** [comment]
This isn't a function directly available in the library, e.g. changing it on touch (because Redis doesn't). But you can: set the TTL of a key (e.g. how long from how to expire) and Redis server itself has [key eviction policies](https://redis.io/docs/reference/eviction/) for global application if you want a least recently used cache expunge or something.

Some libraries built on top of ours have such translations to give various desired behaviors, though I'm not sure what is the most popular set these days.

**Comment by NickCraver** [comment]
Closing out to tidy up, happy to reopen if there's a follow-up here.
