### ISSUE TITLE
zrevrangebyscore deprication

### ISSUE THREAD

**Issue by sadeghhp** [StackExchange/StackExchange.Redis#2302]
"zrevrangebyscore" command is now deprecated. it can make some issues in production with massive requests

please check this link:
https://github.com/redis/redis/issues/6680

It can be replaced by [ZRANGE](https://redis.io/commands/zrange) with the REV and BYSCORE arguments when migrating or writing new code.

**Comment by mgravell** [comment]
As I understand it, the actual data and performance is the same here regardless - simply; now that `ZRANGE` has `REV` and `BYSCORE` (since 6.2.0), the intention is to reduce everything to use the one command; so: yes we can *do this*, but I wouldn't consider it super-critical. The performance degredation in the linked post is irrelevant; as I understand it `ZRANGE` with the same sizes would have the exact same features.

**Comment by NickCraver** [comment]
Since answered above - closing out to tidy up!
