### ISSUE TITLE
Question: Efficiently delete RedisKeys in bulk via wildcard pattern

### ISSUE THREAD

**Issue by udlose** [StackExchange/StackExchange.Redis#2313]
**Problem**: 
I need to efficiently delete keys from my Redis Cache using a wildcard pattern

**Tech stack**: 
- .NET 6 (async all the way through)
- StackExchange.Redis 2.6.66
- Redis Server 6.2.6.
- I currently have ~500k keys in Redis.

**Example**:
I store the following 3 keys:
```
dailynote:getitemsforuser:region:sw:user:123
dailynote:getitemsforuser:region:fl:user:123
dailynote:getitemsforuser:region:sw:user:456
...
```

The original solution used the `KeysAsync` method to retrieve the list of keys to delete via a wildcard pattern. Since the Redis Server is 6.x, the `SCAN` feature is being used by `KeysAsync` internally by the `StackExchange.Redis` nuget. 

Original implementation used a wildcard pattern `dailynote:getitemsforuser:region:*`. As one would expect, this solution didn't scale well and we started seeing `RedisTimeoutExceptions`.

I'm aware of the "avoid this in PROD if you can" and have seen Marc Gravell respond to a couple other questions/issues on SO and StackExchange.Redis GitHub. The only potential alternative I could think of is to use a Redis `SET` to "track" each `RedisKey` and then retrieve the list of values from the `SET` (which are the keys I need to remove). Then delete the `SET` as well as the returned keys.

**Potential Solution?**:

1. Create a Redis `SET` with a key of `dailynote:getitemsforuser` with a value which is the key of the form `dailynote:getitemsforuser:region:XX...`

The `SET` would look like:
```
dailynote:getitemsforuser (KEY)
    dailynote:getitemsforuser:region:sw:user:123 (VALUE)
    dailynote:getitemsforuser:region:fl:user:123 (VALUE)
    dailynote:getitemsforuser:region:sw:user:456 (VALUE)
    ...
```
I would still have each individual key:
```
dailynote:getitemsforuser:region:sw:user:123
dailynote:getitemsforuser:region:fl:user:123
dailynote:getitemsforuser:region:sw:user:456
...
```
2. when it is time to do the "wildcard" remove, I get the members of the `dailynote:getitemsforuser` `SET`, then call `RemoveAsync` passing the members of the set as the `RedisKey[]`. Then call `RemoveAsync` with the key of the `SET` (`dailynote:getitemsforuser`)

I'm looking for feedback on how viable of a solution this is, alternative ideas, gotchas, and suggestions for improvement. TIA

**Comment by mgravell** [comment]
The feature you want does not directly exist on the server, this we cannot expose it at the client (efficiently).

The usual advice is: if you can partition the things you frequently need to delete as a bulk item, make *that prefix* the key of a *hash*, and treat the rest of the key (suffix) as the hash field-names. Then deleting that entire prefix means deleting the hash, which is a single call.

**Comment by udlose** [comment]
Thanks for your prompt reply!

In my case, each of the "original" keys stores JSON as a string in its value (I don't have the ability to use RedisJSON for various reasons).  How would that work with your suggestion?

**Comment by slorello89** [comment]
If you only need to support prefixes/postfix, a hash would work as Marc suggested. If all you need is prefixes and postfixes and the cardinality of the prefixes you need to be able to inspect isn't well defined, you could potentially use a sorted set with lexigraphic ordering:


```
127.0.0.1:6379> ZADD testPrefix 0 dailynote:getitemsforuser:region:sw:user:123
(integer) 1
127.0.0.1:6379> ZADD testPrefix 0 dailynote:getitemsforuser:region:fl:user:123
(integer) 1
127.0.0.1:6379> ZADD testPrefix 0 dailynote:getitemsforuser:region:sw:user:456
(integer) 1
127.0.0.1:6379> ZRANGE testPrefix [dailynote:getitemsforuser:region:sw (dailynote:getitemsforuser:region:t BYLEX
1) "dailynote:getitemsforuser:region:sw:user:123"
2) "dailynote:getitemsforuser:region:sw:user:456"
```

you could then delete the ids you got back.

obviously for postfixes you'd just reverse your keynames :) , and if you need a combo you could always use set combination operations to find the intersections.

This leaves out the case where you have a mid-string wildcard - unfortunately there's not a method to support that outside of RedisJSON that I know of.

**Comment by udlose** [comment]
I should add that each of the "original keys" has a TTL which would mean that I'd need to have the _fields_ of the hash that not only support TTL, but also support _different_ TTL's between each other - i.e. `STRING` key of `dailynote:getitemsforuser:region:fl:user:123` will have a different TTL than `STRING` key of `dailynote:getitemsforuser:region:sw:user:456`

**Comment by udlose** [comment]
> If you only need to support prefixes/postfix, a hash would work as Marc suggested. If all you need is prefixes and postfixes and the cardinality of the prefixes you need to be able to inspect isn't well defined, you could potentially use a sorted set with lexigraphic ordering:
> 
> ```
> 127.0.0.1:6379> ZADD testPrefix 0 dailynote:getitemsforuser:region:sw:user:123
> (integer) 1
> 127.0.0.1:6379> ZADD testPrefix 0 dailynote:getitemsforuser:region:fl:user:123
> (integer) 1
> 127.0.0.1:6379> ZADD testPrefix 0 dailynote:getitemsforuser:region:sw:user:456
> (integer) 1
> 127.0.0.1:6379> ZRANGE testPrefix [dailynote:getitemsforuser:region:sw (dailynote:getitemsforuser:region:sx BYLEX
> 1) "dailynote:getitemsforuser:region:sw:user:123"
> 2) "dailynote:getitemsforuser:region:sw:user:456"
> ```
> 
> you could then delete the ids you got back.
> 
> obviously for postfixes you'd just reverse your keynames :) , and if you need a combo you could always use set combination operations to find the intersections.
> 
> This leaves out the case where you have a mid-string wildcard - unfortunately there's not a method to support that outside of RedisJSON that I know of.

How would you account for the storing of values within the original keys:
```
> dump dailynote:getitemsforuser:region:fl:user:123
"{\"Name\":\"john\",\"Age\":22}"
```

**Comment by slorello89** [comment]
@udlose - you would only store the keynames in the sorted set, you'd still have your data stored in individual separate keys. TTL would apply to the data's key, not to the prefix sorted set. You could have a larger sorted set with all of your keys and their expiration times in it that you could do traditional ranges over to see what's expired, and clean them out periodically, that's more an optimization step, since you don't want to retrieve/delete expired keys as it increases size of your payload back and forth to Redis (also spare redis from having to iterate over and check a released key).

**Comment by udlose** [comment]
Is there any way to create some sort of dependency between them, like a foreign key or something so that when the `STRING` key expires it removes the corresponding keyname from the set?

**Comment by slorello89** [comment]
Redis is fundamentally not a relational database, so these sorts of cascading relationships simply aren't something supported by the technology. 

The solutions suggested are correct in that after you run your delete, your Redis instance will be in the correct state regardless as to whether the keys have expired or not, the expiration Sorted Set is merely a pattern of optimization.

If you want to automatically remove keys from the set when they expire there are ways you can do that, however they don't have the isolation/consistency guarantees you're used to from a relational database.

1. You can use [keyspace notfications](https://redis.io/docs/manual/keyspace-notifications/#timing-of-expired-events) to have your client be notified when a key expires, the client can then dispatch the ZREM to remove the key from the set
2. You can use [Redis Gears](https://oss.redis.com/redisgears/examples.html#keyspace-notification-processing) to create a gear that will be triggered when a keyspace expiration is heard, and have the gear remove it from the sorted set. The nice thing about this is that nothing has to go over the network.

I'm assuming since you cannot use RedisJson, you probably cannot use Gears (same licensing and it loads more components than the RedisJson so). Which leaves your client keyspace notifications. You will still want to periodically clean out your expired keys using the method I mentioned above, because keyspace notifications are driven by the same interface that handles pub/sub, so there's a chance you might miss messages, in which case you'd have stale data in your sets.

**Comment by NickCraver** [comment]
Closing out to tidy up here.
