### ISSUE TITLE
Is there a support for Credentials provider?

### ISSUE THREAD

**Issue by tavisca-manpreet** [StackExchange/StackExchange.Redis#2314]
I am trying to connect to elasticache with IAM auth mode in which a temp token (valid for 15 min ) is generated and provided as password for client connection. I wanted to check if StackExchange.Redis has an option to provide a credentials provider implementation that takes care of token generation when needed

**Comment by NickCraver** [comment]
This library doesn't have anything to do with credential generation, so there's no concept of "when needed" for us to trigger on - that'd be up to each system rotating credentials.

The way you can do rotation is to hang on to your `ConfigurationOptions` object passed to `.Connect` or `.ConnectAsync` - if you update the password on it, that'll be used next reconnect. Or you can force a reconnect on the multiplexer right then. Regardless, that's how you'd go about it :)

**Comment by tavisca-manpreet** [comment]
The issue with updating the ConfigurationOptions object is that the consuming application has to keep track of it and update the credentials, rather I think a cleaner solution would be that the credentials are fetched from a credential provider when reconnecting. This way, the consuming application can provide a fixed password or create a dynamic one at runtime but does not have to take care of the when part. "When needed" here can be next reconnect, but since this reconnect event is handled by the library, the library can take the responsibility of calling the ConfigurationProvider to get the credentials.
This is query similar to https://github.com/StackExchange/StackExchange.Redis/pull/2033 where there is discussion about a "DefaultOptionsProvider" for this purpose in which the getter can be overridden to provide a custom implementation.
Also, please refer to https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html for more reference to the use case.

**Comment by mgravell** [comment]
Actually, we call Clone() - I don't think holding onto the object and
changing the password would have any useful effect anyway; we'd need
something internally.

**Comment by NickCraver** [comment]
We called `.Clone()` in the old days, but since #2050 (explicitly to support this scenario), we should be good here :)

There are several issues with "getting the credentials when connecting", and here's why we don't do that:
- What does a connect timeout mean?
  - Does it mean just the Redis part or also fetching the credentials?
  - If a timeout includes the provider, do we throw all different exceptions? Or add a new timeout? Who controls that timeout?
- What happens if a dozen connections share a credential provider, do they each call to get the credentials?
- What happens if Redis is down and we're trying to connect quite frequently - do we DDoS the credential source? Or is there some backoff? (even more options)
- Reconnects are per-connection, not per-multiplexer - how do clusters work? Do we fetch for each node or assume they're in sync? (...and is that assumption safe for all people? What about Sentinel setups?)

All of those are baseline questions that would appear to be at the initial connection, but they're not. They come up every reconnect whether it's because of a network hiccup or an explicit initial connection. We have very explicit and often configured-to-be-tight timeouts on reconnecting to sources that get a _lot_ more complicated if we're connecting to something that isn't Redis.

And, it's just inefficient. Your credential provider can choose to listen to some event you know of to change the password going in, do it on some interval, or be triggered by a disconnect event - it's totally your choice. Ultimately all you're doing it setting the credentials on the options.

You can do this by holding on to a reference to the `ConfgurationOptions` or you can create that `DefaultOptionsProvider` which has a getter for user/password on it (just leave user/password blank on the `ConfgurationOptions` itself so it falls back). [All of that works today](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Configuration/DefaultOptionsProvider.cs), so I'm not sure what functionality we'd add here that's a net win. If you want a custom implementation, you're creating an instance and passing it in...all of that works now, all we'd be adding is a different permutation of that.

Whatever you choose to do here though, consider my questions above - these are something someone rotating passwords needs to be aware of. I do not recommend calling out to the source for data in the getter of user/password on the `DefaultOptionsProvider` for example - you want to refresh it when it makes sense and memoize the value there, via timer, event, or whatever. Doing so eliminates a lot of questions and inefficiencies at the same time.

**Comment by NickCraver** [comment]
Answered above on the approach here, so going to close this out to tidy up. Happy to re-open if there's a follow-up.
