### ISSUE TITLE
StackExchange.Redis How can I configure the library having the eval command disabled

### ISSUE THREAD

**Issue by edcastanohunter** [StackExchange/StackExchange.Redis#2315]
I am using the [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis) library to handle all the Redis related work. Currently I have a user that does not have the eval command enabled. How can I configure the library to not use the eval command and try the SET command directly?

This is the exception that I am getting

```
StackExchange.Redis.RedisServerException: NOPERM this user has no permissions to run the 'eval' command or its subcommand
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)
```

I know that this is related with the setup of the user, but as we are not going to have that right enable, how can we work using the library?

Regards,

I am using dotnet core 6 and targeting StackExchange.Redis version 2.2.88. Also posted the question in [StackOverFlow](https://stackoverflow.com/questions/74617199/stackexchange-redis-how-can-i-use-the-library-having-the-eval-command-disabled)

**Comment by NickCraver** [comment]
The issue here isn't with this library, but the Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache library which is calling our methods to use eval. You'll want to ask for this functionality in that library: https://github.com/dotnet/extensions - it's nothing that can be solved here, we're literally only being called with a script to execute.

**Comment by slorello89** [comment]
This is an [ACLs](https://redis.io/docs/management/security/acl/) issue, there's nothing for the client to do as it can only use the commands that the user's permitted to use.

**Comment by mgravell** [comment]
@NickCraver  actually, it is probably here: https://github.com/dotnet/aspnetcore/ (specifically https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs) - which means this is probably "me", but with a different hat on. It would need a little consideration and I wouldn't rush in and change it "just because", but it *looks* like this should be doable with some `MULTI`/`EXEC` love instead, in the "set with relative-expiration" case

**Comment by edcastanohunter** [comment]
I just wonder how would it be to have a implementation for [IDistributedCache](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache) just using you library, I mean with the "correct" commands, I am not so versed in Redis as such, just learning.
