### ISSUE TITLE
What exactly does abortConnect control?

### ISSUE THREAD

**Issue by gdoron** [StackExchange/StackExchange.Redis#2318]
Hi guys,

I used StackExchange.Redis for many years, and read the [documentation](https://stackexchange.github.io/StackExchange.Redis/Configuration.html#:~:text=If%20true%2C%20Connect%20will%20not%20create%20a%20connection%20while%20no%20servers%20are%20available) for `abortConnect` more than a dozen times
> If true, Connect will not create a connection while no servers are available

But to this day, I can't really say I understand what it does exactly.
If it's true, would it throw? what about disconnects? Microsoft [here](https://gist.github.com/JonCole/36ba6f60c274e89014dd#the-cause) claims it also effects temp disconnections.

Can you please explain in more details this important configuration?

Thanks!

**Comment by NickCraver** [comment]
It means it'll complete the connect calls (creating one) even if it can't connect. So for example if your application comes up before the Redis server does (happens in cloud scenarios especially when provisioning for the first time), it'll return a connection that wasn't successful but is continuing to retry/reconnect in the background. As soon as it succeeds and we have a server, commands will succeed. Until then, expect timeout errors because commands waited in a buffer for a long as possible for a server to be available and then gave up when it wasn't.

**Comment by gdoron** [comment]
Thanks @NickCraver.
Does it have something to do with disconnections at all?
Because there is a connection object, but just for some reason there was a disconnection.
Does it still keep the commands waiting and retry until the timeout?

**Comment by NickCraver** [comment]
A current version (2.5+) will buffer commands to retry when a connection is available, up until the timeout, yes. Previous versions would error immediately and didn't have this backlog functionality.
