### ISSUE TITLE
Threads are performing asynchronous work but are waiting on a synchronous call to method. This may cause thread pool starvation and hangs.

### ISSUE THREAD

**Issue by DarthSonic** [StackExchange/StackExchange.Redis#2326]
We have several issues in our app with high cpu consumption and hanging threads. One of them is caused by StackExchange.Redis:

This is all information I can provide (taken from memory dump analysis):

"2 threads are performing asynchronous work in method 'StackExchange.Redis.PhysicalBridge.ProcessBacklogAsync()', but are waiting on a synchronous call to method 'System.Threading.WaitHandle.WaitOne(int, bool)'. This may cause thread pool starvation and hangs."

![image](https://user-images.githubusercontent.com/3968605/208882288-96819a55-6b71-4446-a487-f0bc8454bee7.png)

![image](https://user-images.githubusercontent.com/3968605/208882651-0824d1d4-3351-42cf-b396-6d7438f7a0d1.png)

![image](https://user-images.githubusercontent.com/3968605/208882758-37a2db66-5823-47c1-8385-d5cbb84e7cb6.png)

**Comment by DarthSonic** [comment]
Here the "2 threads" displayed. Both from or called by StackEchange.Redis.

![image](https://user-images.githubusercontent.com/3968605/208884246-5c706a5b-ff47-468a-86cb-8af453c5e9b3.png)

**Comment by NickCraver** [comment]
What you are seeing is normal and not an issue. As noted in the comments that's a dedicated thread (of which where is at most 1 per bridge). It only appears when there is a backlog to process of commands that could not be sent and then waits (using no CPU) for 5 seconds for any other stragglers to come in, because starting and stopping a thread for each is ridiculously more expensive. It is working exactly as it should and not causing any hangs to anything else.

I'm not sure what happened to the second command here but the screenshot you posted would absolutely be something that deadlocks with ASP.NET context. This is one of the most common deadlock sources in .NET, 2 things waiting on the synchronization context (HttpContext in that case) and neither can get it because neither is releasing it. I saw an `AsyncHelper.RunSync` method which is a huge red flag to me and would be the first thing I'm looking at. Usually a method like that is trying to prevent async from going viral, but the consequences of trying things like that are deadlocks, as you're witnessing now.
