### ISSUE TITLE
C# how to store and retrieve model in redis that has a serialized string field

### ISSUE THREAD

**Issue by MostafaSDesoky** [StackExchange/StackExchange.Redis#2335]
Hello
I'm trying to store a model to the redis that has 3 string fields each one is serialized json
I have no problem in setting it and I can see it in redis insight
but when getting it from redis it fires error json exception when digging deep into it, the problem with those string fields that contains json

```
  [Document(Prefixes = new[] { "Demo" })]
    public class Demo
    {
        [Indexed]
        public string ReferenceNumber { get; set; }  
        [Indexed]
        public string Note { get; set; }
        [Indexed]
        public string ItemsData { set; get; }  <-- those the string fields that contains json
        [Indexed]
        public string SkillsData { get; set; }
        [Indexed]
        public string Data { get; set; }
    }
```

**Comment by mgravell** [comment]
SE.Redis doesn't do anything re serialization, indexing, etc; it just exposes the underlying redis API. You say you have no problem "setting it" - fine: can we see the code you're using for that? Likewise, you say "but when getting it from redis it fires error json exception" - can we see the code for that too? Since we don't do deserialization, presumably that error is coming from your code? Or perhaps you've confused two libraries?

**Comment by mgravell** [comment]
I think you're talking about Redis.OM; however, that *isn't us*.
