### ISSUE TITLE
ConnectionMultiplexer.IsConnected remains True eventhough Sentinel is down.

### ISSUE THREAD

**Issue by kg-logix** [StackExchange/StackExchange.Redis#2336]
I have a configuration of 3 Redis Sentinels monitoring 1 Redis Master and 3 Redis Slaves. I am connecting to the Redis Sentinels using the following configuration settings:

```
configuration.AbortOnConnectFail = true;
configuration.ConfigCheckSeconds = 1;
configuration.ConnectTimeout = 1000;
configuration.KeepAlive = 1;
configuration.EndPoints.Add("192.168.1.217", 26379);
configuration.EndPoints.Add("192.168.1.217", 26380);
configuration.EndPoints.Add("192.168.1.217", 26381);
configuration.ServiceName = "servicename";
configuration.Password = "password";

var connection = ConnectionMultiplexer.SentinelConnect(configuration, Console.Out);
```
And pass that connection through dependency injection as an ` IConnectionMultiplexer. `

Within my program I then:
1. Get the Endpoints [ _IConnectionMultiplexer.GetEndpoints( )_ ];
2. Get the Servers [ _IServer.GetServers( )_ ];
3. Check each IsConnected.

The issue is that if I pause a Sentinel in my docker container the **IsConnected** doesn't change from **True** to **False**. 
However, if I start the program with the container paused the **IsConnected** returns **False** and changes to **True** if I resume the container. 

Has anybody experienced the same issue and can help out please?

**Comment by NickCraver** [comment]
What is your overall goal? Do you want to monitor something from Sentinel specifically? Most users want to connect to the primary server _behind_ Sentinel which is what a regular `.Connect()` rather than `.SentinelConnect()` will do here. The intent is that we connect to Sentinel, return the current primary connection Sentinel tells us about, and switch if that changes (based on pub/sub messages from Sentinel). I'm not sure checking the Sentinel connection itself directly for all properties has been something that's exhaustively done or something anyone has cared about yet. So I'm trying to ask: is this an important thing to poke at, or does `.Connect()` getting you the underlying primary and kind of ignoring Sentinel exists do what you ultimately want to do here?

**Comment by kg-logix** [comment]
The overall goal is to monitor the system's status and health through the sentinels instead of connecting to the primary directly. This gives me more information on the Redis structure such as if a fail-over is currently taking place. I felt that this is also advantageous as the application does not flood the master with pinging calls but instead takes advantage of the inherent calls the sentinel does to the primaries and replicas.

**Comment by kg-logix** [comment]
Thanks for the response @NickCraver. 

I am aware that the ConnectionMultiplexer handles the monitoring and performs changes if the primary changes. However I wanted to point out that the **IsConnected** property does not go to false when I pause the Sentinel in my docker container (replicating a the Sentinel going offline).

I wanted to point it out since I believe this can be a bug, regardless of its use case.

**Comment by NickCraver** [comment]
@kg-logix We are still connected though, to the actual server. Sentinel isn't required to keep doing everything we need with Redis and all commands continue to function, so why would we represent it any other way here?

If you want to very specifically connect to the Sentinel server and monitor that for any reason, you can use `ConnectionMultiplexer.SentinelConnectAsync()` and it'll have the `.IsConnected` behavior for that endpoint.

What you're seeing is absolutely by design. Sentinel's primary use is to manage servers and maximize uptime. To kill all connections when the _helper_ is down but everything else would be working is explicitly something we do not want to do, nor would any user I'm aware of desire. That's akin to shutting all your servers down because you're rebooting the monitoring system.

**Comment by kg-logix** [comment]
@NickCraver thanks for your response. I believe there is a misunderstanding here though. 

My issue concerns the **.IsConnected** property for the **Sentinel** endpoint which is resulting in **true** despite having that Sentinel container paused in docker. 

I have found other Github Issues  similar to what I am saying and after some digging I realized that the issue I was experiencing was due to the container being paused (i.e. if I stop the container, the .IsConnected reflects the correct state of the Sentinel Endpoint). 

In truth I still don't know if this is an issue or not but I will be closing the issue.
