### ISSUE TITLE
what's the difference between ResponseTimeout and SyncTimeout?

### ISSUE THREAD

**Issue by leslietoo** [StackExchange/StackExchange.Redis#235]
there are two type Timeout in ConfigurationOptions class: ResponseTimeout and SyncTimeout. It's hard to understand the difference from source code comment. Can u explain them separately?

**Comment by NickCraver** [comment]
ResponseTimeout is the number of ms before we treat the connection as dead - since it's been that long since we've seen activity on the connection and treat it as "stale". SyncTimeout is the amount of time to wait on *a specific operation* to complete. For example a synchronous `GET` to make the full round trip and complete.
