### ISSUE TITLE
Caching ServiceBusSender Object to Redis Cache

### ISSUE THREAD

**Issue by akhilesh-doc** [StackExchange/StackExchange.Redis#2375]
Hi Team,

I am using AzureFunction to work on some functionality , its Service Bus triggered event.

As you know that Creating ServiceBusSender object are costly, my plan is to create ServiceBusSender object once and cache that object so that it can be used latter when AzureFunction event triggered. Ex.

 ServiceBusClient serviceBusClient = new ServiceBusClient(_messageBrokerMetadata.QueueConnectionString,

                                                             new ServiceBusClientOptions { TransportType = ServiceBusTransportType.AmqpWebSockets });

                serviceBusSender = serviceBusClient.CreateSender(_messageBrokerMetadata.QueueOrTopicName);

I want to cache serviceBusSender  object to Redis Cache.  so next time I don't want to create ServiceBusSender object, I should retrieve from Redis Cache if object is available, I can get it and use rather that creating new Object again.

I am trying to cache that object on Azure Redis Cache. While retrieving ServiceBusSender cached on Redis, I am getting an exception ie. FullyQualifiedNamespace is throwing null exception .

Is there any way I can cache ServiceBusSender object to Redis Cache.

Note :- its working fine with In memory cache.

Images showing Cached Data is retrieved but when we are reserializing it for ServiceBusSender, its throwing exception

![MicrosoftTeams-image](https://user-images.githubusercontent.com/125657261/219643166-6c3c340a-08b3-4599-99d3-5b573aa46e48.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/125657261/219643225-ec01dece-b30e-4e4c-bf76-4da164dfc2bc.png)

**Comment by NickCraver** [comment]
As far as I'm aware, that's a client and not something you can serialize. It has connection, state, etc. so that's just not something you're going to be able to serialize across the wire and get back. Objects have to be simple things you can save and get back to restore all the data you need to create it again - ServiceBusSender [is not that](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs), it's a complex object with a lot going on.

Put another way, if you can't serialize it to a memory stream and back, you can't stick it somewhere else like Redis either. The same as say serializing it to JSON and back - all the same story.

**Comment by akhilesh-doc** [comment]
@NickCraver , I was going through https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussender?view=azure-dotnet and its saying that we can cache the Sender Object as mentioned.

"The [ServiceBusSender](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussender?view=azure-dotnet) is safe to cache and use for the lifetime of an application or until the [ServiceBusClient](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusclient?view=azure-dotnet) that it was created by is disposed"

What is your thought on this.

**Comment by mgravell** [comment]
I think what they're saying there is that you don't need to create the object each time you use it. A different form of cache. Perhaps "reuse" would have been a better word for them.

**Comment by NickCraver** [comment]
Closing out to tidy up!
