### ISSUE TITLE
Sentinel startup dependency

### ISSUE THREAD

**Issue by bukowskim** [StackExchange/StackExchange.Redis#2390]
I am trying to use Redis Sentinel with docker-compose and sentinel mode on. The connection string looks like this:
StackExchange.Redis is in 2.6.96 version.

```
localhost:26379,serviceName=mymaster,allowAdmin=true,abortConnect=false,tiebreaker=
```

Since the recommendation is to have a single TCP connection I want to create it on an application startup, like that:

```csharp
ConnectionMultiplexer.Connect("localhost:26379,serviceName=mymaster,allowAdmin=true,abortConnect=false,tiebreaker=")
```

If I do that and:
- redis master is not available - I am getting:

```
StackExchange.Redis.RedisTimeoutException: Timeout performing ROLE (5000ms), inst: 0, qu: 1, qs: 0, aw: False, bw: SpinningDown, rs: NotStarted, ws: Idle, in: 0, last-in: 0, cur-in: 0, sync-ops: 1, async-ops: 0, serverEndpoint: 127.0.0.1:6379, conn-sec: n/a, mc: 1/1/0, mgr: 10 of 10 available, clientName: L104024(SE.Redis-v2.6.90.64945), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=0,Free=32767,Min=20,Max=32767), POOL: (Threads=7,QueuedItems=0,CompletedItems=139), v: 2.6.90.64945
```

- sentinel is not available - I am getting:

```
Sentinel: The ConnectionMultiplexer is not a Sentinel connection. Detected as: Standalone
at StackExchange.Redis.ConnectionMultiplexer.GetSentinelMasterConnection(ConfigurationOptions config, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs:line 166
   at StackExchange.Redis.ConnectionMultiplexer.SentinelPrimaryConnect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.Sentinel.cs:line 133
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 673
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 651
   at Nativesson.Api.Redis.RedisExtensions.CreateConnection(RedisOptions redisOptions) in C:\repos\Nextgen.Nativesson.Core\src\Nativesson.Api\Redis\RedisExtensions.cs:line 36
```

If I use non-sentinel mode: `localhost:26379,allowAdmin=true,abortConnect=false,tiebreaker=` and Redis is unavailable, then it does not throw during startup (it will throw an exception only if that redis connection is being used).
It creates a startup dependency between redis and the application. I want to avoid that.  
Is there a way to have the same behavior for sentinel mode and non-sentinel mode? Am I doing something wrong?

docker-compose.yaml:

```
version: '3.8'

services:
  redis-master:
    image: 'bitnami/redis:7.0.8'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]            
  redis-sentinel:
    image: 'bitnami/redis-sentinel:7.0.8'
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    ports:
      - '26379:26379'
    depends_on:
      redis-master:
        condition: service_healthy
```

**Comment by NickCraver** [comment]
I'm trying to understand your setup - you have Sentinel for a single server both in the same container? I might be missing something but: can you skip Sentinel altogether? It's not clear to me what "not available" means in your description of the scenarios - that can mean a lot of things. What does it mean here? The server is off? Firewall blocked? Port not exposed? Other?

I'm not sure how Sentinel behaves in the not-there-at-startup case honestly, it's not something we test a lot and it's something going away in the big picture with Redis overall (as of my last conversation with that group), so it's not something we add a lot more features or complexity for either. The general point of Sentinel is to be available (HA in itself with multiple members) and we're generally designed to connect to `1-n` of them for resiliency (generally, the goal is Sentinel is in use at all). So...I think this just hasn't come up, because you're in a very bad state already if the HA controllers are down as a baseline. There may be something we can do better here, really just streaming anything I think may be relevant for consideration here to provoke thoughts :)

**Comment by bukowskim** [comment]
Sorry, I have not been available for a couple of days.

The docker-compose file is only for local development purposes. In the production scenario, we have a fully-fledged cluster.
Not being available can mean a lot of things - e.g. transient connectivity issues, which may happen only for a short period of time. In my scenario, Redis/Sentinel is only used for caching, so I can imagine we should be able to recover when it is not available during startup. 

Despite the fact that Sentinel should be HA, still, I'm not too fond of the idea of introducing such dependency when my application doesn't need it. 
I was just wondering - why this is different for Sentinel? Is there a built-in way to achieve such behavior with the existing configuration? If not, then this is fine, I guess this can be achieved with the manual code around the library etc.

**Comment by NickCraver** [comment]
So overall, Sentinel is a totally different code path, because you're connecting to Sentinel _to get another connection_ and the child is what we hand back. Even if the child isn't online or connectable (for any reason, could be down, could be firewall), we can retry that and keep going. But in the Sentinel case we need to figure out what that second connection is even going to (the endpoint) to return it for an app to use when it's up. That's another step away and why we don't really support this scenario.

If you want to connect to Sentinel manually and retry beneath that's totally doable, but that's a complex promise structure to put in the core connection logic of the library, so something we're very unlikely to support natively.

**Comment by NickCraver** [comment]
Closing out to tidy up!
