### ISSUE TITLE
ServerSnapshot never removes a node

### ISSUE THREAD

**Issue by VladimirKhil** [StackExchange/StackExchange.Redis#2417]
It seems that after calling ConnectionMultiplexer.ReconfigureAsync() only new server nodes could be discovered and added to ServerSnapshot list but old ones are never removed.
We have a situation when Redis Cluster nodes got new IP addresses after rescheduling in Kubernetes cluster. They are successfully discovered by client but old phantom IPs stay in server list.
Is there a way to detect such non-responsive IPs and remove corresponding servers from the snapshot? Or is ForceReconnect approach the recommended way of handling this situation?

**Comment by mgravell** [comment]
This crosses over with the discussion on #2383; in theory yes this is something we can consider - however, we need to be *really* careful not to detach endpoints until we're absolutely sure that they don't have anything outstanding on them; so *if/when* we look at this, we need to figure out a stop-drain mechanism - or at least make sure that we mark the bridges as doomed (preventing new messages being sent, including heartbeat pings), optionally giving them some amount of time to *indicate* that they've emptied (if not already), before finally telling them to cull themselves - and *then and only then* can we remove them from the snapshot. Otherwise we could end up with consumer-facing tasks that never complete, which is: very bad.

So yes, in principle this is something we can do, but we need to be very careful; and in addition to ^^^, we need to be mindful of figuring out the "what do we keep?" logic.

**Comment by VladimirKhil** [comment]
Thank you very much for the response! Ok, we will rely on some own mechanisms for now like observing endpoint's IsConnected property, keeping an internal list of healthy endpoints that have not throw any exceptions during communication or trying to have static IPs for cluster nodes. The Multiplexer recreation approach seems to be a painful operation.

**Comment by mgravell** [comment]
It shouldn't be *that* painful - just: creating multiplexers isn't something you want to do *constantly*, for example on a per-request basis in a web-server. You presumably don't move nodes around *constantly* - so IMO responding to some broadcast "we changed the world" event, or periodically checking the current node state against a prior snapshot: should be fine, i.e. creating and swapping the multiplexer *when appropriate*: should be absolutely fine.
