### ISSUE TITLE
Getting many keys - Question regarding approach 

### ISSUE THREAD

**Issue by pianoman4873** [StackExchange/StackExchange.Redis#2419]
The Task<RedisValue[]> StringGetAsync(RedisKey[] keys, CommandFlags flags = CommandFlags.None) method throws an exception when the keys involved are destined to different nodes in Redis cluster.
Considering that the Redis client uses multiplexing and pipelining, do you think it would be still beneficial to group the keys based on nodes and make several calls to   StringGetAsync(RedisKey[] keys) with each call containing keys destined to a specific node, instead of just making much more calls to StringGetAsync(RedisKey[] keys)  ( sending them one after the other in batches and then awaiting all tasks to complete )?

If so , would you still batch the amount of keys sent in (RedisKey[] keys) for each node ?
Meaning , if I have a 100,000 keys  destined to some node , would you send them all in one call or batch them in smaller chunks ( and if so, how would you decide on the chunk size ) ?

Thanks

**Comment by mgravell** [comment]
Firstly, it isn't per-node; it is per-slot. This is enforced at the server (although there is an oddity where current azure redis cache servers allow multi-slot/single-node fetches, this oddity is planned to be removed, so: don't rely on it).

As for the rest: I would try it. Does a simple per-key get perform well for you? Great, do that. Otherwise, indeed group by slot (there's an API to compute the slot per key), and batch. As for the batch size; try it! I'd start with 128, 512 and 1024 - and measure.

**Comment by pianoman4873** [comment]
Thanks Marc, 
You mean the exception in the client would be thrown if the keys aren't destined to the same slot ?

**Comment by mgravell** [comment]
I believe so yes, precisely because it will also be thrown by the server
(in a cluster environment).

**Comment by NickCraver** [comment]
Closing out to tidy up!
