### ISSUE TITLE
Async extensibility point needed on ConfigurationOptions

### ISSUE THREAD

**Issue by philon-msft** [StackExchange/StackExchange.Redis#2434]
We're building a new SE.Redis extension that needs to make an async call to acquire a token to initialize ConfigurationOptions.Password. To avoid sync-over-async, we'd like this to happen in a fully async code path. Currently there is only a sync version of `ConfigurationOptions.Apply()` that takes a sync-only `Action<>` to customize ConfigurationOptions.

I believe we'd need to add an `ApplyAsync()` like this in ConfigurationOptions that takes a `Func<ConfigurationOptions, Task> configure` param rather than `Action<ConfigurationOptions>`: 

```cs
public async ValueTask<ConfigurationOptions> ApplyAsync(Func<ConfigurationOptions, Task> configure)
{
    if (configure != null)
    {
        await configure.Invoke(this);
    }

    return this;
}
```

And we'd need a complementary `ConnectAsync()` override in ConnectionMultiplexer like: 

```cs
public static async ConnectionMultiplexer ConnectAsync(string configuration, Func<ConfigurationOptions, Task> configure, TextWriter? log = null) =>
    ConnectAsync(await ConfigurationOptions.Parse(configuration).ApplyAsync(configure), log);
```

I haven't created a PR because this has some tricky implications to the API and compatibility.

**Comment by NickCraver** [comment]
Let's definitely chat on this one (sorry about spring break timing, missed call today!). IMO, it's not a great path to add these overloads because it would add a lot of cardinality to existing methods. The things I'm thinking about here are:
- `.ApplyAsync()` can be an extension method today (doesn't even need to be in lib)
- I don't think this needs another `.ConnectAsync()` overload, because a user could do: `.ConnectAsync(await ConfigurationOptions.Parse(confguration).ApplyAsync(...))`, or have the `await` be before, either way.
- If the _initial_ connection requires async fetch, what in the configuration options is async? And why wouldn't that be async for future fetched doing the same activity? That seems to be unhandled by this approach.
- A _lot_ of people use `.Connect()` that I've seen, even in mostly async paths, due to `Lazy<ConnectionMultiplexer>` especially - what is their expected path?

I totally get at least some use cases (e.g. token fetch), but I don't think applying an async overload in this niche area may be the right approach (where we've avoided other overloads like `ILogger`, etc. due to cardinality of these methods as well). IMO, extending .Connect/.ConnectAsync() with more overloads isn't a good solution, and we end up with crazy combinations and hard to maintain APIs (especially with optional args)...I think we need to find a workable method that both covers async well (as possible) and strays away from that particular approach. `.Apply()` itself was entirely designed to side-step this problem :)
