### ISSUE TITLE
KeyTimeToLiveAsync Returns null value for -1 TTL and key not found

### ISSUE THREAD

**Issue by JosephConroy93** [StackExchange/StackExchange.Redis#2438]
Hi, 

We have an issue when calling the KeyTimeToLive & KeyTimeToLiveAsync functions in the library.
When a record in our REDIS has a TTL (which isn't -1) the TTL TimeSpan value is returned correctly,
however when we pass a Key of a record which has TTL of -1 we get null returned.
Similarly when we pass in a Key which is not valid, then we also get null.

Referring to REDIS documentation (& the REDIS console on our server) when executing these queries, we receive the values;
![image](https://user-images.githubusercontent.com/111498620/233572853-fdb3818b-800f-4f73-94cb-1b13dd4167a4.png).

I would expect to receive these same values using the above function? 
we are using StackExchange.Redis v2.6.104. Redis Version: 6.0.14, NET 7.0 Target Framework

Any advise/support would be greatly appreciated. Thanks.
https://redis.io/commands/ttl/

**Comment by mgravell** [comment]
There's two things in play here; firstly, **the server API changed** - before 2.8, it would return `-1` in both those scenarios, hence that is what the API was designed around. Secondly, because we're parsing the TTL and expressing it as a `TimeSpan`, we can't give you exactly that API - and it would break existing code.

What you ask for is reasonable, but IMO we would need to create a new API that expresses the additional possible outcomes separately. I'm not sure that returning a negative `TimeSpan` is clear, so IMO we'd need to return some kind of simple struct that encompasses everything; perhaps:

``` c#
public readonly struct KeyLifetime
{
    private const long NoKey = -2, NoExpiry = -1;
    private readonly long _milliseconds;
    internal KeyLifetime(long milliseconds) => _milliseconds = milliseconds;
    public bool KeyExists => _milliseconds != NoKey;
    public bool HasExpiry => _milliseconds >= 0;
    public TimeSpan? Value => _milliseconds < 0 ? default : new(TimeSpan.FromMilliseconds(_milliseconds));
}
```

Thoughts?

---

Note: *today*, you could use `var ttl = (int) db.Execute("TTL", key);`

**Comment by JosephConroy93** [comment]
Thanks for the quick support mgravell ! this is sufficient for our requirements. 
So just to confirm, the Execute() function essentially is the same as using the console in REDIS, with the standard output as the return value?

**Comment by JosephConroy93** [comment]
db.Execute() function is sufficient workaround for this ! closing issue

**Comment by mgravell** [comment]
yes; `Execute` issues ad-hoc commands manually; the API is not quiet the same as the CLI - each argument is passed *separately* (rather than one string), and if you have keys you should ideally send them as `RedisKey`, not `string` (this is so that routing works correctly if you're using cluster or similar)
