### ISSUE TITLE
Are transactions from different clients being processed in the correct order?

### ISSUE THREAD

**Issue by wist214** [StackExchange/StackExchange.Redis#2509]
Hello everyone!

Context:
I'm running multiple VMs each connecting to the same Redis server and according to the documentation Redis uses one thread to process all requests. 
So my expectation is that if one VM puts some value into the cache and then (in my case after 7ms) another VM tries to get that value, all operations will be performed sequentially, and the second VM will get the updated value, but as it turns out, this is wrong. 
In my case, the second VM get the old value.

Question:
Does anyone know why this is happening, and how can I get Redis to process all transactions in the correct order?

**Comment by mgravell** [comment]
This isn't really a client library question, but: in the scenario you describe, everything should work in the expected way; the redis server core is indeed single threaded, so we should expect that a GET that follows a SET (or other mutating operation) will see the correct (most recent) value. There isn't enough data here to discuss this, though; for example:

- what makes you think that the GET and SET arrived in the expected order, if they are independent nodes?
- did you have a MONITOR running to see what happened?
- is the GET talking to the primary? or a replica? if it is taking to a replica: there will be replication delays
- does your application have any kind of in-process caching that means it never actually issued the GET?

**Comment by mgravell** [comment]
well, if we're talking only 7ms, I'd be thinking "is the log accurate? did clock drift or latency impact the logs?" - because *unless something very weird is happening*, if the GET got issued to the server: the server would have responded with the up-to-date value

(I might also permit weirdness if this is a "cluster" scenario *and* there was an active slot migration going on at the time, or if it is a hosted instance and the host did something weird like move the nodes)

but: is there anything client-library related in here? because we can't really speak for the server; we're not the server folks

**Comment by wist214** [comment]
It isn't "cluster" scenario, I think the log error is unlikely, but I will try to consider this possibility. 
Thank you for your feedback, It doesn't look like a client-library related issue, I'll try to reproduce the problem to be sure, but for now the issue can be closed.
