### ISSUE TITLE
Does StackExchange.Redis retries on cluster commands?

### ISSUE THREAD

**Issue by javedsha** [StackExchange/StackExchange.Redis#2556]
Hello,

Does the library retries on cluster commands like meet, nodes, set slot etc. in case of time out and connection failure? Looking at configuration, the only option I can see is the BacklogPolicy which by default will try to queue in case of connection failure unless the timeout for operation has reached.

Questions:

1. The async timeout is applicable to all commands (async) including cluster commands, right?
2. Is there any other way to specify number of retries? Or application should use libraries like Proxy and retry themselves.

Note: Our application is focus on cluster operations & management, and not the get/set operations.

Thanks.

**Comment by NickCraver** [comment]
We do not retry internally (because no single solution works for all, or takes into account pipelining). My standing suggestion is to use Polly or something similar here to retry as desired.

Note that when an exception is thrown in the case we've already sent the command (the message status is on the exception), we don't know if it was dropped _on the way there_ or the response was dropped _on the way back_, that's just the nature of being a client on a roundtrip that sent but never got a result. Take that information into account when deciding whether you want to retry something!

**Comment by javedsha** [comment]
Thanks @NickCraver , this helps.
