### ISSUE TITLE
Multiple Connections waiting in FIN_WAIT_2 State after OS Upgrade

### ISSUE THREAD

**Issue by ajnavsun1806** [StackExchange/StackExchange.Redis#2611]
Hi,

We are facing this unique issue after NET6 migration. After every OS Upgrade, there are multiple ports which are stuck in FIN_WAIT_2 state at 6380 port. Because of which the Redis connection starts failing.
![image](https://github.com/StackExchange/StackExchange.Redis/assets/37746359/f64b7b6c-a5d1-4ee6-bd63-0e0aed20c884)

Please let me know if you need more information. Kindly help as we are unable to root cause this issue. 
We are using Microsoft.Extensions.Caching.StackExchangeRedis version 6.0.25

Best Regards,
Ankit

**Comment by NickCraver** [comment]
This looks like a `ConnectionMultiplexer` is being created _a lot_, and not around for a long-lifetime (as is the intended design). Doing this will open a socket each time, so you hit ephemeral port exhaustion due to sockets in this state.

Ultimately, I'd look at where/how you're creating multiplexers, e.g. per request instead of per application or something to that effect.

**Comment by NickCraver** [comment]
Closing out to tidy up - advice above on next steps :)
