### ISSUE TITLE
Experiencing frequent StackExchange.Redis.RedisTimeoutException:  Timeout performing EVAL (5000ms)

### ISSUE THREAD

**Issue by NayanMansinha1** [StackExchange/StackExchange.Redis#2614]
Need help to understand what is causing these timeouts. Is this due to high sync-ops? If so, how to identify what is causing such high number? thanks.

 StackExchange.Redis.RedisTimeoutException: 
Timeout performing EVAL (5000ms), 
inst: 0, 
qu: 13, 
qs: 0, 
aw: False, 
bw: Activating, 
rs: ReadAsync, 
ws: Idle, 
in: 0, 
in-pipe: 0, 
out-pipe: 0, 
last-in: 0, 
cur-in: 0, 
sync-ops: 5515828, 
async-ops: 0, 
serverEndpoint: *****, 
conn-sec: 71567.81, 
aoc: 0, 
mc: 1/1/0, 
mgr: 10 of 10 available, 
clientName: *****(SE.Redis-v2.6.116.40240), 
IOCP: (Busy=1,Free=999,Min=200,Max=1000), 
WORKER: (Busy=57,Free=32710,Min=200,Max=32767), 
v: 2.6.116.40240

**Comment by NickCraver** [comment]
That error indicates you're possibly hitting thread pool starvation, from using synchronous calls instead of async. You'll want to use async as much as possible so that code waiting on a response from Redis for relatively long durations is not occupying a thread while doing so, exhausting the pool.

But also: that's a LUA script, which may be running too long - it's worth looking at what that's doing and how long it takes if a heavy script.
