### ISSUE TITLE
Invalid Zero Length check expression

### ISSUE THREAD

**Issue by MikeAlhayek** [StackExchange/StackExchange.Redis#2764]
I noticed many invalid expression when checking for a zero elements in a collection.

Here is explanation

```
List<string> items = null;

if(items?.Count == 0)
{
    // This will evaluate false since null does not equals 0.
}

if(items?.Any() ==false)
{
    // This will evaluate false since items is null. which is translated to items != null && items.Count == 1
}
if(items == null || items.Count == 0)
{
    // This will evaluate true since items either null OR is not null and it's count is 0.
}

if(items?.Count > 0)
{
    // This check is okay because null items will return false and if the Count is 0 will also false.
}
```

**Comment by mgravell** [comment]
Firstly, most of the scenarios described in the PR (#2765) are collections - they are strings.

Whether or not this is incorrect depends on what the expected semantics are; `prefix?.Length == 0` propagates the `null`, which means that `null` inputs will evaluate here as `false`, which means it is semantically akin to `prefix is not null && prefix.Length == 0`. Again: that is *neither right nor wrong*; what matters is the intent. Your changes in #2765 change that significantly, making it `prefix is null || prefix.Length == 0`. Again, also neither right nor wrong by itself.

If you're saying there is an *error*, the first thing to do here is to describe a scenario where the wrong thing happens, ideally in the form of a test, where that test is then fixed by the proposed change. There are no tests in the PR, and no target scenarios described.

I am happy to consider this **if and when a specific scenario is described**, but I don't think we should change this simply "because".

**Comment by mgravell** [comment]
Closing this; it appears to be part of a bulk creation of similar PRs on the assumption that `?.Length == 0` is automatically incorrect.
