### ISSUE TITLE
ISubscriber.SubscribeAsync usability issue

### ISSUE THREAD

**Issue by niemyjski** [StackExchange/StackExchange.Redis#281]
It doesn't make any sense for SubscribeAsync to return a task. It doesn't do anything.. Every other message bus implementation that I've used allows you to pass a Func<Message, CancellationToken, Task>  (or some combination of func) as a parameter so the internal message loop / handler can await the task. I found this while trying trying to use the async version on https://github.com/exceptionless/Foundatio

On a side note, this library rocks.

**Comment by NickCraver** [comment]
It makes sense if you need to ensure you are subscribed before taking further action. There are many scenarios in which you can miss messages because you aren't rigged to the loop as you thought. For example when an application starts up it may switch from a polling mechanism to get started (let's say: reading settings) to event-based after that. I can't remove the polling model until I know I'm getting deltas - so I'd await the subscription finishing.

**Comment by NickCraver** [comment]
@niemyjski I should add here: the reason you want to return a `Task` in general is for the await, so the state machine properly handles exception flow and such. Unless you have a *very* narrow case for which `void` async methods are allowed at all (event handlers mostly), returning `void` from an `async` with invariably cause problems.

I'll go ahead and close this out to clean up, but happy to discuss further if curious!

**Comment by niemyjski** [comment]
Yeah I get why you want to return a task/state machine. But I just don't understand why we can't pass a Task Func to Subscribe and that sets it as a backing field. Then that is awaited later when subscribers are initiated or used for the first time.

**Comment by niemyjski** [comment]
So I guess having an async function here would slow down the message loop at least in the current design. Have you put any more thought into this? I was wondering if ConfigureAwait(false).GetAwaiter().GetResult() recent change could be causing additional timeouts / threads to get deadlocked on .net core
