### ISSUE TITLE
Does StackExchange.Redis support TransactionScope?

### ISSUE THREAD

**Issue by lauthu** [StackExchange/StackExchange.Redis#313]
Hi all, can I operate Redis directly in TransactionScope?

**Comment by mgravell** [comment]
No. The redis transaction model isn't really suitable for that:

- there isn't really a rollback as such (there is a "don't do the stuff I've told you to queue")
- it would depend on blocking the connection waiting on external resources, which is anathema to a shared (multiplexed) connection
- it is a lot of work, that doesn't seem necessary

There is no plan to attempt to emulate this scenario, since it isn't a natural fit

**Comment by lauthu** [comment]
@mgravell Thank you for replying~ I'm junior on Redis. If there any best practice on transactional issues handling?

 for example, if I use Redis as a cache for Sql Server, how to make sure data on RDB and Redis both updated correctly?

**Comment by mgravell** [comment]
That depends an awful lot on what "correctly" means to you, especially in
the context of a cache; a lot of people treat cache as volatile and
non-critical, so have persistence (RDB) completely disabled. And there are
a myriad of approaches you could use for populating it (and invalidating
it), including basic timeouts, explicit purges, and pub/sub.

On 7 December 2015 at 06:32, LiuXinyu <notifications@github.com> wrote:

> @mgravell <https://github.com/mgravell> Thank you for replying~ I'm
> junior on Redis. If there any best practice on transactional issues
> handling?
>
> for example, if I use Redis as a cache for Sql Server, how to make sure
> data on RDB and Redis both updated correctly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/313#issuecomment-162424470>
> .
>



-- 
Regards,

Marc

**Comment by lauthu** [comment]
@mgravell  Thank you very much.☺
