### ISSUE TITLE
While running on localhost frequently getting StackExchange.Redis.RedisServerException

### ISSUE THREAD

**Issue by manjitsiwach** [StackExchange/StackExchange.Redis#318]
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> StackExchange.Redis.RedisServerException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

Plz help.
Thanks

**Comment by NickCraver** [comment]
This happens when your `redis.conf` (this is the common name but can be called anything - see what you launched it with) specifies that you want to save snapshots. In your case it's likely the config is either aimed at a directory that doesn't exist, or the process isn't running with credentials with permissions to actually save there.
