### ISSUE TITLE
How To store reference type object (or List) in redis Cache

### ISSUE THREAD

**Issue by KamranShahid** [StackExchange/StackExchange.Redis#325]
Is there any possibility that i can to store reference type object (or List) in redis Cache (without using further extension)

**Comment by mgravell** [comment]
Since you mention lists (which rules out hashes), the thing that leaps to
mind here is serialization. SE.Redis very deliberately does not express any
opinion on serialzsation choices, but ultimately you can use any serializer
you like, as long as it can generate (in some way) either a byte[] or a
string - and a serializer that can do neither is a poor serializer! Many
people like JSON, but I generally use protobuf (via protobuf-net) to
squeeze out the last few drops of efficiency. You could, for example, write
an extension method that adds a helper method onto any of the SE.Redis APIs

**Comment by KamranShahid** [comment]
Thanks Mark.
I think you have also tried to answer my question at http://stackoverflow.com/questions/34513341/api-for-save-select-list-of-reference-type-into-redis

**Comment by NickCraver** [comment]
@KamranShahid Are you all set now? If so I'll close this out.

**Comment by KamranShahid** [comment]
Sure Nick
