### ISSUE TITLE
ConnectionMultiplexer.Connect  consume too much CPU

### ISSUE THREAD

**Issue by shzy2012** [StackExchange/StackExchange.Redis#405]
Here my Code

        ///Redis 连接配置
        private static Lazy<ConfigurationOptions> configOptions2 = new Lazy<ConfigurationOptions>(() => {
            var configOptions = new ConfigurationOptions();
            configOptions.EndPoints.Add("10.0.11.236:6379");
            configOptions.ClientName = "Connection";
            configOptions.ConnectTimeout = 100000; //100S
            configOptions.SyncTimeout = 100000;
            return configOptions;
        });

/// Call 
for (int i = 0; i < 10000; i++) {
                IDatabase tmpDb = ConnectionMultiplexer.Connect(configOptions2.Value).GetDatabase(5);
                Console.WriteLine(i);
 }

---------------------------------------------------------------------------------------

![redis](https://cloud.githubusercontent.com/assets/3347060/15238873/e63318f4-190f-11e6-96dd-2712a28d5c8c.png)

I don't Know  why?

r

**Comment by mgravell** [comment]
Establishing a connection is non-trivial; I don't know why you are creating 10,000 of them in a loop, but you *totally shouldn't do that* - heck, even the OS is going to struggle spinning up that many sockets in a tight loop. The idea here is that you establish a connection *once*, and share it between multiple calls (i.e. for the duration of an app, or at least until the socket dies a death, as sockets sometimes do). If you are connecting for every call, then frankly you're doing it wrong. See https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/PipelinesMultiplexers.md

**Comment by shzy2012** [comment]
> creating 10,000 of them in a loop
test connect to redis 

So Thank for you answer

**Comment by mgravell** [comment]
Again, I cannot emphasize what a bad idea that is. I don't think you are testing what you think you are testing. Testing something in a way it is neither expected nor designed to be used *is not useful*, and I'm not going to waste any of my time trying to make a silly thing work. This is like saying "when I sit idle on the driveway and rev my car fully - pedal to the metal - it starts getting smokey and the engine is making a funny noise". The "fix" to this is **not** to change the car so that it can withstand that; it is to *stop doing that*.

You should never ever need to create redis connections at this rate. If you are doing this: *you are doing it wrong*.
