### ISSUE TITLE
Need Help for reading the entire keys along with its values from redis 

### ISSUE THREAD

**Issue by abhit011** [StackExchange/StackExchange.Redis#409]
I have saved the 50 K keys in Redis Cache (Using redis  for Cache only purpose...) .
I have created 20 Threads to do the entire savings part and now in reading part , please let me know is that the correct way to do it

```c#
void letsNowReadFromCache(){
    var seq = server.Keys(pattern: "*", pageSize: pageSizeForTesting);
    long cacheCursor = 0;
    int cahceOffset = 0, cachePageSize = 0;
    IEnumerator<RedisKey>iter = seq.GetEnumerator();
    
    while (iter.MoveNext())
    {
        Console.WriteLine("count" + j++);     

        totalSoFar++;
        if (totalSoFar >= countChecking)
            break;

         cacheCursor = ((IScanningCursor)seq).Cursor;
         cacheOffset = ((IScanningCursor)seq).PageOffset;
         cachePageSize = ((IScanningCursor)seq).PageSize;

         RedisKey key = iter.Current;
         String returnval = redis.StringGet(key);
         dumpIntoSomeWhere(returnval); 
    }
}
```

**Comment by abhit011** [comment]
Any pointers ?

**Comment by abhit011** [comment]
Where pageSizeForTesting is 100

**Comment by abhit011** [comment]
Also is there any parallel way of fetching such items, please let me know..

**Comment by NickCraver** [comment]
What is your goal here? To persist all of redis somewhere? The general answer to `keys` (which we translate into a scan on newer versions of redis) is "don't do that", because in there are generally better solutions to the problems people are trying to solve. For example, are you *just* trying to make a backup? If so, why not use the `.rdb` redis has built-in for persistence?

Context would help a lot here - can you describe a bit more what goals you're after?

**Comment by abhit011** [comment]
I am using redis 3.0.501 version, I opine in that, ""Key API"" translate into Scan only.  
As per lots the blog and other posts read, they say its better to use scan using pagesize:. and i used that only. 
Nick I am using redis only for cache only and no persistence at all.. My application is like fetching 100,000+ users profile info from the SQL at one time  (This operation happens only once during the start of my app), that''s why i am creating separate threads to read from SQL and then writing into Redis.cache. either uring HashSetAsync or StringSetAsyc.(Assuming that cache has been flushed or restarted)
.
After that periodically one of my application timing thread reads all the User keys along with its relevant values from the redis cache, <Code already written above> and then storing those redis cache retrieved values into threads internal data structures. Then using those internal data structure I do some kind of processing.... 
  
Note that Users information gets keep on changing , so that's why previously it used to read every time from SQL (and it was was a crime :P ), it just used to get stuck for quite a long to get those user info from SQL.. 
Hence I brought the Cache Layer in our backend, and indeed choose Redis after reading lots of posts :) 
Now in my web applicaiaton any change in users I first write that into cache and then into SQL.

**Comment by abhit011** [comment]
is this the correct way to find the no of keys in redis with a particular Key pattern ?
code 
 ```
long countChecking = server.Keys(pattern: this._userTypeEnum.ToString().ToLower()  +
                                                        ":" +
                                                        "*", pageSize: 1000).Count();
```

**Comment by abhit011** [comment]
Please any pointers .....

**Comment by abhit011** [comment]
Should it take close to 30 seconds ? Just to iterate through the redis keys with a pattern like 
this    var seq = server.Keys(pattern: "*", pageSize: pageSizeForTesting); 
I assumed that it should be lightening fast ? Please throw some light , if I am doing anything wrong in it 
Abhit

**Comment by NickCraver** [comment]
@abhit011 Apologies this got dropped - what you are doing was correct! We'll turn this into a scan under the covers if the server supports it. The duration will depend on the speed of the redis server, how busy it is, and the number of keys. If you have a replica/slave, we recommend running this operation against it instead of the master.

Note for anyone finding this later: it's still not cheap to do. It's an expensive operation to scan all of redis, scans just make each individual block not take so long, as to not stall out all other consumers.

**Comment by NickCraver** [comment]
Closing out to cleanup.
