### ISSUE TITLE
Add Overload to KeyExpire and KeyExpireAsync to take IEnumerable of Keys

### ISSUE THREAD

**Issue by aaronmell** [StackExchange/StackExchange.Redis#421]
Any technical reason why this can't be done?

**Comment by NickCraver** [comment]
What would the return type be? Since redis doesn't actually have an API like this, I'd hesitate to fake one here. You can call this in a loop, which is effectively what would happen if implemented in the library (presumably with an array allocation for the return). I'm just not sure the library is the best place for that function. I'd imagine the use case for `bool[] (IEnumerable<RedisKey> keys, DateTime? expiry, CommandFlags flags)` would be quite a low count. 

Do you have some examples of use cases here? That helps quite a bit. Is there a technical reason it *can't* be done? Nope! That's the beauty of software. But it's not *actually* a batch operation, it'd be the library faking one and not being atomic with a matching redis server operation here, that creates edge cases and more situations to handle. In such cases, decent justification and use cases to shape an API help a lot.

**Comment by aaronmell** [comment]
Just trying to reduce the network traffic on my end, I'm using a several sets in a method on my side and it would have been nice to reduce the number of calls by setting expiration on them all at once. I assumed that if the redis API supported passing a collection of keys to expire, it would have already been implemented, but I wanted to verify in case it had been overlooked.

**Comment by NickCraver** [comment]
Are you trying to reduce network traffic, or latency? What does your current code look like? If you're doing something like waiting on each operation in a loop now, we can definitely drastically reduce that with minor tweaks. Can you post a small section where the efficiency problem lies?

**Comment by aaronmell** [comment]
My code currently looks like 

SetAddAsync Set1
KetExpireAsync For Set1

SetAddAsync Set2
KeyExpireAsync For Set2

SetAddAsync Set3
KeyExpireAsync For Set3

SetAddAsync Set4
KeyExpireAsync For Set4

My sets are basically sliding expiration at this point, and used to contain useful groups of items.

**Comment by mgravell** [comment]
I could be wrong, but I didn't think there was a varadic overload at the
Redis end. If you are actually after reducing network, the main way to do
this here would be to use a Lua script or a module (the brand new stuff,
not yet exposed), but in reality I doubt that this is contributing to an
immediate bottleneck. If it is: Lua would be the first thing I tried.

If there is a varadic version of EXPIRE and PEXPIRE, I'm not hugely opposed
to extending the API. But if the server doesn't offer this, then id be more
reluctant.

**Comment by mgravell** [comment]
Upon checking, indeed, neither expire nor pexpire offer this functionality.
I'm not sure that it buys us anything to spoof it. Adding an enumerable
version would not do anything to change the network overhead.

**Comment by aaronmell** [comment]
Okay, Thanks!
