### ISSUE TITLE
please build a full net4.0 project

### ISSUE THREAD

**Issue by wolfben** [StackExchange/StackExchange.Redis#429]
in net4.0 eviroment，can not build it,please commit a full net4.0 project,thanks

**Comment by mgravell** [comment]
There is one in nuget. Does that one fail for you? Please be specific.

**Comment by wolfben** [comment]
Without the development of the network environment, so I can't use nuget, I can only reference manual, but in the process of library reference each other, always cannot compile would happen, may be some DLL component version of the problem, so I hope you can pack a complete NET4.0 projects;thank you

**Comment by ricardopieper** [comment]
You can clone the repo and build the StackExchange.Redis_Net40 project by yourself. It works fine for me.

**Comment by NickCraver** [comment]
Two options here: you can either download from NuGet via the Download link on [the NuGet package page](https://www.nuget.org/packages/StackExchange.Redis/) ([direct download link](https://www.nuget.org/api/v2/package/StackExchange.Redis/1.1.608)) and use the `net40` DLLs, or you can build from source.

Note: we will be dropping .NET 4.0 support in the v2 release of StackExchange.Redis, since it's become a big burden to support and will be even more so with the enhancements planned.

Closing this out to cleanup, but feel free to poke with more questions.
