### ISSUE TITLE
Web.config assemblyBinding gets modified for System.Net.Http

### ISSUE THREAD

**Issue by mfelicio** [StackExchange/StackExchange.Redis#44]
When adding a the nuget package to a WebAPI project or to a project referenced by the WebAPI project the System.Net.Http assemblyBinding gets changed to version 2.0.0.0. My project uses System.Net.Http 4.0.0.0 and every time I add the nuget package to any of the referenced proejcts the System.Net.Http gets changed, asp.net web app doesn't start and I have to manually revert the assemblyBinding.

All my projects are .NET 4.5.

Does this happen to anyone else?

**Comment by NickCraver** [comment]
@mfelicio What you were most likely hitting is when NuGet does an update of your `.config` files, it isn't updating this *for the package you're updating*, it's updating them *for all packages*, *every time*. That means if any previous binding failed to update (e.g. wasn't committed), you'll see it get modified on the next package update.

I'll close this out since not related to SE.Redis, but wanted to give context for anyone finding this later.
