### ISSUE TITLE
Cast to long throws exception

### ISSUE THREAD

**Issue by yue-shi** [StackExchange/StackExchange.Redis#447]
``` C#
public static explicit operator long(RedisValue value)
{
    var blob = value.valueBlob;
    if (blob == IntegerSentinel) return value.valueInt64;
    if (blob == null) return 0; // in redis, an arithmetic zero is kinda the same thing as not-exists (think "incr")
    long i64;
    if (TryParseInt64(blob, 0, blob.Length, out i64)) return i64;
    throw new InvalidCastException();
}
...
internal static bool TryParseInt64(byte[] value, int offset, int count, out long result)
{
    ...
    if (b < '0' || b > '9') return false;
    ...
}
```

This causes casting like `(long)0.002` to throws exception. I wonder what the rationale is behind this while the standard long casting returns 0 for this particular case.

**Comment by NickCraver** [comment]
This is an active choice since it's not *actually* a long. Rather than silently losing precision we're doing a strict enforcement here. Since this is heavy in I/O, you don't want to assume a user's data types, it's safer to error when something unexpected happens rather than silently passing along bad data.

If you *really* want a long here, you can of course cast to the *actual* type, then cast again to a `long`. But we don't want StackExchange.Redis to silently cause trouble here, so the behavior is intentional.
