### ISSUE TITLE
1.1.603 also have MOVED exception

### ISSUE THREAD

**Issue by doterme** [StackExchange/StackExchange.Redis#459]
i got StackExchange.Redis 1.1.603 from nuget,but in my cluster i also got MOVED exception，how can i solve this exception?

**Comment by yaronyudov** [comment]
@doterme This issue is the same as issue #179

**Comment by doterme** [comment]
@yaronyudov yes,but now i used 1.1.604-alpha,the MOVED exception not exists.

**Comment by gokhansengun** [comment]
I had the same issue and mine turned out to be networking issue, it may be yours too.

I am using a Redis cluster where the Redis nodes are inside the Docker containers. I also use Docker for Mac where I run the client. In Docker for Mac and Docker for Windows, there is no way to reach container over their IP. Network connectivity happens over forwarded ports on localhost.

Redis, with MOVED command tell the client to go to another node but client is unable to follow the address because it is inside Docker network hence the error.

**Comment by NickCraver** [comment]
Closing out to cleanup.
