### ISSUE TITLE
No connection is available to service this operation: KEYS

### ISSUE THREAD

**Issue by bobmanz** [StackExchange/StackExchange.Redis#515]
Hello,

I've opened up an issue over at StackExchange.Redis.Extensions, however, I think it requires some discussion over here since the exception is being thrown in the RedisServer.cs class.  Below is the link to that issue and discussion.

[https://github.com/imperugo/StackExchange.Redis.Extensions/issues/84](https://github.com/imperugo/StackExchange.Redis.Extensions/issues/84)

The fix could be in the extension class to only search keys on a server that 'IsConnected==true' or the method to retrieve servers should only return connected servers.

Thoughts?

**Comment by NickCraver** [comment]
Which SE.Redis version and Redis server version are in play here? I ask because recent versions of the library against server releases in the past few years wouldn't actually be attempting KEYS, we're hiding the ugly with scans underneath to not lock up the server.

Can you provide these details please?
