### ISSUE TITLE
This Redis command is not allowed from scripts

### ISSUE THREAD

**Issue by wxf8126275** [StackExchange/StackExchange.Redis#524]
执行的脚本为：return redis.call('SPOP',@key)

“StackExchange.Redis.RedisServerException”类型的异常在 StackExchange.Redis.dll 中发生，但未在用户代码中进行处理

其他信息: ERR Error running script (call to f_cb67b2f8bcdf2402b5331977dd0197dc8372725b): @user_script:1: @user_script: 1: This Redis command is not allowed from scripts

**Comment by mgravell** [comment]
This isn't a library error. This is redis itself rejecting the command.
Essentially this is due to replication. All script operations should be
deterministic so that the script execute command can be replicated, rather
than the side-effects being replicated. SPOP is non-deterministic, so
cannot be used. This is a topic for redis itself (not any library) if you
disagree with it.

**Comment by NickCraver** [comment]
Closing this out since it's not really a library issue, there's no action we can take here :-/

**Comment by mgravell** [comment]
Note: you might want luck if you add:

redis.replicate_commands()

At the top of your script. This changes the replication mode to effects
rather than scripts.

On 20 Nov 2016 11:28 pm, "Nick Craver" <notifications@github.com> wrote:

Closed #524
<https://github.com/StackExchange/StackExchange.Redis/issues/524>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/524#event-865764425>,
or mute the thread
