### ISSUE TITLE
StackExchange.Redis.RedisServerException: ERR Protocol error: expected '$', got '�'

### ISSUE THREAD

**Issue by Jflima92** [StackExchange/StackExchange.Redis#529]
Hi,

I'm getting this error a couple of times, and I can't manage to find where the problem is.
I know the Redis uses the RESP protocol and that the $ symbol should be the first byte of the reply.
Basically what I'm doing here is Object -> Base64String -> insert to redis using a lua script.
Has anyone had this issue before?

Thanks in advance.

**Comment by mgravell** [comment]
That's very odd and unusual. Is there anything atypical in your setup such
as an SSL proxy?

On 24 Nov 2016 6:26 p.m., "Jorge Lima" <notifications@github.com> wrote:

Hi,

I'm getting this error a couple of times, and I can't manage to find where
the problem is.
I know the Redis uses the RESP protocol and that the $ symbol should be the
first byte of the reply.
Basically what I'm doing here is Object -> Base64String -> insert to redis
as string.
Has anyone had this issue before?

Thanks in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/529>, or mute
the thread

**Comment by Jflima92** [comment]
Hi @mgravell,

No, I'm not using SSL proxy, but my redis client is connected to a remote linux machine, don't know if it helps. And thanks for the fast reply!

**Comment by NickCraver** [comment]
This looks like an encoding error, is it still happening?

**Comment by Jflima92** [comment]
Hi @NickCraver, fortunately we managed to overcome this issue, it's not happening anymore. It probably was an encoding issue due to bom being added to our UTF-8 encoded Lua files in visual studio. I'll close the issue. Thanks
