### ISSUE TITLE
Connection leak in multiplexer

### ISSUE THREAD

**Issue by ReimerA** [StackExchange/StackExchange.Redis#541]
Hi I know this is not the intended scenario to create new multiplexers and dispose of them again, but it seems this code is leaking connections to the Redis Server - I guess that is not intended either..?

using (var multiplexer = ConnectionMultiplexer.Connect("someConnectionString"))
{
	multiplexer.GetDatabase();
}

(using 1.1.608)

**Comment by mgravell** [comment]
What is the thing that makes you think it is leaking connections? What are
you observing?

**Comment by NickCraver** [comment]
If you are using and disposing the `ConnectionMultiplexer` rapidly, I'd imagine you're leaking ports at approximately the same rate, since the OS takes a while to close them by default (see: `TIME_WAIT`). The `ConnectionMultiplexer` is meant to be very long-lived a reused across the lifetime of the application. It handles reconnecting, etc.
