### ISSUE TITLE
Connection issue after some idle time with StackExchange.Redis

### ISSUE THREAD

**Issue by ratidzidziguri** [StackExchange/StackExchange.Redis#543]
I have latest version of this package installed and it works without any issues till application gois into standby period after which any attempts to connect to redis server fails with exception that it can not connect to the server. i tried to set 

> It was not possible to connect to the redis server(s); to create a disconnected multiplexer [...]

Application is ASP.net asmx web service and it has this instantiate in a private static variable so there is only single instance of this created. this blocks us from releasing this in production as connection issue brings all system down.

We tried to set AbortOnConnectFail to false but that did not make any changes and we are still facing this issue. the version we are currently using is 1.1.608

**Comment by NickCraver** [comment]
Sorry I didn't see this one at the time, these reconnect issues were fixed in the 1.2.x series, using the latest 1.2.6 should get anyone hitting this squared away. If it doesn't please open an issue with the full error message, it also contains additional debug information and guidance that helps is resolve these :)
