### ISSUE TITLE
SWAPDB?

### ISSUE THREAD

**Issue by checkhavoc** [StackExchange/StackExchange.Redis#551]
Is there a method that supports the ability to execute a "SWAPDB {db1} {db2}"?

**Comment by MattHoneycutt** [comment]
+1 

Did you ever find a way to do this with StackExchange.Redis?

**Comment by NickCraver** [comment]
This is indeed missing, added it to the commands list for the next pass.

**Comment by mgravell** [comment]
Implemented in 2.0, thanks

**Comment by igalnassi** [comment]
I have been trying to find documentation as to why SWAPDB is an admin-only function. Is it due to a performance concern or just that it is a dangerously overarching manipulation of the data (similar to renaming of a table in the relational-database terms)?

Just wondering as I would like to find a different way to do my business if there are any performance concerns.

Thanks a lot for all the good work!

**Comment by mgravell** [comment]
the latter; it isn't performance related

**Comment by igalnassi** [comment]
Thanks for the fast response!
