### ISSUE TITLE
Where are "Sets"?

### ISSUE THREAD

**Issue by nemanjapetrovic** [StackExchange/StackExchange.Redis#553]
From the following [link ](https://redis.io/commands/sadd) we can see that Redis has SETS as a data structure. 

I have trouble finding a function that will store/get/update/remove SETS values?

**Comment by pasteusernamehere** [comment]
All the set operations are part of the StackExchange.Redis.IDatabase interface. Each method is prefixed with 'Set'. I.e. SetAdd, SetCombine, SetCombineAndStore, SetRemove....

You will also find similar signatures for SortedSet.

Async signatures can be found in StackExchange.Redis.IDatabaseAsync.

Load the Nuget package, the Intellisense documents each method fairly well.

**Comment by mgravell** [comment]
Nods gratefully at @pasteusernamehere

On 17 Jan 2017 4:46 p.m., "pasteusernamehere" <notifications@github.com>
wrote:

All the set operations are part of the StackExchange.Redis.IDatabase
interface. Each method is prefixed with 'Set'. I.e. SetAdd, SetCombine,
SetCombineAndStore, SetRemove....

You will also find similar signatures for SortedSet.

Async signatures can be found in StackExchange.Redis.IDatabaseAsync.

Load the Nuget package, the Intellisense documents each method fairly well.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/553#issuecomment-273225465>,
or mute the thread

**Comment by nemanjapetrovic** [comment]
Thank you, I was looking for "SMEMBERS" command. I found it, "SetMembers" is the name of the method. Was expecting name like "Get...." not the "Set...".

**Comment by NickCraver** [comment]
Closing out to cleanup :)
