### ISSUE TITLE
[Question] Why SE.Redis is no longer using RunContinuationsAsynchronously for asynchronous continuations

### ISSUE THREAD

**Issue by IlyaGrebnov** [StackExchange/StackExchange.Redis#558]
Marc/Nick,

For personal education :) What is technical reason for SE.Redis to use ThreadPool.QueueUserWorkItem instead of RunContinuationsAsynchronously for asynchronous continuations?

**Comment by NickCraver** [comment]
I wish I could coherently answer this, unfortunately part of the answer is *we don't know*. Enabling them solved some edge cases, but also caused all sorts of totally inexplicable task behavior due to deep implementations in the runtime across various scenarios. It got to the point we rolled it back, basically doing more harm than good. Some deadlock situations were the most apparent. For example: #401 and #434.

**Comment by NickCraver** [comment]
Closing this out, since we don't actually have a better answer, unfortunately.
