### ISSUE TITLE
SETNX missing?

### ISSUE THREAD

**Issue by llint** [StackExchange/StackExchange.Redis#561]
It seems that the Redis command `SETNX` is missing from the current StackExchange.Redis `IDatabase` API (1.2.0), any plan to add it in the near future?

**Comment by llint** [comment]
I found out that IDatabase.StringSet has a When flag, which I can specify the condition, so SETNX should be expressed with StringSet(..., When.NotExist, ...)

**Comment by mgravell** [comment]
correct, the When flag determines which variant is used.

On 26 Jan 2017 10:43 p.m., "llint" <notifications@github.com> wrote:

Closed #561
<https://github.com/StackExchange/StackExchange.Redis/issues/561>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/561#event-938573959>,
or mute the thread
