### ISSUE TITLE
Redis Timeout

### ISSUE THREAD

**Issue by guy-algomizer** [StackExchange/StackExchange.Redis#562]
Hi,
can some one tell the meaning of this and what we can do

 mgr: ExecuteSelect, err: never, queue: 783, qu: 0, qs: 783, qc: 0, wr: 0, wq: 0, in: 2920, ar: 0, clientName: TEST-ALL, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), Local-CPU: unavailable 

We are using aws elasticache with redis

**Comment by mgravell** [comment]
the meaning of that is "there's work sent (qs); the server has replied with
something (in), but for some reason there is no active reader (ar)". Can
you indicate what runtime version and OS you are using, and what library
version?

On 26 Jan 2017 11:29 p.m., "guy-algomizer" <notifications@github.com> wrote:

Hi,
can some one tell the meaning of this and what we can do

mgr: ExecuteSelect, err: never, queue: 783, qu: 0, qs: 783, qc: 0, wr: 0,
wq: 0, in: 2920, ar: 0, clientName: TEST-ALL, IOCP:
(Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767),
Local-CPU: unavailable

We are using aws elasticache with redis

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/562>, or mute
the thread

**Comment by zhangpeng-kooboo** [comment]
@mgravell we saw the similar error sometimes.

Timeout performing GET Settings:settingName-contentBlocksSetting, inst: 8, queue: 6, qu: 0, qs: 6, qc: 0, wr: 0, wq: 0, in: 57105, ar: 0, clientName: RD00155D58AA6F (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)

I am using "StackExchange.Redis": "1.1.608" in Azure WebApp .NET Core 1.0.

**Comment by cleverguy25** [comment]
Seeing the same thing.  [#599](https://github.com/StackExchange/StackExchange.Redis/issues/599).  Also ASP.Net Core, but in our case running on Linux in ECS container.

**Comment by GomesNayagam** [comment]
I am facing the same issue, LINUX 16.04 DOTNET CORE 1.1.1 redisclient 1.2.4
An exception of type 'StackExchange.Redis.RedisTimeoutException' occurred in StackExchange.Redis.dll but was not handled in user code

Additional information: Timeout performing GET dummy:dummy:F4C9385F1902F7334B00B9B4ECD164DE, inst: 1, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: LUS-CND7211PKH, serverEndpoint: Unspecified/sjc04s1ssccs01.teslamotors.com:6379, keyHashSlot: 5206, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by niemyjski** [comment]
Were you able to resolve this issue?

**Comment by GomesNayagam** [comment]
i dint do anything, server side i reported and kight have solved

**Comment by niemyjski** [comment]
Can you please clarify, that doesn't make any sense.

**Comment by GomesNayagam** [comment]
which version are u using, i am using 1.2.6, and  did not receive the problem recently, if happens i will update, i am also using pool in client side.

**Comment by isolimani** [comment]
Hi All,

Were you able to resolve the issue ? I am getting a same error. 


Error in ConnectionMultiplexer class in ExecuteSyncImpl Function.
 Error Message: Timeout performing GET key  inst: 2, mgr: ExecuteSelect, err: never, queue: 8, qu: 0, qs: 8, qc: 0, wr: 0, wq: 0, in: 556, ar: 0, clientName: WIN-L8P1AVQI124, serverEndpoint: Unspecified/ws-cache.3rpbnm.ng.0001.use1.cache.amazonaws.com:6379, keyHashSlot: 5886, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=10,Free=32757,Min=8,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)



I tried to decrease the timeout in elasticcache but still got the errors only in peak hours.

Do you think enable the cluster in elasticcache will help ?


Thanks

**Comment by NickCraver** [comment]
@isolimani You're seeing a timeout to redis there - what are your timeout setting set to? If the machines are overwhelmed at peak, you may simply need to up the timeout values. I'm going to close this out to consolidate timeout issue and since the original was resolved. We're going to attack networking the most next.
