### ISSUE TITLE
ConnectionMultiplexer.Connect throws exception

### ISSUE THREAD

**Issue by visooof** [StackExchange/StackExchange.Redis#564]
Hi guys,

using netstandard 1.6.1 and stack exchange 1.2.0

On ConnectionMultiplexer.Connect I get an exception

Could not load file or assembly 'System.Runtime.InteropServices, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Any idea how to fix this?

**Comment by visooof** [comment]
So I managed to bypass this one and now I am getting the error

One or more errors occurred. (The attempted operation is not supported for the type of object referenced)

with stack trace

   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log)
   at StackExchange.Redis.PhysicalConnection.BeginConnect(TextWriter log)
   at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log)
   at StackExchange.Redis.ServerEndPoint..ctor(ConnectionMultiplexer multiplexer, EndPoint endpoint, TextWriter log)
   at StackExchange.Redis.ConnectionMultiplexer.<ReconfigureAsync>d__115.MoveNext()

my connection string looks like 

servername.redis.cache.windows.net:6380,password=password,ssl=True,abortConnect=False

Any ideas why am I getting this socket exception?

**Comment by mgravell** [comment]
The first one is very odd - what did you do to get past it?

On 28 Jan 2017 10:06 p.m., "visooof" <notifications@github.com> wrote:

Hi guys,

using netstandard 1.6.1 and stack exchange 1.2.0

On ConnectionMultiplexer.Connect I get an exception

Could not load file or assembly 'System.Runtime.InteropServices,
Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The
located assembly's manifest definition does not match the assembly
reference. (Exception from HRESULT: 0x80131040)

Any idea how to fix this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/564>, or mute
the thread

**Comment by mgravell** [comment]
the second on looks like the fast path tweak; I'll check the exception
handling. What OS are you running on, so I can compare?

On 30 Jan 2017 1:00 a.m., "Marc Gravell" <marc.gravell@gmail.com> wrote:

The first one is very odd - what did you do to get past it?


On 28 Jan 2017 10:06 p.m., "visooof" <notifications@github.com> wrote:

Hi guys,

using netstandard 1.6.1 and stack exchange 1.2.0

On ConnectionMultiplexer.Connect I get an exception

Could not load file or assembly 'System.Runtime.InteropServices,
Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The
located assembly's manifest definition does not match the assembly
reference. (Exception from HRESULT: 0x80131040)

Any idea how to fix this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/564>, or mute
the thread

**Comment by visooof** [comment]
1st one i was building/packaging against netstandard 1.5, changed to .netcore 1.1 and it solved itself
2nd one. I am running on Win 7 professional 64 bit.

**Comment by visooof** [comment]
I don't think it is a Redis issue,

here

https://github.com/StackExchange/StackExchange.Redis/issues/463

people having absolute same issue and as a workaround they say compile with some MONGODB driver or something, no idea how to do this on .netcore 1.1...

**Comment by visooof** [comment]
BTW I am using Redis package v. 1.1.0 alpha1

**Comment by mgravell** [comment]
I thought you said 1.2 earlier. It is worth using the latest dll version.

**Comment by NickCraver** [comment]
@visooof can you update us on results using the latest release please?
