### ISSUE TITLE
Secure password in the ConfigurationOptions

### ISSUE THREAD

**Issue by paveliak** [StackExchange/StackExchange.Redis#58]
I wonder if there is a way to avoid caching password in the ConnectionMultiplexer. Today ConnectionMultiplexer keeps reference to the ConfigurationOptions object that has plain text password inside. If process crashes creating minidump then password may be exposed in it.

Probably password could be stored as SecureString in the ConfigurationOptions.

**Comment by NickCraver** [comment]
This isn't a bad idea - it's the a core use case of SecureString.

**Comment by NickCraver** [comment]
Since the landscape of `SecureString` (e.g. turning it back into a string for use) hasn't really changed any in the past few years - I'm going to decline implementing this one. It just adds complexity without much benefit here. The honest situation assessment is: if you can dump memory, the machine/process is owned at that point.

**Comment by daviburg** [comment]
I'm loading the connection string as a secure string for my app and don't have any ConnectionMultiplexer.Connect overload taking a SecureString input or ConfigurationOptions with SecureString only storage of the secret.
Getting a crash dump is far from owning the machine. The very point of securestring is that hackers have used catching dumps to elevate into the next level of access.
