### ISSUE TITLE
Does Server.Time() already include roundtrip time?

### ISSUE THREAD

**Issue by ttchongtc** [StackExchange/StackExchange.Redis#592]
I want to get Redis server time so I use Server.Time(). However, there is a round trip latency in that method. When the method is called, I assume there is a request being sent out to Redis server and a request coming back to my local machine (Redis client). My question is: does the DateTime I get from Server.Time() already account for the latency of the request coming back from Redis server? Do I need to do something like below to get the precise Redis server time?

            Stopwatch sw = new Stopwatch();
            sw.Start();
            DateTime redisTime = this.redisServer.Time();
            sw.Stop();

            // Divide by 2 due to the elapsed time is the round trip.
            return redisTime.AddMilliseconds(sw.ElapsedMilliseconds / 2);

**Comment by mgravell** [comment]
Nothing fancy happens here - it literally just reports back whatever the redis server reported back. No attempt is made to account for latency, and indeed any attempt to do so can only be an approximation, because you can't tell *where* the latency happened - if all the latency was on the outbound (and nominal latency on the inbound), then you could be moving from a virtually accurate number to an entirely inaccurate one.

**Comment by NickCraver** [comment]
It's also worth nothing that many servers don't have time that's *that* accurate, not relative to the average latency to Redis. Correcting this is futile for several reasons, because the values used to base any correction on are also likely inaccurate.

**Comment by NickCraver** [comment]
Closing out to cleanup.
