### ISSUE TITLE
什么时候出.net core 版本呢，源主有这方面的打算吗？

### ISSUE THREAD

**Issue by DarrenWen** [StackExchange/StackExchange.Redis#594]

**Comment by mgravell** [comment]
"when out of the. Net core version of it, the source has this intention?"
(Google translate)

If you are asking will .net core be supported - it should already be. If
you're asking about the latest .net core drops, then: when we get to it

On 11 Mar 2017 2:47 a.m., "DarrenWen" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/594>, or mute
the thread

**Comment by NickCraver** [comment]
Closing out to cleanup.
