### ISSUE TITLE
Timeour error message has invalid link

### ISSUE THREAD

**Issue by benaadams** [StackExchange/StackExchange.Redis#619]
In the issues https://github.com/aspnet/Caching/issues/296 and https://github.com/StackExchange/StackExchange.Redis/issues/611 the exception refers to 

`https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md` which 404s

**Comment by NickCraver** [comment]
Hmmm, fixed in code, but in retrospect we never should have allowed that in - that was bound to break :(

I'm not sure we can even put a temp file there, due to Windows case insensitivity and GitHub restrictions on pages directories...

**Comment by conyg** [comment]
Can somebody provide a working link to document / documentation?

**Comment by NickCraver** [comment]
@conyg absolutely, current is: https://stackexchange.github.io/StackExchange.Redis/Timeouts

**Comment by NickCraver** [comment]
Going to close this out - current lib has the new link, and due to the combination of GitHub Pages and Windows file system constraints, we can't even reasonably put a stub in here. We've pointed at the main site URL (linked above) this round so the break won't happen again even if we shift around how pages work.
