### ISSUE TITLE
would support a method like 'db.StringPop("abc");'

### ISSUE THREAD

**Issue by liuzexiazbx** [StackExchange/StackExchange.Redis#622]
I have used methods db.StringGet("abc") and db.KeyDelete("abc").
but no methods for pop.
could support it.

and I used follow helper class with follows
```c#
namespace WebApplication.api
{
    public class RedisHelper
    {
        private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            var configurationOptions = new ConfigurationOptions
            {
                EndPoints = { { "127.0.0.1", 6379 } },
                KeepAlive = 180,
               // Password = "123456",
               // DefaultVersion = new Version("3.0.0"),
                // Needed for cache clear
                AllowAdmin = true
            };
            return ConnectionMultiplexer.Connect(configurationOptions);
        });

        public static IDatabase Connection
        {
            get
            {
                return lazyConnection.Value.GetDatabase();
            }
        }
    }
}
```
then I called as follows
```c#
RedisHelper.Connection.StringSet("test","test")
```
I wonder if I called as that,Whether it will product a lot of redis connections and make my web effective lower?
wish your help,thanks

**Comment by mgravell** [comment]
SE.Redis *essentially* surfaces the [redis API](https://redis.io/commands). There is no inbuilt redis command that does what you ask, which is why we don't expose it. If you want to do that, you could use either a multi-exec block, or a Lua script. I'd probably advise the latter, via `ScriptEvaluate`. If you prefer, in 4.0 you could write a "module" to do this, and use the new `Execute` API (in client lib 1.2.2 and above) to invoke it.

Perhaps this would also be a good feature suggestion to [rxstrings](http://redismodules.com/modules/rxstrings/) (the Redis Labs set of module extensions for 4.0); I have taken the liberty of adding https://github.com/RedisLabsModules/redex/issues/12 that cross-references this one - if the feature gets into rxstrings, I will be happy to re-expose it on an extension API (I plan on adding all of `RedisLabsModules` as add-on packages, essentially). That requires 4.0 of course.

If you need help doing this in Lua or multi-exec, let me know - I'll be delighted to put an example together. I would *guess* something like (untested):

    string s = (string)db.ScriptEvaluate(@"
        local val = redis.call('get', KEYS[1])
        redis.call('del', KEYS[1])
        return val", new RedisKey[] { key });

or:

    var get = multi.StringGetAsync(key);
    var del = multi.KeyDeleteAsync(key);
    await multi.ExecuteAsync(); // we didn't issue constraints, so don't need to loop for success
    // note that the following two will now be completed, need to sync-await them for result
    string s = await get;
    await del;

or if you aren't using `async`/`await`:

    var get = multi.StringGetAsync(key);
    var del = multi.KeyDeleteAsync(key);
    await multi.Execute(); // we didn't issue constraints, so don't need to loop for success
    // note that the following two will now be completed, need to sync-await them for result
    string s = get.Result;

**Comment by liuzexiazbx** [comment]
Thank you for your detailed answer.look forward to Redis support pop method.

**Comment by NickCraver** [comment]
Closing out to cleanup, looks like we're good here.
