### ISSUE TITLE
Is it safe to have 2 ConnectionMultiplexer for the same redis instance?

### ISSUE THREAD

**Issue by epignosisx** [StackExchange/StackExchange.Redis#642]
Our app is already using **StackExchange.Redis** implicitly through the **Microsoft.Extensions.Caching.Redis** package.

Now we want to start using StackExchange.Redis's PubSub API, however, **Microsoft.Extensions.Caching.Redis** does not give us access to the ```ConnectionMultiplexer``` it creates. I would need to create a second ```ConnectionMultiplexer``` for the same Redis.

Is is safe to create a second ```ConnectionMultiplexer```? I'm asking because I read in the docs that it is recommended to have a single ```ConnectionMultiplexer``` for the lifetime of the application.

**Comment by nemaroller** [comment]
It is safe, but if you are going to use it for pub/sub purposes, do yourself a favor and create a separate Redis instance to serve the pub/sub requests. That way you isolate your concerns. I have an instance for cache which has a maxmemory set to 85% of the total memory available, and an instance for pub/sub with 1% of the total memory available. Since Redis is single-threaded it is better to create multiple instances than attempt to use one instance to serve all needs.

**Comment by NickCraver** [comment]
As @nemaroller yes, it is safe. However, note that pipeline order is per-instance (connection), so something issued in-order on one connection and the order it's available on the other *may* not be safe. In a great many cases this doesn't matter, but just stating it as a caveat.

**Comment by epignosisx** [comment]
Thanks for the feedback folks!
