### ISSUE TITLE
SortedSetScan not returning cursor 0, looping on the last cursor value

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [StackExchange/StackExchange.Redis#652]
I want to take all the data from the sorted set on the specific patern. I'm using the command ZSCAN and its realization in StackExchange.Redis
 Sample code:     
  ```
long cursor = 0;
var result = new List<RedisValue>();
do
            {
                var values = _cache.SortedSetScan(cacheKey, pattern, 50, cursor, result.Count);
                var iter = values.GetEnumerator(); 

                while (iter.MoveNext())
                {
                    result.Add(iter.Current.Element);
                }
                cursor = ((IScanningCursor)values).Cursor;
                
            } while (cursor != 0);
```
At first I send cursor 0, after that - the next one that comand returns. But then the loop occurs and the cursor doesn't return 0 although the data is empty. Why is it happening? It should return 0. To resolve it, I had to add a condition to check whether there is some data  `  if (values.Count() == 0) break;` , but I'm not sure it's the right way to do. 

Is there some other solution (the faster one) to do the Take, Skip whithout reading all the data from  `pattern`  and doing manipulations in the code?

```
            var res = new List<T>();
            foreach (var item in result.Skip(skip).Take(take))
            {
                res.Add(JsonConvert.DeserializeObject<T>(item));
            }

```

**Comment by mgravell** [comment]
The iterator returned from `SortedSetScan` *itself* deals with the need to call recursively; to iterate over the data once, you should just need to `foreach` once over `values`. The optional cursor semantics are for advanced scenarios where you need to be able to resume a sequence in isolation. It *sounds* like the problem here is that the `.Cursor` isn't being updated in the final iteration - in which case sure: we can investigate and fix that. But you *shouldn't need it* here. Your code should be simply:

    foreach(var item in values) {...}

or perhaps simply:

    return _cache.SortedSetScan(cacheKey, pattern, 50).ToList();

Note also that the `pageOffset` is **completely unrelated** to how you're using it - it should definitely not be given the value of `result.Count`. That is the offset inside a single active batch to which the iterator has read - to allow resume, etc from positions within a single batch - the correct value to use is available from `IScanningCursor.PageOffset`, but **you shouldn't need to use this for your scenario**.

**Comment by Ilchuk-Mihail** [comment]
I couldn't find a better solution than to read all the data by the pattern and do Take, Skip in the code. Maybe you could advise me with better solutions? 
This sorted set contains the list of my friends. One object looks like this:
```
{
  "id": "5930768b0222646b24c75de7",
  "on": true
}
```
My friend's ID and his status true/false online/offline
In this case I want to do pagination/infinite scrolling through friends that are online. Pattern looks like this: ` *true*`.
This sorted set is limited to the size of 10 000 objects. 
How to choose `pageSize `parameter for this collection? What will it affect to?

**Comment by mgravell** [comment]
Are you looking for `SortedSetRangeBy{Score|Rank}[WithScores]`? can you be more specific about what the scenario is here? You have a sorted set; you have *a* value in the sorted set... now; what records do you want to fetch, and how do they relate in terms of scores in the sorted set?

**Comment by Ilchuk-Mihail** [comment]
Its a social media scenario, something similar to Fb. Every person has friends that I store in cache. Also they have a status mark (online/offline). E.g. I have 10 friends, so this list from 10 objects is in my list `friends:myId`
```
{
  "id": "5930768b0222646b24c75de7",
  "on": true
}
{
  "id": "593076bf0222646b24c75e8f",
  "on": false
}
{
  "id": "593076d30222646b24c75ea6",
  "on": true
}
...
```
For example, 7 friends is offline, 3 friends online and I need to display these people on my pages **My Friends** and **My Friends Online**. Sorted set is not being used at all now, the score is 0 for everyone. But soon these friends would have to be sorted by a certain algorithm where the popularity of the friends would be considered, and so both **My Friends** and **My Friends Online** would need to be sorted. That is why I chose the structure to simplify sorting.

Also, the key to every person is stored in the cache: `user:Id` with time to live 15 min. When the time runs out, there's a subscriber that fetches the info about removing the key and the status of this person is changed to offline for every list of every friend. Same if somebody is online - every friend can see the changed status in every list in cache.

**Comment by mgravell** [comment]
So: can I check my understanding? each user has a *different* sorted (keyed by user), which is their set of friends sorted by popularity, and what you want to do is to get all the ones where `on` is `true`?

Frankly, I'd implement it differently; I'd have two keys per user - one that is *all* their friends, and one that is their online friends only (perhaps just the ids, not full json); rather than updating the json from `true` to `false`, this is then add/remove to the sorted set (with the score if that is relevant). Then getting the online list is just "get this set", job done. Storing data in json doesn't make it easy to filter etc inside redis *unless* you use something like "rejson" (https://github.com/redislabsmodules/rejson), but I don't know enough about that module to comment on how that maps to sorted sets etc.

If you want to filter at the client instead, that's fine too.  However, it is not obvious to me that the ZSCAN defines any particular order, so if you're intending that to fetch the "top n"... that's actually a really interesting question, and I intend to ask it specifically on the redis git repo. But if you want to fetch ranges with defined order, the methods I pointed to above achieve that.

**Comment by mgravell** [comment]
group question: https://groups.google.com/forum/#!topic/redis-db/bPdIv19jRe8

**Comment by Ilchuk-Mihail** [comment]
Yes, every user has the list of his friends in cache. At first, I was thinking about 2 separate lists myself but on **My Friends page** I also need to mark friends that are online. On **My Friends Online** page there's only the list of friends that are online. If there will be 2 lists, how would I show whether the friend is online or not? 
I understand that working with  2 lists that contain only ids is easier but it would double the info and I can't see how to merge 2 lists on **My Friends page** to show both online and offline friends.

The only option I see here is to have sorted set online:friends:myId and sorted set offline:friends:myId without the list of all the friends. In that case all friends would be an intersection between `online:friends:myId `and  `offline:friends:myid`. When somebody logs in to the website, he's being transferred from the offline list to the online list and vice versa . 

Can you think of a better solution?

**Comment by NickCraver** [comment]
@Ilchuk-Mihail I'd have 2 lists: the all friends (rarely changed) and online friends. Just do the intersection in memory, the online friends would be relatively small I'd think.
