### ISSUE TITLE
SocketAsyncEventArgs for sockets

### ISSUE THREAD

**Issue by israellot** [StackExchange/StackExchange.Redis#655]
Ever considered using SocketAsyncEventArgs ?
Networking in a high usage scenario is taking takes a reasonable amount of cpu. SocketAsyncEventArgs could help bring it down.

**Comment by mgravell** [comment]
I'm well aware of SAEA and make extensive use of it in some other places.
The problem here, howeve, is the time dependency and the unreliability of
timeliness on the IO queue. we have plans to overhaul the network stack,
and one of the key things I'll be looking at is the libuv and RIO work that
has been done for Kestrel. It is my expectation that the model for this
will be a good fit.

**Comment by israellot** [comment]
You are probably right. Taking the RIO and libuv road might be great step as this is the de-facto redis client for .net. Thanks for sharing your thoughts!

**Comment by NickCraver** [comment]
The direction here has shifted quite a bit as Kestrel and .NET Core has evolved. It'll be based on the Sockets namespace now, via Pipelines. A ton of work has been done there on the Microsoft side to make it performant and reusable across all platforms...and we'll be taking advantage :) Closing out to tidy up.
