### ISSUE TITLE
Connection Timeout on AppPool Restart

### ISSUE THREAD

**Issue by markdemich** [StackExchange/StackExchange.Redis#698]
We have a web farm with 25 IIS servers.  They are all hitting the same redis server and normally is works pretty well.  We do a scheduled app pool recycle at load load times once per day and it works without incident.  However, if our app pool crashes and automatically starts up again while under medium to heavy load it will fail to connect to redis.    As a test, we set AbortOnConnectFail to false and increased the ConnectionTimeout to 5000 and that helps eliminate most of the connection errors, but now I think it will never fail and repeatedly try even if the redis goes down, which is not what we want.

Does anyone have an explanation as to why this is happening?  Any tips on debugging this would be appreciated.  What I don't understand is that under load we're hitting this redis server at a rate of up to 200,000 calls/min, and the response times are very small < 10ms.  So why would one new connection attempt take more than a 5 seconds?

Thanks for your help.

**Comment by NickCraver** [comment]
Can you paste the error? The most likely cause for this is thread pool starvation. This happens when IIS comes up under full load and steals a thread for every request, all of them likely waiting on the connection to finish. The problem there is that every new thread available (which is increases relatively slowly) is taken by IIS and none are available to complete the connection to Redis.

We found this at Stack Overflow and it affected many other async/Task based behavior as well. The best thing we did was ensure a web server came up cold from the load balancer side. In that, I mean we made it come back online as down (e.g. DRAIN vs MAINT in HAProxy land). This changes behavior so that the load balancer does the pinging as back up before slamming the app with hundreds of requests per second. Most load balancers have similarly configurable behavior. We found this *drastically* reduced our startup time for a cold application (from ~23-40 seconds to a few seconds).

The error message will tell us what's happening here (it has the thread counts in it), but it's likely the above. And changing this overall behavior in larger load balanced scenarios can be a much bigger win than just StackExchange.Redis. Also, please include the version number you're on, as we've made thread/completion changes to help with this in the 1.2.6 release.

**Comment by markdemich** [comment]
Thanks for you help.  We're using ServiceStack.Redis 1.1.608.

Unfortunately, our main problem is when an app pool crashes occasionally and we need to reconnect under load so I would love to better understand what's going on here just in case it's something that we can prevent.   Here's an excerpt of the log when it's trying to connect after an apppool recycle.  Let me know if you need more information and thanks for your help.

We're going to try upgrading and repeating our test.  We can repeat this in a perf environment so it should be clear when we get it working.

[afterrecycleAppPool_withoutanychanges.txt](https://github.com/StackExchange/StackExchange.Redis/files/1280916/afterrecycleAppPool_withoutanychanges.txt)

**Comment by markdemich** [comment]
We updated the latest client (version 1.2.6) and tried our load test again.  We loaded up all of our 10 servers with a moderate amount of load, it was about 20% of what we have at peak in production.  We then recycled a single server's app pool.  Redis did connect without error, but it took 76 seconds.  That 76 second delay caused other requests to timeout since they were also waiting for redis to connect.  

We captured the following information from the client connection call.  Is there anything here that would help to get to the bottom of this.  I'm not sure why it takes so long to establish a connection with redis.

I'm not sure about the "tie-breaker" references.  We only have one redis server so I don't know what it's breaking the tie between.

Any help would be greatly appreciated.  Thanks.

```
StackExchange Redis Connect - redis-server:6379,name=StackExchangeNonceSource,keepAlive=-1,syncTimeout=3000,connectTimeout=5000,password=*****,abortConnect=True,connectRetry=3

Connecting redis-server:6379/Interactive...
BeginConnect: redis-server:6379
1 unique nodes specified
Requesting tie-break from redis-server:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=74,Free=32693,Min=8,Max=32767)
EndConnect: redis-server:6379
Connected Interactive/redis-server:6379
Server handshake
Setting client name: StackExchangeNonceSource
Auto-configure...
Sending critical tracer: Interactive/redis-server:6379
Writing to Interactive/redis-server:6379: ECHO
Flushing outbound buffer
Starting poll
Connect complete: redis-server:6379
Response from Interactive/redis-server:6379 / ECHO: BulkString: 16 bytes
Writing to Interactive/redis-server:6379: GET __Booksleeve_TieBreak
Writing to Interactive/redis-server:6379: PING
Response from Interactive/redis-server:6379 / GET __Booksleeve_TieBreak: (null)
Response from Interactive/redis-server:6379 / PING: SimpleString: PONG
Not all tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=78,Free=32689,Min=8,Max=32767)
redis-server:6379 did not respond
All tasks are already complete
redis-server:6379 had no tiebreaker set
No masters detected
redis-server:6379: Standalone v2.8.14, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active; not in use: DidNotRespond
redis-server:6379: int ops=12, qu=0, qs=0, qc=2, wr=0, sync=10, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, sync=3, socks=1
Circular op-count snapshot; int: 0+12=12 (1.20 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from redis-server:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=78,Free=32689,Min=8,Max=32767)
Writing to Interactive/redis-server:6379: GET __Booksleeve_TieBreak
Writing to Interactive/redis-server:6379: PING
Response from Interactive/redis-server:6379 / GET __Booksleeve_TieBreak: (null)
Response from Interactive/redis-server:6379 / PING: SimpleString: PONG
All tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=78,Free=32689,Min=8,Max=32767)
redis-server:6379 returned with success
All tasks are already complete
redis-server:6379 had no tiebreaker set
Single master detected: redis-server:6379
redis-server:6379: Standalone v2.8.14, master; 16 databases; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
redis-server:6379: int ops=14, qu=0, qs=0, qc=0, wr=0, sync=11, async=2, socks=1; sub ops=3, qu=0, qs=0, qc=0, wr=0, subs=1, sync=3, socks=1
Circular op-count snapshot; int: 0+14=14 (1.40 ops/s; spans 10s); sub: 0+3=3 (0.30 ops/s; spans 10s)
Sync timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...
```

**Comment by markdemich** [comment]
@NickCraver , I was hoping you can give us your opinion based on the data we logged.  I can't imagine what could take 76 seconds to connect.

**Comment by NickCraver** [comment]
@markdemich What you're seeing is indeed thread pool starvation. Specifically, look at this in the error: `Busy=74,Free=32693,Min=8,Max=32767`, curiously close to that 76 isn't it? When the thread pool starves and hit the cap, it grows *very* slowly, at a rate of 1 per second (sadly, with no way to change that...short of making your own). When you slam the thread pool early, it'll behave like this. It's mainly because there's no completion thread available to *finish the connection*, even though it's ready to be done.

My best suggestions:

1. Don't let it traffic the app. For example, Stack Overflow had the same issue (2+ minute start), by putting HAProxy into `DRAIN` instead of `MAINT` to `ENABLE`, it status checks the apps via 1 second polls before putting it back into rotation, whereas the state machine change from `MAINT`->`ENABLE` assumed healthy and slammed the server with 300-500req/sec, quickly exhausting the pool.
2. If you must, up the initial threads in the pool. If the app needs it and you know it, upping then pool early is a good move (we do this as well). They do have cost, but *if the app is going to get there anyway*, just go ahead. For example: `ThreadPool.SetMinThreads(100, 100)` (test which values work for you).

Option 1 is very dependent on infrastructure, but option 2 is generally a quick win for high traffic apps. Be sure to call it before you try to `.Connect()` on the multiplexer.

**Comment by mgravell** [comment]
Closing; please see https://github.com/StackExchange/StackExchange.Redis/issues/871
