### ISSUE TITLE
JSON in Redis

### ISSUE THREAD

**Issue by NexusHero** [StackExchange/StackExchange.Redis#712]
Hey, 

i just wanted to publish json files in redis. I encoded  the JSON-array to an byte array, like this: 

var message = Encoding.UTF8.GetBytes(jsonArray.ToString());

But the Json has ("\r \n") in it which is a problem for other clients.
![jsonoutput-redis_new](https://user-images.githubusercontent.com/15985146/30381596-22cb59f8-989d-11e7-9fd5-6b980618aa56.png)

**Comment by NickCraver** [comment]
A few questions here: 
1. If you're storing in redis, why is the JSON pretty printed? Generally this will be a waste of space and add a lot of inefficient to, from, and in your redis usage.
2. Can you paste your full example? I'm not sure how your usage is here, generally you'd just want to cast the string as a `RedisValue` rather than encoding yourself.

**Comment by NexusHero** [comment]
Thanks for the fast reply! Yes, you are correct, its not efficient. But it's not my intention to store those additional Character along the message.

Code example: 

`var jsonArray = JArray.Parse(jsonString);
string ChannelToPublish = _getChannel();
var message = Encoding.UTF8.GetBytes(jsonArray.ToString()); 
 var db = SafeConn.GetDatabase();
db.PublishAsync(ChannelToPublish ,message );`

I thought, I would get rid of those additional character with line 3.) without using a trim(). Could you tell me how to achieve this?

Thanks in Advance!

**Comment by NexusHero** [comment]
HI there, It's not a redis bug. It's Serializer problem of Newton. I Think we can close this Issue! Sorry for takin' your time.
