### ISSUE TITLE
Reading via Dynomite 

### ISSUE THREAD

**Issue by klimchuk** [StackExchange/StackExchange.Redis#731]
We're trying to use Redis via Netflix/dynomite from C# application and dynomite failing on GetDatabase call with any parameters: -1, 0, 1 and so on. Direct connection to Redis works as expected.
Is there any way to get values without calling GetDatabase?

WARNING message shown below:
There was a problem with clustering: No connection is available to service this operation: MGET; SocketClosed on 10.51.29.190:8102/Subscription, origin: ProcessReadBytes, input-buffer: 0, outstanding: 3, last-read: 0s ago, last-write: 0s ago, unanswered-write: 0s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablishing, last-heartbeat: never, last-mbeat: -1s ago, global: 0s ago, mgr: ProcessReadQueue, err: never; IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=5,Free=32762,Min=8,Max=32767), Local-CPU: n/a

**Comment by VladimirMakaev** [comment]
We also want to use Redis with Dynomite cluster. I wonder if it's even possible with a StackExchange client?

**Comment by mgravell** [comment]
I don't know much about dynamite or dynomite cluster. For some proxies
we've pre-coded a list of available commands. It isn't clear to me what is
failing here - it looks like the pub/sub is failing, so I wonder if the
first thing to try is disabling pub/sub. A really lazy way to test that
would be to like and tell it that it is talking to twemproxy. You can set
this on ConfigurationOptions or in the config string. It it works, I'm fine
with adding a new proxy to tell it what exists in dynomite.


On 21 Nov 2017 12:18 p.m., "Vladimir Makaev" <notifications@github.com>
wrote:

We also want to use Redis with Dynomite cluster. I wonder if it's even
possible with a StackExchange client?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/731#issuecomment-346009889>,
or mute the thread

**Comment by NickCraver** [comment]
There's been no further interest in this, so given the only 2 calls I don't think it's something we'd support. But if someone's interested and it doesn't add too much weight, and we have a way to test it - we'er certainly game for taking another look :)

**Comment by RezaHN** [comment]
Is there any chance StackExchange adds support for Dynomite? We badly need it for our caching service!

**Comment by mgravell** [comment]
The core maintenance folks here aren't dynomite users, so: we don't have any direct knowledge of what is / isn't working, nor any endpoint to test on, etc. We don't even know what you're seeing - I wouldn't presume that it behaves the same today as it did in 2017, since library, server, and runtimes have all changed.

So: if there's a genuine desire for things to work with dynomite, input from dynomite users is probably needed.

**Comment by RezaHN** [comment]
We are using Dynomite to create a master-master (multi-master) replication between our Redis services. After running Docker containers of Dynomite, I can connect to them through Redis CLI. When I try to connect to them from our application which uses StackExchange Redis, I get a "Connection to ... failed" error without any details, but in log info of the Docker container there is an error which says "parsed unsupported command 'CLIENT'".

So It seems that StackExchage is using the "CLIENT" command of Redis which is not supported in Dynomite. Now my question is that: Is it possible to use StackExchange without using the "CLIENT" command? Or is there any other solution to fix this error?

PS: The list of Redis commands that Dynomite supports (or does not support) can be found in https://github.com/Netflix/dynomite/blob/dev/notes/redis.md
