### ISSUE TITLE
Redis onpremise high available

### ISSUE THREAD

**Issue by nareshkhatri81** [StackExchange/StackExchange.Redis#744]
Hi, 
How to run redis onpremise windows 2016 in HA configuration?
We want to avoid SPoC of redis instance
Redis sentient is not available for windows it seems.

Thanks

**Comment by NickCraver** [comment]
There are 2 options here with the latest stable Windows release: 3.0.504
- Redis Sentinel, which you can see working as it is in our test suite
- Redis Cluster, also setup and working in the test suite

Each of these have pros and cons. There's a great Stack Overflow answer on the benefits and downsides of each approach here: https://stackoverflow.com/q/31143072/13249

**Comment by nareshkhatri81** [comment]
For sentinel, it seems as per post. We need to have odd number so i guess we need atlest 5 nodes.
1. 2 redis master slave
2. 3 redis sentinel nodes.

Client will connect to which sentinel nodes ?

**Comment by ratzinho87** [comment]
So, does StackExchange.Redis work with Sentinel? The issue #692 suggests that it was not yet merged.

**Comment by mgravell** [comment]
we're aware of the patch, and we intend testing it in our short term plans
- historically we just haven't been in a place to have enough sentinel
knowledge to properly assess it, but we're looking to change that

On 19 Dec 2017 8:22 p.m., "ratzinho87" <notifications@github.com> wrote:

So, does StackExchange.Redis work with Sentinel? The issue #692
<https://github.com/StackExchange/StackExchange.Redis/pull/692> suggests
that it was not yet merged.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/744#issuecomment-352875540>,
or mute the thread

**Comment by NickCraver** [comment]
Discussion happening in #692 (which still lacks unit tests at the moment). I'm going to take another crack at trying to get the test suite green on Appveyor to assist this along. Closing this particular issue out to cleanup, since asked and answered :)
