### ISSUE TITLE
How to check whether the channel is exist or  not in RabbitMQ

### ISSUE THREAD

**Issue by Moinuddin147** [StackExchange/StackExchange.Redis#746]
Is there any way to check whether the rabbitmq channel is exist or not in c# application?

**Comment by mgravell** [comment]
That would probably be a question for a RabbitMQ repo? I have no clue about whether RabbitMQ even uses redis, let alone what storage / communications layout they are using.

If you can tell me what you're trying to do *in redis terms*, then I can advise you on how to do them via this lib.

**Comment by Moinuddin147** [comment]
i just want to check that particular channel is exists or not? if no then want to show error message.

**Comment by mgravell** [comment]
k; so what is a "channel" in this sentence? are you talking about a redis
pub/sub channel? or is this a rabbitmq concept that has been mapped to
another redis primitive such as a list or stream?

rabbitmq != redis

If you can ask the question in terms of what that means to redis, I can
help. If you ask in terms of rabbitmq, then ... I really can't. So, again:
what does that sebtence mean in terms of redis?

On 29 Nov 2017 2:35 a.m., "Moinuddin Patel" <notifications@github.com>
wrote:

i just want to check that particular channel is exists or not? if no then
want to show error message.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/StackExchange.Redis/issues/746#issuecomment-347733838>,
or mute the thread

**Comment by Moinuddin147** [comment]
i am not working in redis i am only work with rabbitmq.
and channel means the queue from where we can publish the message and reciever read the message.

**Comment by orck-adrouin** [comment]
You can try asking the [RabbitMQ community](https://www.rabbitmq.com/#community) you'll probably have more chance to get an answer than by asking the StackExchange.Redis guys.

**Comment by mgravell** [comment]
Closing as off-topic to this lib
