### ISSUE TITLE
Redis Timeout error

### ISSUE THREAD

**Issue by srinivas3340** [StackExchange/StackExchange.Redis#751]
Hi,

We are getting below exception frequently

A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.Timeout performing SETEX CACHE_KEY, inst: 2, mgr: Inactive, err: never, queue: 10, qu: 0, qs: 10, qc: 0, wr: 0, wq: 0, in: 28304, ar: 0, IOCP: (Busy=5,Free=995,Min=4,Max=1000), WORKER: (Busy=7,Free=32760,Min=4,Max=32767), clientName:XXXX

**Comment by CwjXFH** [comment]
@srinivas3340 ,I also encountered the same problem, the exception message include help document url:I https://stackexchange.github.io/StackExchange.Redis/Timeouts. It explains the reason of the exception.

**Comment by szh222212** [comment]
I had set the this--
ThreadPool.SetMinThreads(600, 50);
But still got the problem 
Timeout performing EVAL, inst: 185, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: ***, serverEndpoint: ***, keyHashSlot: 5549, IOCP: (Busy=0,Free=1000,Min=50,Max=1000), WORKER: (Busy=148,Free=32619,Min=600,Max=32767), Local-CPU: unavailable

**Comment by CwjXFH** [comment]
@szh222212 Now,I use stackexchange.redis by single thread,and no timeout exception.
Do you solved the problem,now?

**Comment by truthadjustr** [comment]
I echo the same observation by @CwjXFH . A single thread GET does not cause the timeout error. In my case, the timeout happens when the following combinations:

- The OS just booted up
- The very first GET coming from a subscriber handler

On succeeding GET, i no longer have the timeout. My setup is not busy and RAM is big. There is only around 3 request and key/value pair is just a name of a person.  When my app starts, it invokes the same GET on the key in the Main thread and it succeeds. However, the very first GET coming from a subscribe handler, will cause the timeout error.

**Comment by NickCraver** [comment]
Explanations inline here (and several duplicate issues active) - collapsing the timeout issues down so we can consolidate :)
