### ISSUE TITLE
RedisConnectionException and RedisTimeoutException raise too often

### ISSUE THREAD

**Issue by Bektur-Kurbanov** [StackExchange/StackExchange.Redis#770]
I haven't found any information about these exceptions. My problem is: every 2-3 hours I get one of these exceptions on production. 
StackExchange.Redis.RedisConnectionException:
"No connection is available to service this operation: PUBLISH Changeevents; It was not possible to connect to the redis server(s); ConnectTimeout; IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=4094,Min=8,Max=4095), Local-CPU: n/a"
and it's inner exception is just: "It was not possible to connect to the redis server(s); ConnectTimeout"
1) Could you explain difference between timeout and connection exception? 
2) If exception is thrown in Action(onNext) in Subscribe, after reconnect this action will never be called again, why? how to handle it?
Thanks in advance

**Comment by NickCraver** [comment]
In this case, it looks lie the connection failed and then failed to re-establish. This could be due to a network blip or severe load on the server (on either side) resulting in a connection not completing soon enough. The only quick solution here is to up the connection timeout. I'd also check your `SLOWLOG` on the redis side to see if there's a server stall in play. Sometimes a massive command like someone running `KEYS` can cause a world of hurt here.

**Comment by mgravell** [comment]
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871

**Comment by wjkhappy14** [comment]
It was not possible to connect to the redis server(s); ConnectTimeout;
 IOCP: (Busy=0,Free=1000,Min=2,Max=1000),
 WORKER: (Busy=98,Free=1949,Min=2,Max=2047), Local-CPU: n/a'
