### ISSUE TITLE
How to use SSL with Redis

### ISSUE THREAD

**Issue by arora-kushal** [StackExchange/StackExchange.Redis#772]
I want to use SSL with Redis. I've performed following steps:

Created self signed certificate by using following commands:
```
openssl req -newkey rsa:2048 -nodes -keyout cm_key.pem -x509 -days 365 -out cm_cert.pem
openssl pkcs12 -inkey cm_key.pem -in cm_cert.pem -export -out cm_cert.p12
```

Replaced following certificates on all the nodes:

- cm_cert.pem
 cm_key.pem
- api_cert.pem
 api_key.pem
- proxy_cert.pem
 proxy_key.pem

Also, copy/paste certificate in "SSL Client Authentication" textbox in Redis Cluster UI (While creating DB)

 ```
var configurationOptions = new ConfigurationOptions
                {
                    EndPoints = { "127.0.0.1:6379" },
                    Ssl = true
                }
                configurationOptions.CertificateValidation += (sender, cert, chain, errors) =>
                {
                    Console.WriteLine("errors: " + errors);
                    return true;
                };

                configurationOptions.CertificateSelection += OptionsOnCertificateSelection;
                ConnectionMultiplexer redis = ConnectionMultiplexer.Connect(configurationOptions);
                IDatabase db = redis.GetDatabase();
```
```
 private static X509Certificate OptionsOnCertificateSelection(object s, string t, X509CertificateCollection local, X509Certificate remote, string[] a)
        {
            return new X509Certificate2(@"C:\cm_cert.p12", "1234");
        }
```
The above code is working but that's only because I am bypassing certificate validation. 

Also, I am getting the error "RemoteCertificateNameMismatch" in "CertificateValidation"  #method. 

Please suggest.

**Comment by mgravell** [comment]
That's because your self-signed certificate isn't trusted by your computer. A lazy way to fix this would be to install your own CA as a trusted certificate. Otherwise: it is *required* that you provide your own certificate validator that returns true if you trust it, and false if not. You might want to check for your CA's thumbprint in the chain, for example. For a code example, perhaps [see here](https://github.com/StackExchange/StackExchange.Redis/issues/766#issuecomment-357506555)

**Comment by NickCraver** [comment]
Closing this out to cleanup, Marc's described what's happening above.
