### ISSUE TITLE
SELECT command

### ISSUE THREAD

**Issue by dmwharris** [StackExchange/StackExchange.Redis#774]
Using the SELECT command:

       string result = (string) dbConn.Execute("select","5");

result receives "OK".  However, my program is not pointed to database 5, but still points to 0.  I verified this with a Execute("CLIENT" "LIST") call.  Why am I not able to switch my database within the program?

**Comment by mgravell** [comment]
The database is specified when using GetDatabase, and is bound to that
database instance. This is very deliberate for multi-threaded scenarios, so
that two concurrent callers don't trip over each-other. Instead, it handles
the db switching internally, and to prevent unexpected problems: it doesn't
trust the state after a script or execute call, precisely because of what
you did here :)

So: tell it the database number you want when you use GetDatabase. It is ok
to make use of multiple database instances at a time as needed.

**Comment by NickCraver** [comment]
Here's a minimal example of what Marc is talking about for usage, hopefully this clears things up:
```c#
var conn = ConnectionMultiplexer.Connect("localhost"); 
var db = conn.GetDatabase(5);
var myValue = db.StringGet("mykey");
```
