### ISSUE TITLE
Different Expiry Time for Hash Fields

### ISSUE THREAD

**Issue by Sourabh721992** [StackExchange/StackExchange.Redis#801]
We can set expiry time of different string keys within the same namespace.

Can I provide different expiry time to different hash fields within the same Hash Set.

**Comment by abhit011** [comment]
Yeah , had the similar query e.g if TTL can be provided to each entry of Key-Value in HashSet then it would be great, 

e.g If I have a Millon unique ID's and I am collecting their respective time series events , I create hashset 
like ID:<uniqueId>

and in that its key value looks like 
**1 {event1: "No", event2: "No",envent3:"Yes",dttime: "2018-03-18 22:00:05" }
2 {event1: "No", event2: "Yes",envent3:"Yes",dttime: "2018-03-18 22:00:15" }
3 {event1: "No", event2: "Yes",envent3:"Yes",dttime: "2018-03-18 22:00:25" }
4 {event1: "No", event2: "Yes",envent3:"Yes",dttime: "2018-03-18 22:00:35" }
5 {event1: "No", event2: "Yes",envent3:"Yes",dttime: "2018-03-18 22:00:45" }**

The idea is to retrieve recent most 5 entries, since its a time series events , it can grow insanely huge under one HashSet only, and I feel the limit for no of keyvalue inside a HashSet is **2^32 - 1 close to 4 Billion** , If I am not wrong ? I know its huge, but still. 

I could achieve the same by using ZSET (making dttime as it ZSCORE ) and then calling ZRANGE.

But if TTL could be provided in the key value then would had been great. 

Abhi
!wq

**Comment by NickCraver** [comment]
> Can I provide different expiry time to different hash fields within the same Hash Set.

Nope, this isn't part of Redis *directly* - the TTL is only on the key directly. Some ideas: you can store the TTL on your hashed objects objects and purge on some interval yourself (somewhat expensive), discard them as they come out (this could be a leak if they never left), store only key names in your set and let redis expire them (leaving some cruft you still need to cleanup at some point in your list), or...use another approach.

**Comment by abhit011** [comment]
But purging for close to a million unique ID will take a bill toll on the system....

**Comment by abhit011** [comment]
*big toll

**Comment by NickCraver** [comment]
@abhit011 Indeed, but I'm relaying what the options are in Redis. The original question here also didn't list how many, they may not have a million like you do.

This library is only a client for functionality in Redis, we do not and cannot add anything Redis cannot already do. There's LUA scripting and modules available server-side but one giant hash just doesn't look like a good option here. A scored ZSET like you mention works _if_ the key option is doable (that's unclear from the ask), but either way: we have to work in the bounds of the data store that are available.

**Comment by abhit011** [comment]
@NickCraver I second you . 
But the idea was to ask "Will something like exist in your backlog ?":)

**Comment by mgravell** [comment]
SE.Redis exposes the functionality that redis provides. Since redis doesn't provide that, it doesn't make sense to consider it part of our backlog. If redis adds that: sure, we'll add an API to access it. But until then....

**Comment by abhit011** [comment]
Thanx Marc and Nick... I will try to handle it as per ZSET or something else...

It's a context switch but need to ask how Redis handles insane traffic insertion like multiple threads pumping data to redis port ..
_(Close to 56 Threads pumping data per process, and there would be 50 Such Processes , the math would be like 56 * 50 ~= 2800 Total Threads pumping data to Redis Port at any Second )_  ? I would say total scale would be close to 50K HashSet / Sec.

Abhi
!wq

**Comment by NickCraver** [comment]
@abhit011 It's just really well written, we can generally push 250k ops/sec on a single core with redis without issue here at Stack Overflow. It's a beast and we love it.

**Comment by abhit011** [comment]
:) for the beast ...
