### ISSUE TITLE
Time out issues

### ISSUE THREAD

**Issue by jdamhost** [StackExchange/StackExchange.Redis#806]
03/25/2018 14:19:37 +01:00 [Error] [HybridStorage] [Litecoin] An exception occurred while committing share: Timeout performing HINCRBY litecoin:stats, inst: 10, queue: 10, qu: 0, qs: 10, qc: 0, wr: 0, wq: 0, in: 294, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379, keyHashSlot: 3100, IOCP: (Busy=0,Free=200,Min=6,Max=200), WORKER: (Busy=600,Free=0,Min=6,Max=600) 

I have set up Coiniumserv and added a miner to the pool,however I am receiving this error, does anyone know how I can adjust the limits? I am on centos7

**Comment by ArtOfCode-** [comment]
So... lemme get this straight, you're using as much CPU power as possible for mining, and then wondering why other things are slow and timing out? Try leaving some spare CPU cycles for other things.

**Comment by jeremymeng** [comment]
It seems that Coiniumserv actually uses SE.Redis https://github.com/bonesoul/CoiniumServ/issues/876

**Comment by jdamhost** [comment]
that's with an asic attached without it running its fine

**Comment by jdamhost** [comment]
I'm trying to get the pool working with the miner attached I dontm ine with the CPUs on the server

**Comment by NickCraver** [comment]
In short: the thread pool is exhausting here. See this part of the exception? `WORKER: (Busy=600,Free=0,Min=6,Max=600)` - that means your thread pool has exploded to 600 threads due to contention. You're either overloaded with `async` in general, or (likely, based on experience) hitting `.Result` or `.GetAwaiter().GetResult()` in the codebase somewhere...tying up the thread pool.

**Comment by mgravell** [comment]
Closing; please see https://github.com/StackExchange/StackExchange.Redis/issues/871
