### ISSUE TITLE
ERR value is not an integer or out of range

### ISSUE THREAD

**Issue by vikrant-verma** [StackExchange/StackExchange.Redis#819]
I have this code in a lua script which I run from .net.

    `const string script = " if redis.call('EXISTS', '{0}') == 1 then" +
                              " local user = redis.call('get','{0}')" +
                              " local value = cjson.decode(user)" +
                              " value['UserPreferences'] = cjson.decode('{1}')" +
                              " value['Timestamp'] = cjson.decode('{2}')" +
                              " local val=cjson.encode(value)" +
                              " redis.call('set', '{0}', val)" +
                              " redis.call('EXPIRE', '{0}','{3}')" +
                              " end";

        var redisScript = string.Format(script, "User_" + userId, JsonConvert.SerializeObject(userPreferences), JsonConvert.SerializeObject(DateTime.UtcNow), ConfigurationManager.AppSettings["RedisKeyExpiryTime"]);
      await Cache.ScriptEvaluateAsync(redisScript);`

This returns the error :

Error: ERR value is not an integer or out of range

please give some feedback to solve the issue.

**Comment by mgravell** [comment]
Firstly, that error is coming from the server, not the client library, so
ultimately a lot of this will come down to "issue a script that is legal".

Note it is a terrible idea to use string.Format here - this could lead to
script cache saturation, and could lead to escaping vulnerabilities, and
could lead to incorrect server routing (on sharded environments).

The correct way to handle parameters is via the two additional parameters
to the ScriptEvaluate method - which allow keys and values to be supplied
for the KEYS and ARGV inbuilts as described here:
https://redis.io/commands/eval

Ultimately, though, it is hard to say much here without your full current
Lua script (after the string.Format).

If it was me, to debug this I would capture the generated string into a
text file, and then take away *almost all of it*, and add steps back a bit
at a time and run it - repeat until it breaks. Then look at the line I just
added and scratch my head a bit.

There are quite a few lines in your Lua which means it would be hard for me
to simply guess. Especially since I don't have the data that goes with it,
or your current input values.

**Comment by NickCraver** [comment]
Marc gave all the feedback with current info above - closing this out to cleanup.
