### ISSUE TITLE
RedisTimeoutException references expired URL

### ISSUE THREAD

**Issue by rusanu** [StackExchange/StackExchange.Redis#832]
The text of the message points to https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md but this returns 404. Once you let the cat out of the bag, you cannot change your mind. The URL must persist for ever and ever, no matter what is your current git layout or your current client version. Please restore the URL.

**Comment by NickCraver** [comment]
This is unfortunate, but it's also not the end of the world. We've put a canonical link (already in the lib) which points to the persistent https://stackexchange.github.io/StackExchange.Redis/Timeouts. We cannot use `/Docs` because GitHub will not render pages from there. They require `/docs`. And we cannot maintain both because we develop on Windows.

Unfortunately this isn't something we can retroactively fix, it is what it is at this point and we've moved to a URL we won't break going forward. Sorry for the trouble, but it's just not something we can reasonably resolve.
