### ISSUE TITLE
Unable to add StackExchange.Redis 1.2.6 to Visual Studio 2010 - .NET Framework 4.0

### ISSUE THREAD

**Issue by ytyagi79** [StackExchange/StackExchange.Redis#853]
Trying to add the package to one of my project in Visual Studio 2010 - .NET Framework 4.0. 

Using Command - **dotnet add package StackExchange.Redis --version 1.2.6**

Getting following error -

Installing 'StackExchange.Redis 1.2.6'.
Successfully installed 'StackExchange.Redis 1.2.6'.
Adding 'StackExchange.Redis 1.2.6' to ADAM.SearchEngine.
Uninstalling 'StackExchange.Redis 1.2.6'.
Successfully uninstalled 'StackExchange.Redis 1.2.6'.
Install failed. Rolling back...
Could not install package 'StackExchange.Redis 1.2.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by NickCraver** [comment]
StackExchange.Redis has not supported .NET Framework 4.0 since the 1.2.1 release, so you have two options for resolving:
1. Target a higher version of .NET (.NET 4.0 is very old at this point).
2. Explicitly target the 1.2.1 release, as it is the highest compatible version.

**Comment by mgravell** [comment]
Closing; ultimately it is impossible for us to support old .NET Frameworks. You're more than welcome to keep using the old lib under the caveat that it is EOL, but: the features we need [for the 2.0 enhancements](https://github.com/StackExchange/StackExchange.Redis/issues/871) - and which are very much needed - aren't ever going to work on 4.0.

We do not plan on another 4.0 deploy, sorry. That has been [officially obsolete since 2015](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/). I realize that it isn't always up to you as a developer what framework your company or client targets, but as a library author, targeting very old frameworks is sometimes easy, but sometimes an insurmountable burden - and in this case: it is the latter.
