### ISSUE TITLE
2.0: fails to resolve named by default

### ISSUE THREAD

**Issue by mgravell** [StackExchange/StackExchange.Redis#900]
Classic example `ConnectionMultiplexer.Connect("localhost:6379")` - works on 1.*, fails on 2.*

Perhaps related to @NickCraver 's overhaul of this area?

Also possibly related: all cloud tests are currently failing with socket errors; possibly the same thing?

**Comment by mgravell** [comment]
for TLS, the error from ConnectAsync is "The requested name is valid, but no data of the requested type was found"

**Comment by mgravell** [comment]
@NickCraver  that "fixes" both "localhost" and our TLS/cloud providers, but: not sure whether this does more harm than good - you know more about this area; eyeballs would be welcome

**Comment by mgravell** [comment]
The more I think about it, the more I'm tempted to say that we should resolve it at *parse time*; in particular, it would be good to have a convention to stringify and parse explicit v4 vs v6 dns addresses. However, I'm not sure if there *is* a convention for v6 dns addresses? or should this be part of dns resolve, i.e. if there are no v6 endpoints in the dns data, use a v4? but: we don't handle the dns resolution here :/

**Comment by NickCraver** [comment]
Hmm, this is tricky - we really want to offload this to the OS if we can. With DNS you can have AAAA (IPv6) and A (IPv4) records on the same endpoint. Most things (e.g. a browser) will try to establish a connection on *both* simultaneously, the first one back wins. Some things have another behavior like "try IPv6 for ~2 seconds, then go with v4".

We can't resolve at parse time (assuming you mean config parse here) because that'll break any DNS-based failovers (e.g. Azure)...really need to connect at parse time. I'm happy to poke this locally when able, but will need to get some cloud setup info from you to test the SSL bits.

If the fix as-is improves things, then that nets us: IPv6 works, DNS is IPv4 (sometimes a bad assumption). That's still a net win over v1.x and I cna poke at improving...I don't consider this any kind of blocker to v2 rolling if your current fix is testing out.

Let's say we can't get the socket to do this for us underneath (I need to dig on that front)...then we may need configurable IPv6 vs. IPv4 behavior for the case an endpoint has both (maybe an enum of some?), but ideally: we don't write this code at all and framework handles it. I'll dig and see what we can do, for now: let's just assume IPv4 *only for DNS* just before connect, that's the minimal surface area for bad assumptions that shouldn't break anything else.

Thoughts?

**Comment by NickCraver** [comment]
I'm okay closing this out. We have a net-better than v1.x and we've enabled connecting to IPv6 directly. Forcing the issue with `resolveDns` also works.

Happy to revisit this *if* it remains a problem for anyone.
