### ISSUE TITLE
Optimizing Allocations in Get in 2.0

### ISSUE THREAD

**Issue by zvolkov** [StackExchange/StackExchange.Redis#920]
Today I profiled our app for allocations, and saw that a lot of them come from the GetBlob() method of RawResult class. Basically, you're allocating an array of bytes to copy the raw data from the response buffer. As I understand, that array of bytes is later passed to the RedisValue class, I think?

Looking at [RawResult in 2.0](https://github.com/StackExchange/StackExchange.Redis/blob/pipelines/src/StackExchange.Redis/RawResult.cs), I see that the buffer was changed from byte[] to ReadOnlySequence, but you're still allocating an array of bytes to return, correct?

The particular scenario I have in mind (which I think is pretty common with other people) is storing a serialized object in Redis and deserializing it upon retrieval. I think it would be cool if we could deserialize it without allocating that array of bytes. I don't really understand how new Spans and Pipelines work, but wouldn't it be awesome to return a window onto a preallocated resusable buffer, for the consumer to feed to the deserializer, instead of allocating new array for every value?

**Comment by mgravell** [comment]
What you have described is how `RawResult` currently works. We can't do it for `RedisValue`, because:

- there is no existing contract with the consumer about how they signal that they have finished with the value
- we want to advance the underlying stream so that other messages can be consumed without blockage

What we could consider would be leading the buffer from the array pool and then allowing it to be returned via some new `Recycle()` API (or possible`Dispose()`), but *this* is complicated by the fact that `RedisValue` is a `struct` - so: easily accidentally copied with disastrous consequences.

So, that leaves the option of have a small class that represents the lease, held in the object field of the `RedisValue`, and copying from the pipeline into a leased buffer. If the consumer recycles it: great. If not... Not perfect, but we'll live.

So: that's the complications and reasons it isn't just "done". What's your thoughts on the last part, i.e. a proxy to a leased buffer?

**Comment by mgravell** [comment]
Side note: I absolutely agree with you on the utility of this. Maybe what we should consider here is a new API - `StringGetLease[Async]` for example that returns an `IMemoryLease<byte>` (I have have the interface name wrong, but: the concept exists in the new memory assembly)

**Comment by mgravell** [comment]
I think I'm going to go ahead add add a StringGetLease variant (and possibly a HashGetLease) using the same approach I spoke about t in my blog post on "SimplSockets" recently. As it happens we have a use-case for that too.

**Comment by zvolkov** [comment]
I understand and agree with your overall assessment. Byte arrays leased from a pool was my exact idea when I suspected that "we want to advance the underlying stream", thanks for confirming that.

An API to return leases for common scenarios sounds perfect. Basically, for anything that is potentially parsed or deserialized (string for JSON and XML, byte array for binary serialization). We store binary serialized objects in hashes, so HashGetLease would be nice. We also do HashGetAll quite a lot, but I'm not sure how that could benefit from these. 

Would you want to go as far as making the lease IDisposable or introducing a finalizer to ensure you don't leak the pool? Or would the struct getting off the stack would be enough to cut the root and get the lease get GC'd and the array returned to the pool?

**Comment by mgravell** [comment]
There's an existing pattern for this - IMemoryOwner-T (I discuss it here https://blog.marcgravell.com/2018/07/pipe-dreams-part-3.html). It uses disposable rather than a finalizer because in abandoned cases, the span/memory could still be in use when the original root is collected, so: finalizer would be dangerous.

**Comment by mgravell** [comment]
See commit above; feedback welcome

**Comment by mgravell** [comment]
note: for multi-value items, I guess we'd want to take it to the absurd, i.e.

```c#
Lease<Lease<byte>> StringGetLease(Lease<RedisKey> keys, ...)
```

so the result is a lease of leases, and the varadic input (keys) is *also* a lease.

**Comment by mgravell** [comment]
@NickCraver FYI for eyeballs just in case you haven't seen this API addition - makes perfect sense, and we can make *immediate* use of this in `StackRedis`

**Comment by mgravell** [comment]
Closing as implemented in 2.* - we can revisit any additional missing APIs as needed
