### ISSUE TITLE
Question: which GitHub release corresponds to the Nuget package StackExchange.Redis.1.1.603?

### ISSUE THREAD

**Issue by kristianjaeger** [StackExchange/StackExchange.Redis#941]
Thanks.

**Comment by mgravell** [comment]
Vexingly, the nearest label I can see is 1.1.605; I see that 1.1.603 is dated 16/05/2016; the only commit on that date is 0b47916a53e269835717c72a474785e10713e723, so... I'd *assume* that it was that one - especially since the two commits after that on the 20th/21st are for 1.1.604-alpha.

Sorry we didn't do a better job of book-keeping on that release, but I'm pretty confident that the answer is 0b47916a53e269835717c72a474785e10713e723

**Comment by kristianjaeger** [comment]
Thanks @mgravell !  The context is helpful.  Cheers.
