### ISSUE TITLE
Use in module for PowerShell Core (.Net Standard 2.0)

### ISSUE THREAD

**Issue by tibmeister** [StackExchange/StackExchange.Redis#948]
I am racking my brains trying to figure out how to use this as a reference in a netstandard2.0 class library that I can use as a module for PowerShell Core.  I'm open to any thoughts or suggestions.

**Comment by mgravell** [comment]
Well, how do references for PowerShell usually work? What happens if you
try that?

@NickCraver - you know a lot more about PowerShell than me; any thoughts?

**Comment by jeroenlandheer** [comment]
> I am racking my brains trying to figure out how to use this as a reference in a netstandard2.0 class library that I can use as a module for PowerShell Core. I'm open to any thoughts or suggestions.

Since you're using PowerShell Core, the library for powershell in which you have your commands should be  a .Net Core class library, not .Netstandard. You can reference .Netstandard libraries from that though. (You can use the System.Management.Automation nuget package from NuGet for the Powershell functionality, version 6.1 just got released.) 

When deploying your powershell module, use dotnet publish to grab all the DLLs together and put them in a folder, next you use publish-module with your .psd1 file to publish it to a NuGet feed. 

The PSD1 contains the name of your module, and some other metadata about your module:

```
@{
	GUID="{some-guid}"
	Author="Your name"
	CompanyName="Your company"
	ModuleVersion="1.0.0.0"
	Description="Your module's description"
	PowerShellVersion="2.0"
	CLRVersion="2.0"
	RequiredAssemblies="the name of your DLL file.dll"
	NestedModules="the name of the module"
	RootModule="the name of your DLL file.dll"
	FormatsToProcess="your-module.formats.ps1xml"
}
```

The formats file:

```
<?xml version="1.0" encoding="utf-8" ?>
<!-- Zie: https://technet.microsoft.com/en-us/library/hh847831.aspx -->
<Configuration>
</Configuration>
```

The types file:

```
<?xml version="1.0" encoding="utf-8" ?>
<!-- Zie: https://technet.microsoft.com/en-us/library/hh847881.aspx -->
<Types>

</Types>
```

Hope this gets you started :)

**Comment by NickCraver** [comment]
We've added back `net462` and `net472` builds in the `2.x` series to better support these limited scenarios. There are just too many places assembly loading is horrible to realistically dropped them. The latest client should be much more friendly for usage here.
