### ISSUE TITLE
can not work with Unity 

### ISSUE THREAD

**Issue by zhuyiif** [StackExchange/StackExchange.Redis#967]
Unity version:2018.2.6f1

error message `Unloading broken assembly Assets StackExchange.Redis.dll, this assembly can cause crashes in the runtime`

**Comment by mgravell** [comment]
I have no idea what that error message means - it seems unity specific. Is
there an inner message?

Also: What version of SE.Redis are you using?

**Comment by zhuyiif** [comment]
I figure it out, the latest stackexchange redis (2.0.513)is not working with Unity, the 1.2.6 works, so I have to use .net 1.5 redis library

**Comment by mgravell** [comment]
I wish I had more context for what that means :(

**Comment by Ancolie18** [comment]
I have a similar problem！

My Unity version is 2019.4.2f1 (.netstandard2.0).
I added the NuGet package to the C# script and used the 2.1.58 version of StackExchange.Redis. I referenced the namespace in the script, but running Unity will display an error: "The type or namespace name'StackExchange' could not be found (are you missing a using directive or an assembly reference?)".

I tried to add the dll file to Plugins separately, but it still reported an error: Assembly'Assets/Plugins/StackExchange.Redis.dll' will not be loaded due to errors: Unable to resolve reference'System.Memory'. Is the assembly missing or incompatible with the current platform? Reference validation can be disabled in the Plugin Inspector.

I also tries SE1.2.6，same problem occurred.
Does SE support its use in Unity? Or is it the cause of issues such as version?
Hope to get your reply, thank you!
