### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException

### ISSUE THREAD

**Issue by shahzadgodil** [StackExchange/StackExchange.Redis#979]
Hello,

I am getting below mentioned error

My current settings are:
<processModel autoConfig="false" minIoThreads="200" minWorkerThreads="200" />

opt.SyncTimeout = 100000
opt.AllowAdmin = True
opt.KeepAlive = 300000

An unhandled exception of type 'StackExchange.Redis.RedisTimeoutException' occurred in StackExchange.Redis.dll

Additional information: Timeout performing KEYS, inst: 0, mgr: ExecuteSelect, err: never, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 1, in: 0, ar: 0, clientName: DESKTOP-4PP7624, serverEndpoint: Unspecified/localhost:6379, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=5,Free=4090,Min=4,Max=4095) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

Thanks
Shahzad Godil

**Comment by mgravell** [comment]
That looks like the writer failed to wake in a 1.* version. We have
fundamentally overhauled this code in 2.* with the primary aim being
stability. Is it possible to try 2.*?

**Comment by mgravell** [comment]
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

If this is 1.* - sorry, that code isn't changing.
