### ISSUE TITLE
Upgrading from 1.2.6 to 2.0.513 resulting in System.BadImageFormatException

### ISSUE THREAD

**Issue by slope-taylor** [StackExchange/StackExchange.Redis#981]
I have a .NET 4.7.1 project and after simply upgrading the StackExchange.Redis NuGet package from 1.2.6 to 2.0.513, the solution builds but I get a run time error:

"System.BadImageFormatException: Cannot load a reference assembly for execution."

Has anyone else run into this?  Any help is greatly appreciated!

**Comment by ErroneousFatality** [comment]
Yeah. That's not a problem strictly related to this project. That happens when you update a lot of packages through the Nuget Package Manager and it fails to update the bindingredirect instructions in your .config file for the project.
I solved it by deleting my whole runtime -> assemblyBinding tag and running Add-BindingRedirect -Project <project name> in the Package Manager Console.

**Comment by ErroneousFatality** [comment]
Also try clearing your obj and bin folders before building, since Clear doesn't always clear cached packages.

On Nov 11, 2018 5:28 PM, Nick Craver <notifications@github.com> wrote:

@slope-taylor<https://github.com/slope-taylor> I concur it's not this package, but a package issue in general - can you try the steps above and see if that resolves? Generally, it's lack of a redirect generation that happens this. If a re-install doesn't work there, can you elaborate on your setup? For example, is it a web application, console app, other?

**Comment by slope-taylor** [comment]
@NickCraver @ErroneousFatality Thanks guys, it turns out Visual Studio was adding an extra System.Runtime binding redirect for some reason, so it in fact wasn't an issue with this specific package.  I ran into it while updating another package as well.  Rebuilding the binding redirects seems to fix it, thanks for the help!
